
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Trial
{
public partial class TbTrialRankReward
{
    private readonly System.Collections.Generic.Dictionary<int, Trial.CfgTrialRankReward> _dataMap;
    private readonly System.Collections.Generic.List<Trial.CfgTrialRankReward> _dataList;
    
    public TbTrialRankReward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Trial.CfgTrialRankReward>();
        _dataList = new System.Collections.Generic.List<Trial.CfgTrialRankReward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Trial.CfgTrialRankReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Trial.CfgTrialRankReward.DeserializeCfgTrialRankReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Trial.CfgTrialRankReward> DataMap => _dataMap;
    public System.Collections.Generic.List<Trial.CfgTrialRankReward> DataList => _dataList;

    public Trial.CfgTrialRankReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Trial.CfgTrialRankReward Get(int key) => _dataMap[key];
    public Trial.CfgTrialRankReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

