
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Trial
{
public partial class TbTrialTotal
{
    private readonly System.Collections.Generic.Dictionary<int, Trial.CfgTrialTotal> _dataMap;
    private readonly System.Collections.Generic.List<Trial.CfgTrialTotal> _dataList;
    
    public TbTrialTotal(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Trial.CfgTrialTotal>();
        _dataList = new System.Collections.Generic.List<Trial.CfgTrialTotal>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Trial.CfgTrialTotal _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Trial.CfgTrialTotal.DeserializeCfgTrialTotal(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Trial.CfgTrialTotal> DataMap => _dataMap;
    public System.Collections.Generic.List<Trial.CfgTrialTotal> DataList => _dataList;

    public Trial.CfgTrialTotal GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Trial.CfgTrialTotal Get(int key) => _dataMap[key];
    public Trial.CfgTrialTotal this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

