
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Equip
{
public sealed partial class CfgMountMain : Luban.BeanBase
{
    public CfgMountMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["sort"]; }
        { var __json0 = _buf["specialEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialEffect = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialEffect.Add(__v0); }   }
        { var __json0 = _buf["advanceCost"]; if(!__json0.IsArray) { throw new SerializationException(); } AdvanceCost = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  AdvanceCost.Add(__v0); }   }
        { if(!_buf["mountLevelID"].IsNumber) { throw new SerializationException(); }  MountLevelID = _buf["mountLevelID"]; }
        { if(!_buf["advanceMount"].IsNumber) { throw new SerializationException(); }  AdvanceMount = _buf["advanceMount"]; }
        { var __json0 = _buf["buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } Buffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buffs.Add(__v0); }   }
        { if(!_buf["animation"].IsString) { throw new SerializationException(); }  Animation = _buf["animation"]; }
        { if(!_buf["animationOffset"].IsObject) { throw new SerializationException(); }  AnimationOffset = Math.Vec3.DeserializeVec3(_buf["animationOffset"]);  }
        { if(!_buf["fx"].IsString) { throw new SerializationException(); }  Fx = _buf["fx"]; }
        { if(!_buf["fxOffset"].IsObject) { throw new SerializationException(); }  FxOffset = Math.Vec3.DeserializeVec3(_buf["fxOffset"]);  }
        { if(!_buf["shadowOffset"].IsObject) { throw new SerializationException(); }  ShadowOffset = Math.Vec3.DeserializeVec3(_buf["shadowOffset"]);  }
    }

    public static CfgMountMain DeserializeCfgMountMain(JSONNode _buf)
    {
        return new Equip.CfgMountMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 坐骑类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 坐骑编号
    /// </summary>
    public readonly int Sort;
    /// <summary>
    /// 增加属性类型
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialEffect;
    /// <summary>
    /// 进阶消耗
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> AdvanceCost;
    /// <summary>
    /// 进阶时强化等级要求
    /// </summary>
    public readonly int MountLevelID;
    /// <summary>
    /// 进阶后坐骑
    /// </summary>
    public readonly int AdvanceMount;
    /// <summary>
    /// 效果id
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buffs;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> Buffs_Ref;
    /// <summary>
    /// 动画
    /// </summary>
    public readonly string Animation;
    /// <summary>
    /// 动画偏移量
    /// </summary>
    public readonly Math.Vec3 AnimationOffset;
    /// <summary>
    /// 特效
    /// </summary>
    public readonly string Fx;
    /// <summary>
    /// 特效偏移量
    /// </summary>
    public readonly Math.Vec3 FxOffset;
    /// <summary>
    /// 阴影偏移量
    /// </summary>
    public readonly Math.Vec3 ShadowOffset;
   
    public const int __ID__ = 1751151276;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SpecialEffect) { _e?.ResolveRef(tables); }
        foreach (var _e in AdvanceCost) { _e?.ResolveRef(tables); }
        Buffs_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in Buffs) { Buffs_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "sort:" + Sort + ","
        + "specialEffect:" + Luban.StringUtil.CollectionToString(SpecialEffect) + ","
        + "advanceCost:" + Luban.StringUtil.CollectionToString(AdvanceCost) + ","
        + "mountLevelID:" + MountLevelID + ","
        + "advanceMount:" + AdvanceMount + ","
        + "buffs:" + Luban.StringUtil.CollectionToString(Buffs) + ","
        + "animation:" + Animation + ","
        + "animationOffset:" + AnimationOffset + ","
        + "fx:" + Fx + ","
        + "fxOffset:" + FxOffset + ","
        + "shadowOffset:" + ShadowOffset + ","
        + "}";
    }
}

}

