
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Equip
{
public partial class TbEquipMain
{
    private readonly System.Collections.Generic.Dictionary<int, Equip.CfgEquipMain> _dataMap;
    private readonly System.Collections.Generic.List<Equip.CfgEquipMain> _dataList;
    
    public TbEquipMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Equip.CfgEquipMain>();
        _dataList = new System.Collections.Generic.List<Equip.CfgEquipMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Equip.CfgEquipMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Equip.CfgEquipMain.DeserializeCfgEquipMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Equip.CfgEquipMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Equip.CfgEquipMain> DataList => _dataList;

    public Equip.CfgEquipMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Equip.CfgEquipMain Get(int key) => _dataMap[key];
    public Equip.CfgEquipMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

