
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Equip
{ 
    public enum Type
    {
        /// <summary>
        /// 进攻法宝
        /// </summary>
        AttackEquip = 1,
        /// <summary>
        /// 防御法宝
        /// </summary>
        DefenseEquip = 2,
    }

} 

