
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Monster
{
public partial class TbBossMain
{
    private readonly System.Collections.Generic.Dictionary<int, Monster.CfgBossMain> _dataMap;
    private readonly System.Collections.Generic.List<Monster.CfgBossMain> _dataList;
    
    public TbBossMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Monster.CfgBossMain>();
        _dataList = new System.Collections.Generic.List<Monster.CfgBossMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Monster.CfgBossMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Monster.CfgBossMain.DeserializeCfgBossMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Monster.CfgBossMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Monster.CfgBossMain> DataList => _dataList;

    public Monster.CfgBossMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Monster.CfgBossMain Get(int key) => _dataMap[key];
    public Monster.CfgBossMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

