
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Monster
{ 
    public enum Type
    {
        /// <summary>
        /// 礼物BOSS
        /// </summary>
        RandomBoss = 1,
        /// <summary>
        /// 系统BOSS
        /// </summary>
        SystemBoss = 2,
        /// <summary>
        /// 世界BOSS
        /// </summary>
        WorldBoss = 3,
    }

} 

