
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.BattleGroup
{
public sealed partial class MemberBirthFromRangeRandomPos : BattleGroup.MemberBirthPos
{
    public MemberBirthFromRangeRandomPos(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Rect"].IsObject) { throw new SerializationException(); }  Rect = Math.Rect.DeserializeRect(_buf["Rect"]);  }
    }

    public static MemberBirthFromRangeRandomPos DeserializeMemberBirthFromRangeRandomPos(JSONNode _buf)
    {
        return new BattleGroup.MemberBirthFromRangeRandomPos(_buf);
    }

    /// <summary>
    /// 矩形
    /// </summary>
    public readonly Math.Rect Rect;
   
    public const int __ID__ = 361871356;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Rect:" + Rect + ","
        + "}";
    }
}

}

