
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public sealed partial class ceng : Luban.BeanBase
{
    public ceng(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["day"].IsNumber) { throw new SerializationException(); }  Day = _buf["day"]; }
        { if(!_buf["UnableBossTime"].IsString) { throw new SerializationException(); }  UnableBossTime = _buf["UnableBossTime"]; }
    }

    public static ceng Deserializeceng(JSONNode _buf)
    {
        return new Table.ceng(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 星期几
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 不能开启时间
    /// </summary>
    public readonly string UnableBossTime;
   
    public const int __ID__ = 443257819;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "day:" + Day + ","
        + "UnableBossTime:" + UnableBossTime + ","
        + "}";
    }
}

}

