
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public sealed partial class CfgArenaMain : Luban.BeanBase
{
    public CfgArenaMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["nameRich"].IsString) { throw new SerializationException(); }  NameRich = _buf["nameRich"]; }
        { if(!_buf["rankPoint"].IsNumber) { throw new SerializationException(); }  RankPoint = _buf["rankPoint"]; }
        { if(!_buf["robotPoint"].IsNumber) { throw new SerializationException(); }  RobotPoint = _buf["robotPoint"]; }
        { var __json0 = _buf["winDrop"]; if(!__json0.IsArray) { throw new SerializationException(); } WinDrop = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  WinDrop.Add(__v0); }   }
        { var __json0 = _buf["drawDrop"]; if(!__json0.IsArray) { throw new SerializationException(); } DrawDrop = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DrawDrop.Add(__v0); }   }
        { var __json0 = _buf["loseDrop"]; if(!__json0.IsArray) { throw new SerializationException(); } LoseDrop = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  LoseDrop.Add(__v0); }   }
        { if(!_buf["robot"].IsString) { throw new SerializationException(); }  Robot = _buf["robot"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static CfgArenaMain DeserializeCfgArenaMain(JSONNode _buf)
    {
        return new Table.CfgArenaMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 段位
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 段位
    /// </summary>
    public readonly string NameRich;
    /// <summary>
    /// 积分要求
    /// </summary>
    public readonly int RankPoint;
    /// <summary>
    /// 机器人分数
    /// </summary>
    public readonly int RobotPoint;
    /// <summary>
    /// 获胜奖励
    /// </summary>
    public readonly System.Collections.Generic.List<int> WinDrop;
    public System.Collections.Generic.List<Reward.CfgRewardDrop> WinDrop_Ref;
    /// <summary>
    /// 平局奖励
    /// </summary>
    public readonly System.Collections.Generic.List<int> DrawDrop;
    public System.Collections.Generic.List<Reward.CfgRewardDrop> DrawDrop_Ref;
    /// <summary>
    /// 失败奖励
    /// </summary>
    public readonly System.Collections.Generic.List<int> LoseDrop;
    public System.Collections.Generic.List<Reward.CfgRewardDrop> LoseDrop_Ref;
    /// <summary>
    /// 机器人主角主表ID
    /// </summary>
    public readonly string Robot;
    /// <summary>
    /// 段位图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = 1921306556;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        WinDrop_Ref = new System.Collections.Generic.List<Reward.CfgRewardDrop>();
        foreach (var _v in WinDrop) { WinDrop_Ref.Add(tables.TbRewardDrop.GetOrDefault(_v)); }

        DrawDrop_Ref = new System.Collections.Generic.List<Reward.CfgRewardDrop>();
        foreach (var _v in DrawDrop) { DrawDrop_Ref.Add(tables.TbRewardDrop.GetOrDefault(_v)); }

        LoseDrop_Ref = new System.Collections.Generic.List<Reward.CfgRewardDrop>();
        foreach (var _v in LoseDrop) { LoseDrop_Ref.Add(tables.TbRewardDrop.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "nameRich:" + NameRich + ","
        + "rankPoint:" + RankPoint + ","
        + "robotPoint:" + RobotPoint + ","
        + "winDrop:" + Luban.StringUtil.CollectionToString(WinDrop) + ","
        + "drawDrop:" + Luban.StringUtil.CollectionToString(DrawDrop) + ","
        + "loseDrop:" + Luban.StringUtil.CollectionToString(LoseDrop) + ","
        + "robot:" + Robot + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}

