
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public sealed partial class CfgInstructMain : Luban.BeanBase
{
    public CfgInstructMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["plat"].IsString) { throw new SerializationException(); }  Plat = _buf["plat"]; }
        { if(!_buf["instruct"].IsString) { throw new SerializationException(); }  Instruct = _buf["instruct"]; }
        { if(!_buf["paramType"].IsNumber) { throw new SerializationException(); }  ParamType = _buf["paramType"]; }
        { if(!_buf["forward"].IsString) { throw new SerializationException(); }  Forward = _buf["forward"]; }
    }

    public static CfgInstructMain DeserializeCfgInstructMain(JSONNode _buf)
    {
        return new Table.CfgInstructMain(_buf);
    }

    /// <summary>
    /// 指令id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 平台
    /// </summary>
    public readonly string Plat;
    /// <summary>
    /// 指令
    /// </summary>
    public readonly string Instruct;
    public readonly int ParamType;
    public readonly string Forward;
   
    public const int __ID__ = -1696081353;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "plat:" + Plat + ","
        + "instruct:" + Instruct + ","
        + "paramType:" + ParamType + ","
        + "forward:" + Forward + ","
        + "}";
    }
}

}

