
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public sealed partial class CfgQualityMain : Luban.BeanBase
{
    public CfgQualityMain(JSONNode _buf) 
    {
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Item.Quality)_buf["quality"].AsInt; }
        { if(!_buf["colorCode"].IsString) { throw new SerializationException(); }  ColorCode = _buf["colorCode"]; }
    }

    public static CfgQualityMain DeserializeCfgQualityMain(JSONNode _buf)
    {
        return new Table.CfgQualityMain(_buf);
    }

    /// <summary>
    /// 品质
    /// </summary>
    public readonly Item.Quality Quality;
    /// <summary>
    /// 色号
    /// </summary>
    public readonly string ColorCode;
   
    public const int __ID__ = -639145292;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "quality:" + Quality + ","
        + "colorCode:" + ColorCode + ","
        + "}";
    }
}

}

