
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public sealed partial class CfgUnitMain : Luban.BeanBase
{
    public CfgUnitMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["UnitType"].IsNumber) { throw new SerializationException(); }  UnitType = (Unit.UnitType)_buf["UnitType"].AsInt; }
        { if(!_buf["FactionType"].IsNumber) { throw new SerializationException(); }  FactionType = _buf["FactionType"]; }
        { var _j = _buf["groupId"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  GroupId = _j; } } else { GroupId = null; } }
        GroupId_Ref = null;
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["avatar"].IsNumber) { throw new SerializationException(); }  Avatar = _buf["avatar"]; }
        { var __json0 = _buf["battleAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } BattleAttrValue = new System.Collections.Generic.Dictionary<int, long>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } long _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  BattleAttrValue.Add(_k0, _v0); }   }
        { if(!_buf["seatNo"].IsNumber) { throw new SerializationException(); }  SeatNo = _buf["seatNo"]; }
        { if(!_buf["DamageLimit"].IsNumber) { throw new SerializationException(); }  DamageLimit = _buf["DamageLimit"]; }
        { var __json0 = _buf["buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } Buffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buffs.Add(__v0); }   }
        { if(!_buf["buffDesc"].IsString) { throw new SerializationException(); }  BuffDesc = _buf["buffDesc"]; }
    }

    public static CfgUnitMain DeserializeCfgUnitMain(JSONNode _buf)
    {
        return new Table.CfgUnitMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 单位类型
    /// </summary>
    public readonly Unit.UnitType UnitType;
    /// <summary>
    /// 阵营类型
    /// </summary>
    public readonly int FactionType;
    /// <summary>
    /// 所属分组
    /// </summary>
    public readonly int? GroupId;
    public Battle.CfgBattleGroupData GroupId_Ref;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 模型id
    /// </summary>
    public readonly int Avatar;
    /// <summary>
    /// 战斗属性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, long> BattleAttrValue;
    /// <summary>
    /// 座位号
    /// </summary>
    public readonly int SeatNo;
    /// <summary>
    /// 伤害上限
    /// </summary>
    public readonly long DamageLimit;
    /// <summary>
    /// 附加的buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buffs;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> Buffs_Ref;
    /// <summary>
    /// buff描述
    /// </summary>
    public readonly string BuffDesc;
   
    public const int __ID__ = 37406593;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        GroupId_Ref = GroupId!= null ? tables.TbBattleGroup.GetOrDefault(GroupId.Value) : null;
        Buffs_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in Buffs) { Buffs_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "UnitType:" + UnitType + ","
        + "FactionType:" + FactionType + ","
        + "groupId:" + GroupId + ","
        + "level:" + Level + ","
        + "avatar:" + Avatar + ","
        + "battleAttrValue:" + Luban.StringUtil.CollectionToString(BattleAttrValue) + ","
        + "seatNo:" + SeatNo + ","
        + "DamageLimit:" + DamageLimit + ","
        + "buffs:" + Luban.StringUtil.CollectionToString(Buffs) + ","
        + "buffDesc:" + BuffDesc + ","
        + "}";
    }
}

}

