
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public partial class TbGlobalConfig
{
    private readonly System.Collections.Generic.Dictionary<string, Table.CfgGlobalConfig> _dataMap;
    private readonly System.Collections.Generic.List<Table.CfgGlobalConfig> _dataList;
    
    public TbGlobalConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Table.CfgGlobalConfig>();
        _dataList = new System.Collections.Generic.List<Table.CfgGlobalConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Table.CfgGlobalConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Table.CfgGlobalConfig.DeserializeCfgGlobalConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CombatCoefficient, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Table.CfgGlobalConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Table.CfgGlobalConfig> DataList => _dataList;

    public Table.CfgGlobalConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Table.CfgGlobalConfig Get(string key) => _dataMap[key];
    public Table.CfgGlobalConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

