
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public partial class TbInstructMain
{
    private readonly System.Collections.Generic.Dictionary<int, Table.CfgInstructMain> _dataMap;
    private readonly System.Collections.Generic.List<Table.CfgInstructMain> _dataList;
    
    public TbInstructMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Table.CfgInstructMain>();
        _dataList = new System.Collections.Generic.List<Table.CfgInstructMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Table.CfgInstructMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Table.CfgInstructMain.DeserializeCfgInstructMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Table.CfgInstructMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Table.CfgInstructMain> DataList => _dataList;

    public Table.CfgInstructMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Table.CfgInstructMain Get(int key) => _dataMap[key];
    public Table.CfgInstructMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

