
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public partial class TbLanguage
{
    private readonly System.Collections.Generic.Dictionary<int, Table.CfgLanguage> _dataMap;
    private readonly System.Collections.Generic.List<Table.CfgLanguage> _dataList;
    
    public TbLanguage(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Table.CfgLanguage>();
        _dataList = new System.Collections.Generic.List<Table.CfgLanguage>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Table.CfgLanguage _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Table.CfgLanguage.DeserializeCfgLanguage(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Table.CfgLanguage> DataMap => _dataMap;
    public System.Collections.Generic.List<Table.CfgLanguage> DataList => _dataList;

    public Table.CfgLanguage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Table.CfgLanguage Get(int key) => _dataMap[key];
    public Table.CfgLanguage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

