
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public partial class TbQualityMain
{
    private readonly System.Collections.Generic.Dictionary<Item.Quality, Table.CfgQualityMain> _dataMap;
    private readonly System.Collections.Generic.List<Table.CfgQualityMain> _dataList;
    
    public TbQualityMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<Item.Quality, Table.CfgQualityMain>();
        _dataList = new System.Collections.Generic.List<Table.CfgQualityMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Table.CfgQualityMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Table.CfgQualityMain.DeserializeCfgQualityMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Quality, _v);
        }
    }

    public System.Collections.Generic.Dictionary<Item.Quality, Table.CfgQualityMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Table.CfgQualityMain> DataList => _dataList;

    public Table.CfgQualityMain GetOrDefault(Item.Quality key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Table.CfgQualityMain Get(Item.Quality key) => _dataMap[key];
    public Table.CfgQualityMain this[Item.Quality key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

