
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Stage
{ 
    public enum AutoType
    {
        /// <summary>
        /// 不解锁自动<br/>
        /// </summary>
        NotUnlocked = 0,
        /// <summary>
        /// 通关后解锁自动
        /// </summary>
        UnlockedAfterClear = 1,
        /// <summary>
        /// 不通关也解锁自动
        /// </summary>
        UnlockedWithoutClear = 2,
    }

} 

