
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Stage
{
public sealed partial class CfgStageType : Luban.BeanBase
{
    public CfgStageType(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["type"]; if(!__json0.IsArray) { throw new SerializationException(); } Type = new System.Collections.Generic.List<Stage.Type>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Stage.Type __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (Stage.Type)__e0.AsInt; }  Type.Add(__v0); }   }
        { if(!_buf["isResurrect"].IsBoolean) { throw new SerializationException(); }  IsResurrect = _buf["isResurrect"]; }
        { if(!_buf["levelLimit"].IsNumber) { throw new SerializationException(); }  LevelLimit = _buf["levelLimit"]; }
        { var __json0 = _buf["stageList"]; if(!__json0.IsArray) { throw new SerializationException(); } StageList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  StageList.Add(__v0); }   }
    }

    public static CfgStageType DeserializeCfgStageType(JSONNode _buf)
    {
        return new Stage.CfgStageType(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly System.Collections.Generic.List<Stage.Type> Type;
    /// <summary>
    /// 是否有自动复活
    /// </summary>
    public readonly bool IsResurrect;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public readonly int LevelLimit;
    /// <summary>
    /// 关卡组
    /// </summary>
    public readonly System.Collections.Generic.List<int> StageList;
   
    public const int __ID__ = 1693887620;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Luban.StringUtil.CollectionToString(Type) + ","
        + "isResurrect:" + IsResurrect + ","
        + "levelLimit:" + LevelLimit + ","
        + "stageList:" + Luban.StringUtil.CollectionToString(StageList) + ","
        + "}";
    }
}

}

