
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Stage
{
public partial class TbStageType
{
    private readonly System.Collections.Generic.Dictionary<int, Stage.CfgStageType> _dataMap;
    private readonly System.Collections.Generic.List<Stage.CfgStageType> _dataList;
    
    public TbStageType(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Stage.CfgStageType>();
        _dataList = new System.Collections.Generic.List<Stage.CfgStageType>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Stage.CfgStageType _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Stage.CfgStageType.DeserializeCfgStageType(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Stage.CfgStageType> DataMap => _dataMap;
    public System.Collections.Generic.List<Stage.CfgStageType> DataList => _dataList;

    public Stage.CfgStageType GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Stage.CfgStageType Get(int key) => _dataMap[key];
    public Stage.CfgStageType this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

