
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Stage
{ 
    public enum Type
    {
        /// <summary>
        /// 挂机类型
        /// </summary>
        Noraml = 0,
        /// <summary>
        /// 随机BOSS类型
        /// </summary>
        RandomBoss = 1,
        /// <summary>
        /// 论道
        /// </summary>
        CampWar = 2,
        /// <summary>
        /// 系统boss
        /// </summary>
        SystemBoss = 3,
        /// <summary>
        /// 世界BOSS
        /// </summary>
        WorldBoss = 4,
        /// <summary>
        /// 幻境副本
        /// </summary>
        Dungeon = 5,
        /// <summary>
        /// 宗门试炼
        /// </summary>
        Trial = 6,
    }

} 

