
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.BattleGroup
{
public abstract partial class MemberBirthRot : Luban.BeanBase
{
    public MemberBirthRot(JSONNode _buf) 
    {
    }

    public static MemberBirthRot DeserializeMemberBirthRot(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "MemberBirthFromGroupRot": return new BattleGroup.MemberBirthFromGroupRot(_buf);
            case "MemberBirthRandomRot": return new BattleGroup.MemberBirthRandomRot(_buf);
            case "MemberBirthFromMapAreaBossRot": return new BattleGroup.MemberBirthFromMapAreaBossRot(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

