
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.BattleGroup
{
public sealed partial class MemberBirthFromCircleRandomPos : BattleGroup.MemberBirthPos
{
    public MemberBirthFromCircleRandomPos(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["minRadius"].IsNumber) { throw new SerializationException(); }  MinRadius = _buf["minRadius"]; }
        { if(!_buf["maxRadius"].IsNumber) { throw new SerializationException(); }  MaxRadius = _buf["maxRadius"]; }
    }

    public static MemberBirthFromCircleRandomPos DeserializeMemberBirthFromCircleRandomPos(JSONNode _buf)
    {
        return new BattleGroup.MemberBirthFromCircleRandomPos(_buf);
    }

    /// <summary>
    /// 最小半径(厘米)
    /// </summary>
    public readonly int MinRadius;
    /// <summary>
    /// 最大半径(厘米)
    /// </summary>
    public readonly int MaxRadius;
   
    public const int __ID__ = 1050823289;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "minRadius:" + MinRadius + ","
        + "maxRadius:" + MaxRadius + ","
        + "}";
    }
}

}

