
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.BattleGroup
{
public sealed partial class MemberBirthRandomRot : BattleGroup.MemberBirthRot
{
    public MemberBirthRandomRot(JSONNode _buf)  : base(_buf) 
    {
    }

    public static MemberBirthRandomRot DeserializeMemberBirthRandomRot(JSONNode _buf)
    {
        return new BattleGroup.MemberBirthRandomRot(_buf);
    }

   
    public const int __ID__ = -850952074;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

