
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Equip
{
public sealed partial class CfgEquipLevel : Luban.BeanBase
{
    public CfgEquipLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["equipLevel"].IsNumber) { throw new SerializationException(); }  EquipLevel = _buf["equipLevel"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Equip.Type)_buf["type"].AsInt; }
        { var __json0 = _buf["cost"]; if(!__json0.IsArray) { throw new SerializationException(); } Cost = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Cost.Add(__v0); }   }
        { var __json0 = _buf["specialEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialEffect = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialEffect.Add(__v0); }   }
    }

    public static CfgEquipLevel DeserializeCfgEquipLevel(JSONNode _buf)
    {
        return new Equip.CfgEquipLevel(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 强化等级
    /// </summary>
    public readonly int EquipLevel;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Equip.Type Type;
    /// <summary>
    /// 消耗道具
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Cost;
    /// <summary>
    /// 增加属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialEffect;
   
    public const int __ID__ = 445421370;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Cost) { _e?.ResolveRef(tables); }
        foreach (var _e in SpecialEffect) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "equipLevel:" + EquipLevel + ","
        + "type:" + Type + ","
        + "cost:" + Luban.StringUtil.CollectionToString(Cost) + ","
        + "specialEffect:" + Luban.StringUtil.CollectionToString(SpecialEffect) + ","
        + "}";
    }
}

}

