
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Equip
{
public sealed partial class CfgEquipMain : Luban.BeanBase
{
    public CfgEquipMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Equip.Type)_buf["type"].AsInt; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Item.Quality)_buf["quality"].AsInt; }
        { var __json0 = _buf["specialEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialEffect = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialEffect.Add(__v0); }   }
        { var __json0 = _buf["advanceCost"]; if(!__json0.IsArray) { throw new SerializationException(); } AdvanceCost = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  AdvanceCost.Add(__v0); }   }
        { if(!_buf["equipLevelID"].IsNumber) { throw new SerializationException(); }  EquipLevelID = _buf["equipLevelID"]; }
        { if(!_buf["advanceEquip"].IsNumber) { throw new SerializationException(); }  AdvanceEquip = _buf["advanceEquip"]; }
        { if(!_buf["Buffs"].IsNumber) { throw new SerializationException(); }  Buffs = _buf["Buffs"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static CfgEquipMain DeserializeCfgEquipMain(JSONNode _buf)
    {
        return new Equip.CfgEquipMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Equip.Type Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Item.Quality Quality;
    /// <summary>
    /// 增加属性类型
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialEffect;
    /// <summary>
    /// 进阶消耗
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> AdvanceCost;
    /// <summary>
    /// 进阶时强化等级要求
    /// </summary>
    public readonly int EquipLevelID;
    /// <summary>
    /// 进阶后法宝
    /// </summary>
    public readonly int AdvanceEquip;
    /// <summary>
    /// 效果id
    /// </summary>
    public readonly int Buffs;
    /// <summary>
    /// 法宝图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = -1925268669;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SpecialEffect) { _e?.ResolveRef(tables); }
        foreach (var _e in AdvanceCost) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "specialEffect:" + Luban.StringUtil.CollectionToString(SpecialEffect) + ","
        + "advanceCost:" + Luban.StringUtil.CollectionToString(AdvanceCost) + ","
        + "equipLevelID:" + EquipLevelID + ","
        + "advanceEquip:" + AdvanceEquip + ","
        + "Buffs:" + Buffs + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}

