
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Equip
{
public partial class TbMountLevel
{
    private readonly System.Collections.Generic.Dictionary<int, Equip.CfgMountLevel> _dataMap;
    private readonly System.Collections.Generic.List<Equip.CfgMountLevel> _dataList;
    
    public TbMountLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Equip.CfgMountLevel>();
        _dataList = new System.Collections.Generic.List<Equip.CfgMountLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Equip.CfgMountLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Equip.CfgMountLevel.DeserializeCfgMountLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Equip.CfgMountLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<Equip.CfgMountLevel> DataList => _dataList;

    public Equip.CfgMountLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Equip.CfgMountLevel Get(int key) => _dataMap[key];
    public Equip.CfgMountLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

