
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Equip
{
public partial class TbMountMain
{
    private readonly System.Collections.Generic.Dictionary<int, Equip.CfgMountMain> _dataMap;
    private readonly System.Collections.Generic.List<Equip.CfgMountMain> _dataList;
    
    public TbMountMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Equip.CfgMountMain>();
        _dataList = new System.Collections.Generic.List<Equip.CfgMountMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Equip.CfgMountMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Equip.CfgMountMain.DeserializeCfgMountMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Equip.CfgMountMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Equip.CfgMountMain> DataList => _dataList;

    public Equip.CfgMountMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Equip.CfgMountMain Get(int key) => _dataMap[key];
    public Equip.CfgMountMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

