
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    public enum AttributeDamageType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 风属性伤害
        /// </summary>
        Wind = 1,
        /// <summary>
        /// 土属性伤害
        /// </summary>
        Earth = 2,
        /// <summary>
        /// 水属性伤害
        /// </summary>
        Water = 3,
        /// <summary>
        /// 火属性伤害
        /// </summary>
        Fire = 4,
    }

} 

