
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleFxData : Luban.BeanBase
{
    public CfgBattleFxData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["resPath"].IsString) { throw new SerializationException(); }  ResPath = _buf["resPath"]; }
        { if(!_buf["keepTime"].IsNumber) { throw new SerializationException(); }  KeepTime = _buf["keepTime"]; }
        { if(!_buf["loopCount"].IsNumber) { throw new SerializationException(); }  LoopCount = _buf["loopCount"]; }
        { if(!_buf["delayDestoryTime"].IsNumber) { throw new SerializationException(); }  DelayDestoryTime = _buf["delayDestoryTime"]; }
        { if(!_buf["offset"].IsObject) { throw new SerializationException(); }  Offset = Math.Vec3.DeserializeVec3(_buf["offset"]);  }
    }

    public static CfgBattleFxData DeserializeCfgBattleFxData(JSONNode _buf)
    {
        return new Battle.CfgBattleFxData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 特效路径
    /// </summary>
    public readonly string ResPath;
    /// <summary>
    /// 持续时间(ms)
    /// </summary>
    public readonly int KeepTime;
    /// <summary>
    /// 循环次数
    /// </summary>
    public readonly int LoopCount;
    /// <summary>
    /// 延迟消毁时间(ms)
    /// </summary>
    public readonly int DelayDestoryTime;
    /// <summary>
    /// 偏移量
    /// </summary>
    public readonly Math.Vec3 Offset;
   
    public const int __ID__ = -738063422;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "resPath:" + ResPath + ","
        + "keepTime:" + KeepTime + ","
        + "loopCount:" + LoopCount + ","
        + "delayDestoryTime:" + DelayDestoryTime + ","
        + "offset:" + Offset + ","
        + "}";
    }
}

}

