
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleSkillBBParamData : Luban.BeanBase
{
    public CfgBattleSkillBBParamData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["level1Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level1Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level1Params.Add(_k0, _v0); }   }
        { var __json0 = _buf["level2Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level2Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level2Params.Add(_k0, _v0); }   }
        { var __json0 = _buf["level3Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level3Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level3Params.Add(_k0, _v0); }   }
        { var __json0 = _buf["level4Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level4Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level4Params.Add(_k0, _v0); }   }
        { var __json0 = _buf["level5Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level5Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level5Params.Add(_k0, _v0); }   }
        { var __json0 = _buf["level6Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level6Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level6Params.Add(_k0, _v0); }   }
        { var __json0 = _buf["level7Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level7Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level7Params.Add(_k0, _v0); }   }
        { var __json0 = _buf["level8Params"]; if(!__json0.IsArray) { throw new SerializationException(); } Level8Params = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Level8Params.Add(_k0, _v0); }   }
    }

    public static CfgBattleSkillBBParamData DeserializeCfgBattleSkillBBParamData(JSONNode _buf)
    {
        return new Battle.CfgBattleSkillBBParamData(_buf);
    }

    /// <summary>
    /// id(技能ID)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级1黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level1Params;
    /// <summary>
    /// 等级2黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level2Params;
    /// <summary>
    /// 等级3黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level3Params;
    /// <summary>
    /// 等级4黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level4Params;
    /// <summary>
    /// 等级5黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level5Params;
    /// <summary>
    /// 等级6黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level6Params;
    /// <summary>
    /// 等级7黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level7Params;
    /// <summary>
    /// 等级8黑板参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Level8Params;
   
    public const int __ID__ = 1292170028;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level1Params:" + Luban.StringUtil.CollectionToString(Level1Params) + ","
        + "level2Params:" + Luban.StringUtil.CollectionToString(Level2Params) + ","
        + "level3Params:" + Luban.StringUtil.CollectionToString(Level3Params) + ","
        + "level4Params:" + Luban.StringUtil.CollectionToString(Level4Params) + ","
        + "level5Params:" + Luban.StringUtil.CollectionToString(Level5Params) + ","
        + "level6Params:" + Luban.StringUtil.CollectionToString(Level6Params) + ","
        + "level7Params:" + Luban.StringUtil.CollectionToString(Level7Params) + ","
        + "level8Params:" + Luban.StringUtil.CollectionToString(Level8Params) + ","
        + "}";
    }
}

}

