
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleSkillData : Luban.BeanBase
{
    public CfgBattleSkillData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["enabled"].IsBoolean) { throw new SerializationException(); }  Enabled = _buf["enabled"]; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Skill.SkillType)_buf["type"].AsInt; }
        { if(!_buf["cate"].IsNumber) { throw new SerializationException(); }  Cate = (Skill.SkillCate)_buf["cate"].AsInt; }
        { if(!_buf["attributeDamageType"].IsNumber) { throw new SerializationException(); }  AttributeDamageType = (Battle.AttributeDamageType)_buf["attributeDamageType"].AsInt; }
        { if(!_buf["isEnergy"].IsBoolean) { throw new SerializationException(); }  IsEnergy = _buf["isEnergy"]; }
        { if(!_buf["isManualRelease"].IsBoolean) { throw new SerializationException(); }  IsManualRelease = _buf["isManualRelease"]; }
        { if(!_buf["recovery"].IsObject) { throw new SerializationException(); }  Recovery = Skill.RecoveryData.DeserializeRecoveryData(_buf["recovery"]);  }
        { if(!_buf["isSaveSkillCd"].IsBoolean) { throw new SerializationException(); }  IsSaveSkillCd = _buf["isSaveSkillCd"]; }
        { if(!_buf["finishGap"].IsNumber) { throw new SerializationException(); }  FinishGap = _buf["finishGap"]; }
        { if(!_buf["mode"].IsNumber) { throw new SerializationException(); }  Mode = (Skill.AttackMode)_buf["mode"].AsInt; }
        { if(!_buf["isInterrupt"].IsBoolean) { throw new SerializationException(); }  IsInterrupt = _buf["isInterrupt"]; }
        { if(!_buf["skill_min_distance"].IsNumber) { throw new SerializationException(); }  SkillMinDistance = _buf["skill_min_distance"]; }
        { if(!_buf["skill_max_distance"].IsNumber) { throw new SerializationException(); }  SkillMaxDistance = _buf["skill_max_distance"]; }
        { if(!_buf["isOutBattle"].IsBoolean) { throw new SerializationException(); }  IsOutBattle = _buf["isOutBattle"]; }
        { if(!_buf["isWithoutTarget"].IsBoolean) { throw new SerializationException(); }  IsWithoutTarget = _buf["isWithoutTarget"]; }
        { if(!_buf["isDeathUse"].IsBoolean) { throw new SerializationException(); }  IsDeathUse = _buf["isDeathUse"]; }
        { if(!_buf["maxUseCount"].IsNumber) { throw new SerializationException(); }  MaxUseCount = _buf["maxUseCount"]; }
        { if(!_buf["isInterruptMove"].IsBoolean) { throw new SerializationException(); }  IsInterruptMove = _buf["isInterruptMove"]; }
        { if(!_buf["kupp"].IsNumber) { throw new SerializationException(); }  Kupp = _buf["kupp"]; }
        { var __json0 = _buf["triggerConditions"]; if(!__json0.IsArray) { throw new SerializationException(); } TriggerConditions = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  TriggerConditions.Add(__v0); }   }
        { if(!_buf["triggerType"].IsBoolean) { throw new SerializationException(); }  TriggerType = _buf["triggerType"]; }
        { if(!_buf["findTargetData"].IsObject) { throw new SerializationException(); }  FindTargetData = Unit.TargetFindData.DeserializeTargetFindData(_buf["findTargetData"]);  }
        { if(!_buf["filterTargetData"].IsObject) { throw new SerializationException(); }  FilterTargetData = Unit.TargetFilterData.DeserializeTargetFilterData(_buf["filterTargetData"]);  }
    }

    public static CfgBattleSkillData DeserializeCfgBattleSkillData(JSONNode _buf)
    {
        return new Battle.CfgBattleSkillData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 是否激活
    /// </summary>
    public readonly bool Enabled;
    /// <summary>
    /// 技能优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly Skill.SkillType Type;
    /// <summary>
    /// 技能类别
    /// </summary>
    public readonly Skill.SkillCate Cate;
    /// <summary>
    /// 属性伤害类型
    /// </summary>
    public readonly Battle.AttributeDamageType AttributeDamageType;
    /// <summary>
    /// 是否能量技
    /// </summary>
    public readonly bool IsEnergy;
    /// <summary>
    /// 是否手动释放
    /// </summary>
    public readonly bool IsManualRelease;
    /// <summary>
    /// 技能恢复类型
    /// </summary>
    public readonly Skill.RecoveryData Recovery;
    /// <summary>
    /// 是否保存技能CD
    /// </summary>
    public readonly bool IsSaveSkillCd;
    /// <summary>
    /// 技能完成间隔(毫秒)
    /// </summary>
    public readonly int FinishGap;
    /// <summary>
    /// 攻击模式
    /// </summary>
    public readonly Skill.AttackMode Mode;
    /// <summary>
    /// 是否<br/>能被打断
    /// </summary>
    public readonly bool IsInterrupt;
    /// <summary>
    /// 最小射程
    /// </summary>
    public readonly int SkillMinDistance;
    /// <summary>
    /// 最大射程<br/>(手动技能释放范围和最大半径保持一致)
    /// </summary>
    public readonly int SkillMaxDistance;
    /// <summary>
    /// 战斗未激活能否激活该技能
    /// </summary>
    public readonly bool IsOutBattle;
    /// <summary>
    /// 没有目标能否激活技能
    /// </summary>
    public readonly bool IsWithoutTarget;
    /// <summary>
    /// 技能持有者死亡<br/>能否激活技能
    /// </summary>
    public readonly bool IsDeathUse;
    /// <summary>
    /// 全局最大<br/>释放次数
    /// </summary>
    public readonly int MaxUseCount;
    /// <summary>
    /// 是否打断移动
    /// </summary>
    public readonly bool IsInterruptMove;
    /// <summary>
    /// 击飞概率(万分比)
    /// </summary>
    public readonly int Kupp;
    /// <summary>
    /// 触发条件
    /// </summary>
    public readonly System.Collections.Generic.List<int> TriggerConditions;
    public System.Collections.Generic.List<Battle.CfgBattleSkillTriggerData> TriggerConditions_Ref;
    /// <summary>
    /// 触发条件<br/>组合方式
    /// </summary>
    public readonly bool TriggerType;
    public readonly Unit.TargetFindData FindTargetData;
    public readonly Unit.TargetFilterData FilterTargetData;
   
    public const int __ID__ = -1833955403;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Recovery?.ResolveRef(tables);
        TriggerConditions_Ref = new System.Collections.Generic.List<Battle.CfgBattleSkillTriggerData>();
        foreach (var _v in TriggerConditions) { TriggerConditions_Ref.Add(tables.TbBattleSkillTrigger.GetOrDefault(_v)); }

        FindTargetData?.ResolveRef(tables);
        FilterTargetData?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "enabled:" + Enabled + ","
        + "priority:" + Priority + ","
        + "type:" + Type + ","
        + "cate:" + Cate + ","
        + "attributeDamageType:" + AttributeDamageType + ","
        + "isEnergy:" + IsEnergy + ","
        + "isManualRelease:" + IsManualRelease + ","
        + "recovery:" + Recovery + ","
        + "isSaveSkillCd:" + IsSaveSkillCd + ","
        + "finishGap:" + FinishGap + ","
        + "mode:" + Mode + ","
        + "isInterrupt:" + IsInterrupt + ","
        + "skillMinDistance:" + SkillMinDistance + ","
        + "skillMaxDistance:" + SkillMaxDistance + ","
        + "isOutBattle:" + IsOutBattle + ","
        + "isWithoutTarget:" + IsWithoutTarget + ","
        + "isDeathUse:" + IsDeathUse + ","
        + "maxUseCount:" + MaxUseCount + ","
        + "isInterruptMove:" + IsInterruptMove + ","
        + "kupp:" + Kupp + ","
        + "triggerConditions:" + Luban.StringUtil.CollectionToString(TriggerConditions) + ","
        + "triggerType:" + TriggerType + ","
        + "findTargetData:" + FindTargetData + ","
        + "filterTargetData:" + FilterTargetData + ","
        + "}";
    }
}

}

