
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CondComparePropertyData : Battle.ConditionData
{
    public CondComparePropertyData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["targetSource"].IsNumber) { throw new SerializationException(); }  TargetSource = (Target.TargetAttackType)_buf["targetSource"].AsInt; }
        { if(!_buf["compareMode"].IsNumber) { throw new SerializationException(); }  CompareMode = (Condition.CompareMode)_buf["compareMode"].AsInt; }
        { if(!_buf["propertyType"].IsNumber) { throw new SerializationException(); }  PropertyType = (Battle.PropertyType)_buf["propertyType"].AsInt; }
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
    }

    public static CondComparePropertyData DeserializeCondComparePropertyData(JSONNode _buf)
    {
        return new Battle.CondComparePropertyData(_buf);
    }

    /// <summary>
    /// 目标来源
    /// </summary>
    public readonly Target.TargetAttackType TargetSource;
    /// <summary>
    /// 比较方式
    /// </summary>
    public readonly Condition.CompareMode CompareMode;
    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly Battle.PropertyType PropertyType;
    /// <summary>
    /// 比较值万分比
    /// </summary>
    public readonly long PctValue;
    /// <summary>
    /// 比较固定值
    /// </summary>
    public readonly long FixedValue;
   
    public const int __ID__ = 1845271276;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "compareMode:" + CompareMode + ","
        + "propertyType:" + PropertyType + ","
        + "pctValue:" + PctValue + ","
        + "fixedValue:" + FixedValue + ","
        + "}";
    }
}

}

