
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public abstract partial class ConditionData : Condition.ConditionData
{
    public ConditionData(JSONNode _buf)  : base(_buf) 
    {
    }

    public static ConditionData DeserializeConditionData(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "CondFrameData": return new Battle.CondFrameData(_buf);
            case "CondComparePropertyData": return new Battle.CondComparePropertyData(_buf);
            case "Buff.CondUnitEventTypeData": return new Buff.CondUnitEventTypeData(_buf);
            case "Buff.CondBuffEventData": return new Buff.CondBuffEventData(_buf);
            case "Buff.CondPeriodicActivateData": return new Buff.CondPeriodicActivateData(_buf);
            case "Buff.CondDurationTimeData": return new Buff.CondDurationTimeData(_buf);
            case "Skill.CondRandomPerData": return new Skill.CondRandomPerData(_buf);
            case "Skill.CondUnitEventTypeData": return new Skill.CondUnitEventTypeData(_buf);
            case "Skill.CondUnitNoMainTargetData": return new Skill.CondUnitNoMainTargetData(_buf);
            case "Skill.CondUnitGroupTypeData": return new Skill.CondUnitGroupTypeData(_buf);
            case "Skill.CondUnitRandomAtivateSkillData": return new Skill.CondUnitRandomAtivateSkillData(_buf);
            case "Skill.CondCompareHpData": return new Skill.CondCompareHpData(_buf);
            case "Skill.CondSkillCateUseData": return new Skill.CondSkillCateUseData(_buf);
            case "Skill.CondSkillAttackCountData": return new Skill.CondSkillAttackCountData(_buf);
            case "Skill.CondHasBuffData": return new Skill.CondHasBuffData(_buf);
            case "Skill.CondHasBuffStateData": return new Skill.CondHasBuffStateData(_buf);
            case "Skill.CondTargetBodyTypeData": return new Skill.CondTargetBodyTypeData(_buf);
            case "Skill.CondUnitDeathData": return new Skill.CondUnitDeathData(_buf);
            default: throw new SerializationException();
        }
    }

   

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

