
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TbBattleSkillMain
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfgBattleSkillData> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfgBattleSkillData> _dataList;
    
    public TbBattleSkillMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfgBattleSkillData>();
        _dataList = new System.Collections.Generic.List<Battle.CfgBattleSkillData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.CfgBattleSkillData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Battle.CfgBattleSkillData.DeserializeCfgBattleSkillData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfgBattleSkillData> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfgBattleSkillData> DataList => _dataList;

    public Battle.CfgBattleSkillData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfgBattleSkillData Get(int key) => _dataMap[key];
    public Battle.CfgBattleSkillData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

