
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TbBattleGroup
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfgBattleGroupData> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfgBattleGroupData> _dataList;
    
    public TbBattleGroup(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfgBattleGroupData>();
        _dataList = new System.Collections.Generic.List<Battle.CfgBattleGroupData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.CfgBattleGroupData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Battle.CfgBattleGroupData.DeserializeCfgBattleGroupData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfgBattleGroupData> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfgBattleGroupData> DataList => _dataList;

    public Battle.CfgBattleGroupData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfgBattleGroupData Get(int key) => _dataMap[key];
    public Battle.CfgBattleGroupData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

