
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Event
{
public sealed partial class CfgEventMain : Luban.BeanBase
{
    public CfgEventMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Event.Type)_buf["type"].AsInt; }
        { if(!_buf["rate"].IsNumber) { throw new SerializationException(); }  Rate = _buf["rate"]; }
        { var __json0 = _buf["drop"]; if(!__json0.IsArray) { throw new SerializationException(); } Drop = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Drop.Add(__v0); }   }
        { var __json0 = _buf["successNotice"]; if(!__json0.IsArray) { throw new SerializationException(); } SuccessNotice = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SuccessNotice.Add(__v0); }   }
        { var __json0 = _buf["failNotice"]; if(!__json0.IsArray) { throw new SerializationException(); } FailNotice = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FailNotice.Add(__v0); }   }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static CfgEventMain DeserializeCfgEventMain(JSONNode _buf)
    {
        return new Event.CfgEventMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Event.Type Type;
    /// <summary>
    /// 随机权重
    /// </summary>
    public readonly int Rate;
    public readonly System.Collections.Generic.List<int> Drop;
    public System.Collections.Generic.List<Reward.CfgRewardDrop> Drop_Ref;
    /// <summary>
    /// 成功提示
    /// </summary>
    public readonly System.Collections.Generic.List<int> SuccessNotice;
    public System.Collections.Generic.List<Table.CfgLanguage> SuccessNotice_Ref;
    /// <summary>
    /// 失败提示
    /// </summary>
    public readonly System.Collections.Generic.List<int> FailNotice;
    public System.Collections.Generic.List<Table.CfgLanguage> FailNotice_Ref;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = 301281923;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Drop_Ref = new System.Collections.Generic.List<Reward.CfgRewardDrop>();
        foreach (var _v in Drop) { Drop_Ref.Add(tables.TbRewardDrop.GetOrDefault(_v)); }

        SuccessNotice_Ref = new System.Collections.Generic.List<Table.CfgLanguage>();
        foreach (var _v in SuccessNotice) { SuccessNotice_Ref.Add(tables.TbLanguage.GetOrDefault(_v)); }

        FailNotice_Ref = new System.Collections.Generic.List<Table.CfgLanguage>();
        foreach (var _v in FailNotice) { FailNotice_Ref.Add(tables.TbLanguage.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "rate:" + Rate + ","
        + "drop:" + Luban.StringUtil.CollectionToString(Drop) + ","
        + "successNotice:" + Luban.StringUtil.CollectionToString(SuccessNotice) + ","
        + "failNotice:" + Luban.StringUtil.CollectionToString(FailNotice) + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}

