
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Event
{ 
    public enum Type
    {
        /// <summary>
        /// 普通事件
        /// </summary>
        normal = 1,
        /// <summary>
        /// 奇遇事件
        /// </summary>
        special = 2,
    }

} 

