
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.CampWar
{
public partial class CampWarGiftMain
{
    private readonly System.Collections.Generic.Dictionary<int, CampWar.CfgCampWarGift> _dataMap;
    private readonly System.Collections.Generic.List<CampWar.CfgCampWarGift> _dataList;
    
    public CampWarGiftMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CampWar.CfgCampWarGift>();
        _dataList = new System.Collections.Generic.List<CampWar.CfgCampWarGift>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CampWar.CfgCampWarGift _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CampWar.CfgCampWarGift.DeserializeCfgCampWarGift(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.GiftID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CampWar.CfgCampWarGift> DataMap => _dataMap;
    public System.Collections.Generic.List<CampWar.CfgCampWarGift> DataList => _dataList;

    public CampWar.CfgCampWarGift GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CampWar.CfgCampWarGift Get(int key) => _dataMap[key];
    public CampWar.CfgCampWarGift this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

