
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Dungeon
{
public sealed partial class CfgDungeonRankReward : Luban.BeanBase
{
    public CfgDungeonRankReward(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["dungeon"].IsNumber) { throw new SerializationException(); }  Dungeon = _buf["dungeon"]; }
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["rank"]; }
        { var __json0 = _buf["rewardProp"]; if(!__json0.IsArray) { throw new SerializationException(); } RewardProp = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  RewardProp.Add(__v0); }   }
        { var __json0 = _buf["dropReward"]; if(!__json0.IsArray) { throw new SerializationException(); } DropReward = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DropReward.Add(__v0); }   }
    }

    public static CfgDungeonRankReward DeserializeCfgDungeonRankReward(JSONNode _buf)
    {
        return new Dungeon.CfgDungeonRankReward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 幻境ID
    /// </summary>
    public readonly int Dungeon;
    /// <summary>
    /// 伤害排名
    /// </summary>
    public readonly int Rank;
    /// <summary>
    /// 奖励物品
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> RewardProp;
    /// <summary>
    /// 掉落id
    /// </summary>
    public readonly System.Collections.Generic.List<int> DropReward;
    public System.Collections.Generic.List<Reward.CfgRewardDrop> DropReward_Ref;
   
    public const int __ID__ = -1630321723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in RewardProp) { _e?.ResolveRef(tables); }
        DropReward_Ref = new System.Collections.Generic.List<Reward.CfgRewardDrop>();
        foreach (var _v in DropReward) { DropReward_Ref.Add(tables.TbRewardDrop.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dungeon:" + Dungeon + ","
        + "rank:" + Rank + ","
        + "rewardProp:" + Luban.StringUtil.CollectionToString(RewardProp) + ","
        + "dropReward:" + Luban.StringUtil.CollectionToString(DropReward) + ","
        + "}";
    }
}

}

