
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Dungeon
{
public sealed partial class CfgDungeonMain : Luban.BeanBase
{
    public CfgDungeonMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["dungeonID"].IsNumber) { throw new SerializationException(); }  DungeonID = _buf["dungeonID"]; }
        { if(!_buf["stageID"].IsNumber) { throw new SerializationException(); }  StageID = _buf["stageID"]; }
        { var __json0 = _buf["waveID"]; if(!__json0.IsArray) { throw new SerializationException(); } WaveID = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  WaveID.Add(__v0); }   }
        { if(!_buf["NextDungeon"].IsNumber) { throw new SerializationException(); }  NextDungeon = _buf["NextDungeon"]; }
        { if(!_buf["timeLimit"].IsNumber) { throw new SerializationException(); }  TimeLimit = _buf["timeLimit"]; }
    }

    public static CfgDungeonMain DeserializeCfgDungeonMain(JSONNode _buf)
    {
        return new Dungeon.CfgDungeonMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 层数
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 所属副本
    /// </summary>
    public readonly int DungeonID;
    /// <summary>
    /// 出现的关卡ID
    /// </summary>
    public readonly int StageID;
    /// <summary>
    /// 波次id
    /// </summary>
    public readonly System.Collections.Generic.List<int> WaveID;
    public System.Collections.Generic.List<Dungeon.CfgDungeonWave> WaveID_Ref;
    /// <summary>
    /// 下一关
    /// </summary>
    public readonly int NextDungeon;
    /// <summary>
    /// 限时
    /// </summary>
    public readonly int TimeLimit;
   
    public const int __ID__ = -246295933;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        WaveID_Ref = new System.Collections.Generic.List<Dungeon.CfgDungeonWave>();
        foreach (var _v in WaveID) { WaveID_Ref.Add(tables.TbDungeonWave.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "dungeonID:" + DungeonID + ","
        + "stageID:" + StageID + ","
        + "waveID:" + Luban.StringUtil.CollectionToString(WaveID) + ","
        + "NextDungeon:" + NextDungeon + ","
        + "timeLimit:" + TimeLimit + ","
        + "}";
    }
}

}

