
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Dungeon
{
public sealed partial class CfgDungeonWave : Luban.BeanBase
{
    public CfgDungeonWave(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["wave"].IsNumber) { throw new SerializationException(); }  Wave = _buf["wave"]; }
        { var __json0 = _buf["CreateUnitIdList"]; if(!__json0.IsArray) { throw new SerializationException(); } CreateUnitIdList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CreateUnitIdList.Add(__v0); }   }
        { if(!_buf["CreateUnitIntervalTime"].IsNumber) { throw new SerializationException(); }  CreateUnitIntervalTime = _buf["CreateUnitIntervalTime"]; }
        { if(!_buf["CreateUnitdDrationTime"].IsNumber) { throw new SerializationException(); }  CreateUnitdDrationTime = _buf["CreateUnitdDrationTime"]; }
        { if(!_buf["CreateUnitCamp"].IsNumber) { throw new SerializationException(); }  CreateUnitCamp = _buf["CreateUnitCamp"]; }
        { var _j = _buf["CreateUnitGroup"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  CreateUnitGroup = _j; } } else { CreateUnitGroup = null; } }
        CreateUnitGroup_Ref = null;
        { if(!_buf["CreateUnitNum"].IsNumber) { throw new SerializationException(); }  CreateUnitNum = _buf["CreateUnitNum"]; }
        { if(!_buf["CreateUnitBirthPos"].IsObject) { throw new SerializationException(); }  CreateUnitBirthPos = Math.Vec3.DeserializeVec3(_buf["CreateUnitBirthPos"]);  }
    }

    public static CfgDungeonWave DeserializeCfgDungeonWave(JSONNode _buf)
    {
        return new Dungeon.CfgDungeonWave(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 波次
    /// </summary>
    public readonly int Wave;
    /// <summary>
    /// 单位ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> CreateUnitIdList;
    public System.Collections.Generic.List<Battle.CfgBattleUnitData> CreateUnitIdList_Ref;
    /// <summary>
    /// 每批创建单位间隔时间(毫秒)
    /// </summary>
    public readonly int CreateUnitIntervalTime;
    /// <summary>
    /// 创建单位持续时间(毫秒)
    /// </summary>
    public readonly int CreateUnitdDrationTime;
    /// <summary>
    /// 创建单位所属阵营
    /// </summary>
    public readonly int CreateUnitCamp;
    /// <summary>
    /// 创建单位所属组
    /// </summary>
    public readonly int? CreateUnitGroup;
    public Battle.CfgBattleGroupData CreateUnitGroup_Ref;
    /// <summary>
    /// 每批创建单位数量
    /// </summary>
    public readonly int CreateUnitNum;
    /// <summary>
    /// 出生位置(没有组)
    /// </summary>
    public readonly Math.Vec3 CreateUnitBirthPos;
   
    public const int __ID__ = -245997629;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        CreateUnitIdList_Ref = new System.Collections.Generic.List<Battle.CfgBattleUnitData>();
        foreach (var _v in CreateUnitIdList) { CreateUnitIdList_Ref.Add(tables.TbBattleUnitMain.GetOrDefault(_v)); }

        CreateUnitGroup_Ref = CreateUnitGroup!= null ? tables.TbBattleGroup.GetOrDefault(CreateUnitGroup.Value) : null;
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "wave:" + Wave + ","
        + "CreateUnitIdList:" + Luban.StringUtil.CollectionToString(CreateUnitIdList) + ","
        + "CreateUnitIntervalTime:" + CreateUnitIntervalTime + ","
        + "CreateUnitdDrationTime:" + CreateUnitdDrationTime + ","
        + "CreateUnitCamp:" + CreateUnitCamp + ","
        + "CreateUnitGroup:" + CreateUnitGroup + ","
        + "CreateUnitNum:" + CreateUnitNum + ","
        + "CreateUnitBirthPos:" + CreateUnitBirthPos + ","
        + "}";
    }
}

}

