
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Dungeon
{
public partial class TbDungeonTotal
{
    private readonly System.Collections.Generic.Dictionary<int, Dungeon.CfgDungeonTotal> _dataMap;
    private readonly System.Collections.Generic.List<Dungeon.CfgDungeonTotal> _dataList;
    
    public TbDungeonTotal(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Dungeon.CfgDungeonTotal>();
        _dataList = new System.Collections.Generic.List<Dungeon.CfgDungeonTotal>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Dungeon.CfgDungeonTotal _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Dungeon.CfgDungeonTotal.DeserializeCfgDungeonTotal(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Dungeon.CfgDungeonTotal> DataMap => _dataMap;
    public System.Collections.Generic.List<Dungeon.CfgDungeonTotal> DataList => _dataList;

    public Dungeon.CfgDungeonTotal GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dungeon.CfgDungeonTotal Get(int key) => _dataMap[key];
    public Dungeon.CfgDungeonTotal this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

