
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionFindTargetActionTypeData : Buff.ActionData
{
    public ActionFindTargetActionTypeData(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["foundByActionType"]; if(!__json0.IsArray) { throw new SerializationException(); } FoundByActionType = new System.Collections.Generic.List<Unit.UnitActionType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Unit.UnitActionType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (Unit.UnitActionType)__e0.AsInt; }  FoundByActionType.Add(__v0); }   }
        { var __json0 = _buf["targetByActionType"]; if(!__json0.IsArray) { throw new SerializationException(); } TargetByActionType = new System.Collections.Generic.List<Unit.UnitActionType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Unit.UnitActionType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (Unit.UnitActionType)__e0.AsInt; }  TargetByActionType.Add(__v0); }   }
    }

    public static ActionFindTargetActionTypeData DeserializeActionFindTargetActionTypeData(JSONNode _buf)
    {
        return new Buff.ActionFindTargetActionTypeData(_buf);
    }

    /// <summary>
    /// 只能被查找的单位
    /// </summary>
    public readonly System.Collections.Generic.List<Unit.UnitActionType> FoundByActionType;
    /// <summary>
    /// 只能查找的单位
    /// </summary>
    public readonly System.Collections.Generic.List<Unit.UnitActionType> TargetByActionType;
   
    public const int __ID__ = 1343203061;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "foundByActionType:" + Luban.StringUtil.CollectionToString(FoundByActionType) + ","
        + "targetByActionType:" + Luban.StringUtil.CollectionToString(TargetByActionType) + ","
        + "}";
    }
}

}

