
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionDamageConversionUnitData : Buff.ActionData
{
    public ActionDamageConversionUnitData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["targetDamageType"].IsNumber) { throw new SerializationException(); }  TargetDamageType = (Unit.UnitDamageType)_buf["targetDamageType"].AsInt; }
        { if(!_buf["campType"].IsNumber) { throw new SerializationException(); }  CampType = (Target.TargetCampType)_buf["campType"].AsInt; }
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
    }

    public static ActionDamageConversionUnitData DeserializeActionDamageConversionUnitData(JSONNode _buf)
    {
        return new Buff.ActionDamageConversionUnitData(_buf);
    }

    /// <summary>
    /// 产生或受到伤害类型
    /// </summary>
    public readonly Unit.UnitDamageType TargetDamageType;
    /// <summary>
    /// 阵营类型
    /// </summary>
    public readonly Target.TargetCampType CampType;
    /// <summary>
    /// 万分比
    /// </summary>
    public readonly long PctValue;
    /// <summary>
    /// 固定值
    /// </summary>
    public readonly long FixedValue;
   
    public const int __ID__ = -1639723612;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "targetDamageType:" + TargetDamageType + ","
        + "campType:" + CampType + ","
        + "pctValue:" + PctValue + ","
        + "fixedValue:" + FixedValue + ","
        + "}";
    }
}

}

