
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionPropertyModifierData : Buff.ActionData
{
    public ActionPropertyModifierData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["propertyType"].IsNumber) { throw new SerializationException(); }  PropertyType = (Battle.PropertyType)_buf["propertyType"].AsInt; }
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
    }

    public static ActionPropertyModifierData DeserializeActionPropertyModifierData(JSONNode _buf)
    {
        return new Buff.ActionPropertyModifierData(_buf);
    }

    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly Battle.PropertyType PropertyType;
    /// <summary>
    /// 万分比
    /// </summary>
    public readonly long PctValue;
    /// <summary>
    /// 固定值
    /// </summary>
    public readonly long FixedValue;
   
    public const int __ID__ = -701537433;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "propertyType:" + PropertyType + ","
        + "pctValue:" + PctValue + ","
        + "fixedValue:" + FixedValue + ","
        + "}";
    }
}

}

