
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionUnitLifeStealData : Buff.ActionData
{
    public ActionUnitLifeStealData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["lifeStealValue"].IsNumber) { throw new SerializationException(); }  LifeStealValue = _buf["lifeStealValue"]; }
        { if(!_buf["lifeStealMaxHPLimitValue"].IsNumber) { throw new SerializationException(); }  LifeStealMaxHPLimitValue = _buf["lifeStealMaxHPLimitValue"]; }
    }

    public static ActionUnitLifeStealData DeserializeActionUnitLifeStealData(JSONNode _buf)
    {
        return new Buff.ActionUnitLifeStealData(_buf);
    }

    /// <summary>
    /// 吸血系数(万分比)
    /// </summary>
    public readonly int LifeStealValue;
    /// <summary>
    /// 吸血最大生命上限(万分比)
    /// </summary>
    public readonly int LifeStealMaxHPLimitValue;
   
    public const int __ID__ = 1890615976;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "lifeStealValue:" + LifeStealValue + ","
        + "lifeStealMaxHPLimitValue:" + LifeStealMaxHPLimitValue + ","
        + "}";
    }
}

}

