
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionStateWeakModifierData : Buff.ActionData
{
    public ActionStateWeakModifierData(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["foundByUnitType"]; if(!__json0.IsArray) { throw new SerializationException(); } FoundByUnitType = new System.Collections.Generic.List<Unit.UnitType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Unit.UnitType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (Unit.UnitType)__e0.AsInt; }  FoundByUnitType.Add(__v0); }   }
        { var __json0 = _buf["targetByUnitType"]; if(!__json0.IsArray) { throw new SerializationException(); } TargetByUnitType = new System.Collections.Generic.List<Unit.UnitType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Unit.UnitType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (Unit.UnitType)__e0.AsInt; }  TargetByUnitType.Add(__v0); }   }
    }

    public static ActionStateWeakModifierData DeserializeActionStateWeakModifierData(JSONNode _buf)
    {
        return new Buff.ActionStateWeakModifierData(_buf);
    }

    /// <summary>
    /// 只能被查找的单位
    /// </summary>
    public readonly System.Collections.Generic.List<Unit.UnitType> FoundByUnitType;
    /// <summary>
    /// 只能查找的单位
    /// </summary>
    public readonly System.Collections.Generic.List<Unit.UnitType> TargetByUnitType;
   
    public const int __ID__ = 1341062585;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "foundByUnitType:" + Luban.StringUtil.CollectionToString(FoundByUnitType) + ","
        + "targetByUnitType:" + Luban.StringUtil.CollectionToString(TargetByUnitType) + ","
        + "}";
    }
}

}

