
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Buff
{ 
    public enum BuffEventType
    {
        /// <summary>
        /// 当添加时
        /// </summary>
        OnAdd = 0,
        /// <summary>
        /// 当叠加时
        /// </summary>
        OnOverlay = 1,
        /// <summary>
        /// 当生效时
        /// </summary>
        OnActivate = 3,
        /// <summary>
        /// 当删除时
        /// </summary>
        OnDelete = 4,
    }

} 

