
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class BuffFxData : Luban.BeanBase
{
    public BuffFxData(JSONNode _buf) 
    {
        { if(!_buf["fxId"].IsNumber) { throw new SerializationException(); }  FxId = _buf["fxId"]; }
        { if(!_buf["isWorldPos"].IsBoolean) { throw new SerializationException(); }  IsWorldPos = _buf["isWorldPos"]; }
        { if(!_buf["bodyParts"].IsNumber) { throw new SerializationException(); }  BodyParts = (Unit.UnitBodyParts)_buf["bodyParts"].AsInt; }
    }

    public static BuffFxData DeserializeBuffFxData(JSONNode _buf)
    {
        return new Buff.BuffFxData(_buf);
    }

    /// <summary>
    /// 特效ID
    /// </summary>
    public readonly int FxId;
    /// <summary>
    /// 是否显示在世界坐标上
    /// </summary>
    public readonly bool IsWorldPos;
    /// <summary>
    /// 显示在目标身体部位
    /// </summary>
    public readonly Unit.UnitBodyParts BodyParts;
   
    public const int __ID__ = -220517814;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "fxId:" + FxId + ","
        + "isWorldPos:" + IsWorldPos + ","
        + "bodyParts:" + BodyParts + ","
        + "}";
    }
}

}

