
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class CondDurationTimeData : Battle.ConditionData
{
    public CondDurationTimeData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["durationTime"].IsNumber) { throw new SerializationException(); }  DurationTime = _buf["durationTime"]; }
    }

    public static CondDurationTimeData DeserializeCondDurationTimeData(JSONNode _buf)
    {
        return new Buff.CondDurationTimeData(_buf);
    }

    /// <summary>
    /// 持续时间(ms)  =-1 无限时间
    /// </summary>
    public readonly int DurationTime;
   
    public const int __ID__ = 452179912;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "durationTime:" + DurationTime + ","
        + "}";
    }
}

}

