
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class CondUnitEventTypeData : Battle.ConditionData
{
    public CondUnitEventTypeData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["targetSource"].IsNumber) { throw new SerializationException(); }  TargetSource = (Target.TargetAttackType)_buf["targetSource"].AsInt; }
        { if(!_buf["unitEventType"].IsNumber) { throw new SerializationException(); }  UnitEventType = (Unit.UnitEventType)_buf["unitEventType"].AsInt; }
    }

    public static CondUnitEventTypeData DeserializeCondUnitEventTypeData(JSONNode _buf)
    {
        return new Buff.CondUnitEventTypeData(_buf);
    }

    /// <summary>
    /// 目标来源
    /// </summary>
    public readonly Target.TargetAttackType TargetSource;
    /// <summary>
    /// 单位事件类型
    /// </summary>
    public readonly Unit.UnitEventType UnitEventType;
   
    public const int __ID__ = 1778269501;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "unitEventType:" + UnitEventType + ","
        + "}";
    }
}

}

