
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class CondBuffEventData : Battle.ConditionData
{
    public CondBuffEventData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["buffEventType"].IsNumber) { throw new SerializationException(); }  BuffEventType = (Buff.BuffEventType)_buf["buffEventType"].AsInt; }
    }

    public static CondBuffEventData DeserializeCondBuffEventData(JSONNode _buf)
    {
        return new Buff.CondBuffEventData(_buf);
    }

    /// <summary>
    /// BUFF事件
    /// </summary>
    public readonly Buff.BuffEventType BuffEventType;
   
    public const int __ID__ = -465916556;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "buffEventType:" + BuffEventType + ","
        + "}";
    }
}

}

