
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Buff
{ 
    public enum OverlayType
    {
        /// <summary>
        /// 替换
        /// </summary>
        Replace = 0,
        /// <summary>
        /// 属性值大的生效
        /// </summary>
        MaxProperty = 1,
        /// <summary>
        /// 独立计算
        /// </summary>
        Independent = 2,
        /// <summary>
        /// 时间顺序生效
        /// </summary>
        TimeQueue = 3,
        /// <summary>
        /// 最大等级生效
        /// </summary>
        MaxLevel = 4,
        /// <summary>
        /// 最小等级生效
        /// </summary>
        MinLevel = 5,
    }

} 

