
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Buff
{ 
    public enum SameIdReplaceType
    {
        /// <summary>
        /// 不做处理
        /// </summary>
        None = 0,
        /// <summary>
        /// 替换
        /// </summary>
        Replace = 1,
        /// <summary>
        /// 叠加持续时间
        /// </summary>
        StackDuration = 2,
        /// <summary>
        /// 重置持续时间
        /// </summary>
        ResetDuration = 3,
    }

} 

