
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.GuildCompetition
{
public partial class GuildCompetitionMain
{
    private readonly System.Collections.Generic.Dictionary<int, GuildCompetition.CfgGuildCompetitionMain> _dataMap;
    private readonly System.Collections.Generic.List<GuildCompetition.CfgGuildCompetitionMain> _dataList;
    
    public GuildCompetitionMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuildCompetition.CfgGuildCompetitionMain>();
        _dataList = new System.Collections.Generic.List<GuildCompetition.CfgGuildCompetitionMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GuildCompetition.CfgGuildCompetitionMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = GuildCompetition.CfgGuildCompetitionMain.DeserializeCfgGuildCompetitionMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuildCompetition.CfgGuildCompetitionMain> DataMap => _dataMap;
    public System.Collections.Generic.List<GuildCompetition.CfgGuildCompetitionMain> DataList => _dataList;

    public GuildCompetition.CfgGuildCompetitionMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuildCompetition.CfgGuildCompetitionMain Get(int key) => _dataMap[key];
    public GuildCompetition.CfgGuildCompetitionMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

