
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gift
{ 
    public enum specialRewardType
    {
        /// <summary>
        /// 召唤boss
        /// </summary>
        CallBoss = 1,
        /// <summary>
        /// 释放技能
        /// </summary>
        ReleaseSkill = 2,
        /// <summary>
        /// 释放buff
        /// </summary>
        ReleaseBuff = 3,
    }

} 

