
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.GuildCompetition
{
public sealed partial class CfgGuildCompetitionMain : Luban.BeanBase
{
    public CfgGuildCompetitionMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["nameRich"].IsString) { throw new SerializationException(); }  NameRich = _buf["nameRich"]; }
        { var __json0 = _buf["signDrop"]; if(!__json0.IsArray) { throw new SerializationException(); } SignDrop = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SignDrop.Add(__v0); }   }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static CfgGuildCompetitionMain DeserializeCfgGuildCompetitionMain(JSONNode _buf)
    {
        return new GuildCompetition.CfgGuildCompetitionMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 段位
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 段位
    /// </summary>
    public readonly string NameRich;
    /// <summary>
    /// 签到奖励
    /// </summary>
    public readonly System.Collections.Generic.List<int> SignDrop;
    public System.Collections.Generic.List<Reward.CfgRewardDrop> SignDrop_Ref;
    /// <summary>
    /// 段位图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = 2071282183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SignDrop_Ref = new System.Collections.Generic.List<Reward.CfgRewardDrop>();
        foreach (var _v in SignDrop) { SignDrop_Ref.Add(tables.TbRewardDrop.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "nameRich:" + NameRich + ","
        + "signDrop:" + Luban.StringUtil.CollectionToString(SignDrop) + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}

