
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.GuildCompetition
{
public sealed partial class CfgGuildCompetitionRankReward : Luban.BeanBase
{
    public CfgGuildCompetitionRankReward(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["rank"]; }
        { var __json0 = _buf["reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Reward.Add(__v0); }   }
    }

    public static CfgGuildCompetitionRankReward DeserializeCfgGuildCompetitionRankReward(JSONNode _buf)
    {
        return new GuildCompetition.CfgGuildCompetitionRankReward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 获胜还是失败
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 伤害排名
    /// </summary>
    public readonly int Rank;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Reward;
   
    public const int __ID__ = -585236407;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "rank:" + Rank + ","
        + "reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "}";
    }
}

}

