
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleBuffActionData : Luban.BeanBase
{
    public CfgBattleBuffActionData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["actionType"].IsObject) { throw new SerializationException(); }  ActionType = Buff.ActionData.DeserializeActionData(_buf["actionType"]);  }
    }

    public static CfgBattleBuffActionData DeserializeCfgBattleBuffActionData(JSONNode _buf)
    {
        return new Battle.CfgBattleBuffActionData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// BUFF行为数据
    /// </summary>
    public readonly Buff.ActionData ActionType;
   
    public const int __ID__ = -1616329255;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ActionType?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "actionType:" + ActionType + ","
        + "}";
    }
}

}

