
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleBuffCateData : Luban.BeanBase
{
    public CfgBattleBuffCateData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["isDeBuff"].IsBoolean) { throw new SerializationException(); }  IsDeBuff = _buf["isDeBuff"]; }
        { if(!_buf["overlayType"].IsNumber) { throw new SerializationException(); }  OverlayType = (Buff.OverlayType)_buf["overlayType"].AsInt; }
        { if(!_buf["overlayCount"].IsNumber) { throw new SerializationException(); }  OverlayCount = _buf["overlayCount"]; }
        { if(!_buf["tag"].IsNumber) { throw new SerializationException(); }  Tag = (Buff.BuffTag)_buf["tag"].AsInt; }
    }

    public static CfgBattleBuffCateData DeserializeCfgBattleBuffCateData(JSONNode _buf)
    {
        return new Battle.CfgBattleBuffCateData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 是否DEBuff
    /// </summary>
    public readonly bool IsDeBuff;
    /// <summary>
    /// 叠加类型
    /// </summary>
    public readonly Buff.OverlayType OverlayType;
    /// <summary>
    /// 叠加上限
    /// </summary>
    public readonly int OverlayCount;
    /// <summary>
    /// BUFF类型
    /// </summary>
    public readonly Buff.BuffTag Tag;
   
    public const int __ID__ = -1464766286;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "isDeBuff:" + IsDeBuff + ","
        + "overlayType:" + OverlayType + ","
        + "overlayCount:" + OverlayCount + ","
        + "tag:" + Tag + ","
        + "}";
    }
}

}

