
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleUnitData : Luban.BeanBase
{
    public CfgBattleUnitData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["tubeNum"].IsNumber) { throw new SerializationException(); }  TubeNum = _buf["tubeNum"]; }
        { if(!_buf["unitType"].IsNumber) { throw new SerializationException(); }  UnitType = (Unit.UnitType)_buf["unitType"].AsInt; }
        { if(!_buf["jobType"].IsNumber) { throw new SerializationException(); }  JobType = (Unit.ArmType)_buf["jobType"].AsInt; }
        { if(!_buf["hurtType"].IsNumber) { throw new SerializationException(); }  HurtType = (Unit.HurtType)_buf["hurtType"].AsInt; }
        { if(!_buf["armorType"].IsNumber) { throw new SerializationException(); }  ArmorType = (Unit.ArmorType)_buf["armorType"].AsInt; }
        { if(!_buf["bodyType"].IsNumber) { throw new SerializationException(); }  BodyType = (Unit.BodyType)_buf["bodyType"].AsInt; }
        { if(!_buf["bodySize"].IsNumber) { throw new SerializationException(); }  BodySize = _buf["bodySize"]; }
        { if(!_buf["patrolRange"].IsNumber) { throw new SerializationException(); }  PatrolRange = _buf["patrolRange"]; }
        { if(!_buf["isBattleAbilityEnable"].IsBoolean) { throw new SerializationException(); }  IsBattleAbilityEnable = _buf["isBattleAbilityEnable"]; }
        { if(!_buf["isSkillAbilityEnable"].IsBoolean) { throw new SerializationException(); }  IsSkillAbilityEnable = _buf["isSkillAbilityEnable"]; }
        { if(!_buf["isMoveAbilityEnable"].IsBoolean) { throw new SerializationException(); }  IsMoveAbilityEnable = _buf["isMoveAbilityEnable"]; }
        { if(!_buf["isAIAbilityEnable"].IsBoolean) { throw new SerializationException(); }  IsAIAbilityEnable = _buf["isAIAbilityEnable"]; }
        { if(!_buf["unitModel"].IsString) { throw new SerializationException(); }  UnitModel = _buf["unitModel"]; }
        { if(!_buf["unitModelOffset"].IsObject) { throw new SerializationException(); }  UnitModelOffset = Math.Vec3.DeserializeVec3(_buf["unitModelOffset"]);  }
        { if(!_buf["unitModelData"].IsString) { throw new SerializationException(); }  UnitModelData = _buf["unitModelData"]; }
        { if(!_buf["animation"].IsString) { throw new SerializationException(); }  Animation = _buf["animation"]; }
        { var _j = _buf["skinFxId"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  SkinFxId = _j; } } else { SkinFxId = null; } }
        SkinFxId_Ref = null;
        { var __json0 = _buf["initBuffs"]; if(!__json0.IsArray) { throw new SerializationException(); } InitBuffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  InitBuffs.Add(__v0); }   }
        { var __json0 = _buf["aiBTrees"]; if(!__json0.IsArray) { throw new SerializationException(); } AiBTrees = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  AiBTrees.Add(__v0); }   }
        { var __json0 = _buf["battleSkillList"]; if(!__json0.IsArray) { throw new SerializationException(); } BattleSkillList = new System.Collections.Generic.List<Skill.SkAndSktIdData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Skill.SkAndSktIdData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Skill.SkAndSktIdData.DeserializeSkAndSktIdData(__e0);  }  BattleSkillList.Add(__v0); }   }
        { if(!_buf["overheadDisplayUI"].IsString) { throw new SerializationException(); }  OverheadDisplayUI = _buf["overheadDisplayUI"]; }
        { if(!_buf["durationTime"].IsNumber) { throw new SerializationException(); }  DurationTime = _buf["durationTime"]; }
        { if(!_buf["durationTimeUI"].IsString) { throw new SerializationException(); }  DurationTimeUI = _buf["durationTimeUI"]; }
        { var _j = _buf["bornEffect"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  BornEffect = _j; } } else { BornEffect = null; } }
        BornEffect_Ref = null;
        { if(!_buf["bornTime"].IsNumber) { throw new SerializationException(); }  BornTime = _buf["bornTime"]; }
        { if(!_buf["bornSound"].IsString) { throw new SerializationException(); }  BornSound = _buf["bornSound"]; }
        { var _j = _buf["deadEffect"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  DeadEffect = _j; } } else { DeadEffect = null; } }
        DeadEffect_Ref = null;
        { if(!_buf["deadSound"].IsString) { throw new SerializationException(); }  DeadSound = _buf["deadSound"]; }
        { if(!_buf["deadTime"].IsNumber) { throw new SerializationException(); }  DeadTime = _buf["deadTime"]; }
        { if(!_buf["isDeathFly"].IsBoolean) { throw new SerializationException(); }  IsDeathFly = _buf["isDeathFly"]; }
        { if(!_buf["isDeathDispose"].IsBoolean) { throw new SerializationException(); }  IsDeathDispose = _buf["isDeathDispose"]; }
        { if(!_buf["damageLimit"].IsNumber) { throw new SerializationException(); }  DamageLimit = _buf["damageLimit"]; }
        { var __json0 = _buf["battleAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } BattleAttrValue = new System.Collections.Generic.Dictionary<int, long>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } long _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  BattleAttrValue.Add(_k0, _v0); }   }
    }

    public static CfgBattleUnitData DeserializeCfgBattleUnitData(JSONNode _buf)
    {
        return new Battle.CfgBattleUnitData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 管数
    /// </summary>
    public readonly int TubeNum;
    /// <summary>
    /// 单位类型<br/>
    /// </summary>
    public readonly Unit.UnitType UnitType;
    /// <summary>
    /// 兵种<br/>1：坦克<br/>2：战士<br/>3：游侠<br/>4：辅助
    /// </summary>
    public readonly Unit.ArmType JobType;
    /// <summary>
    /// 伤害类型<br/>1-均衡，2-劲力，3-自然，4-秘术
    /// </summary>
    public readonly Unit.HurtType HurtType;
    /// <summary>
    /// 甲胄类型<br/>1-均衡，2-裸形，3-畸刺，4-邪诡
    /// </summary>
    public readonly Unit.ArmorType ArmorType;
    /// <summary>
    /// 体型类型
    /// </summary>
    public readonly Unit.BodyType BodyType;
    /// <summary>
    /// 体型大小(厘米)
    /// </summary>
    public readonly int BodySize;
    /// <summary>
    /// 巡逻范围(厘米)
    /// </summary>
    public readonly int PatrolRange;
    /// <summary>
    /// 战斗功能
    /// </summary>
    public readonly bool IsBattleAbilityEnable;
    /// <summary>
    /// 技能功能
    /// </summary>
    public readonly bool IsSkillAbilityEnable;
    /// <summary>
    /// 移动功能
    /// </summary>
    public readonly bool IsMoveAbilityEnable;
    /// <summary>
    /// AI功能
    /// </summary>
    public readonly bool IsAIAbilityEnable;
    /// <summary>
    /// 单位模型
    /// </summary>
    public readonly string UnitModel;
    /// <summary>
    /// 单位模型偏移量
    /// </summary>
    public readonly Math.Vec3 UnitModelOffset;
    /// <summary>
    /// 单位模型数据
    /// </summary>
    public readonly string UnitModelData;
    /// <summary>
    /// 单位动画
    /// </summary>
    public readonly string Animation;
    /// <summary>
    /// 皮肤特效
    /// </summary>
    public readonly int? SkinFxId;
    public Battle.CfgBattleFxData SkinFxId_Ref;
    /// <summary>
    /// 初始释放BUFF
    /// </summary>
    public readonly System.Collections.Generic.List<int> InitBuffs;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> InitBuffs_Ref;
    /// <summary>
    /// AI行为树
    /// </summary>
    public readonly System.Collections.Generic.List<string> AiBTrees;
    /// <summary>
    /// 战斗技能
    /// </summary>
    public readonly System.Collections.Generic.List<Skill.SkAndSktIdData> BattleSkillList;
    /// <summary>
    /// 头顶上方UI皮肤
    /// </summary>
    public readonly string OverheadDisplayUI;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly int DurationTime;
    /// <summary>
    /// 持续时间UI皮肤
    /// </summary>
    public readonly string DurationTimeUI;
    /// <summary>
    /// 出生特效(默认为空)
    /// </summary>
    public readonly int? BornEffect;
    public Battle.CfgBattleFxData BornEffect_Ref;
    /// <summary>
    /// 出生时间(毫秒)
    /// </summary>
    public readonly int BornTime;
    /// <summary>
    /// 出生音效
    /// </summary>
    public readonly string BornSound;
    /// <summary>
    /// 死亡特效(默认为空)
    /// </summary>
    public readonly int? DeadEffect;
    public Battle.CfgBattleFxData DeadEffect_Ref;
    /// <summary>
    /// 死亡音效
    /// </summary>
    public readonly string DeadSound;
    /// <summary>
    /// 死亡时间(毫秒)
    /// </summary>
    public readonly int DeadTime;
    /// <summary>
    /// 是否死亡击飞
    /// </summary>
    public readonly bool IsDeathFly;
    /// <summary>
    /// 是否死亡后就销毁
    /// </summary>
    public readonly bool IsDeathDispose;
    /// <summary>
    /// 伤害上限
    /// </summary>
    public readonly long DamageLimit;
    /// <summary>
    /// 战斗属性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, long> BattleAttrValue;
   
    public const int __ID__ = 553303540;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SkinFxId_Ref = SkinFxId!= null ? tables.TbBattleFx.GetOrDefault(SkinFxId.Value) : null;
        InitBuffs_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in InitBuffs) { InitBuffs_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

        foreach (var _e in BattleSkillList) { _e?.ResolveRef(tables); }
        BornEffect_Ref = BornEffect!= null ? tables.TbBattleFx.GetOrDefault(BornEffect.Value) : null;
        DeadEffect_Ref = DeadEffect!= null ? tables.TbBattleFx.GetOrDefault(DeadEffect.Value) : null;
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "tubeNum:" + TubeNum + ","
        + "unitType:" + UnitType + ","
        + "jobType:" + JobType + ","
        + "hurtType:" + HurtType + ","
        + "armorType:" + ArmorType + ","
        + "bodyType:" + BodyType + ","
        + "bodySize:" + BodySize + ","
        + "patrolRange:" + PatrolRange + ","
        + "isBattleAbilityEnable:" + IsBattleAbilityEnable + ","
        + "isSkillAbilityEnable:" + IsSkillAbilityEnable + ","
        + "isMoveAbilityEnable:" + IsMoveAbilityEnable + ","
        + "isAIAbilityEnable:" + IsAIAbilityEnable + ","
        + "unitModel:" + UnitModel + ","
        + "unitModelOffset:" + UnitModelOffset + ","
        + "unitModelData:" + UnitModelData + ","
        + "animation:" + Animation + ","
        + "skinFxId:" + SkinFxId + ","
        + "initBuffs:" + Luban.StringUtil.CollectionToString(InitBuffs) + ","
        + "aiBTrees:" + Luban.StringUtil.CollectionToString(AiBTrees) + ","
        + "battleSkillList:" + Luban.StringUtil.CollectionToString(BattleSkillList) + ","
        + "overheadDisplayUI:" + OverheadDisplayUI + ","
        + "durationTime:" + DurationTime + ","
        + "durationTimeUI:" + DurationTimeUI + ","
        + "bornEffect:" + BornEffect + ","
        + "bornTime:" + BornTime + ","
        + "bornSound:" + BornSound + ","
        + "deadEffect:" + DeadEffect + ","
        + "deadSound:" + DeadSound + ","
        + "deadTime:" + DeadTime + ","
        + "isDeathFly:" + IsDeathFly + ","
        + "isDeathDispose:" + IsDeathDispose + ","
        + "damageLimit:" + DamageLimit + ","
        + "battleAttrValue:" + Luban.StringUtil.CollectionToString(BattleAttrValue) + ","
        + "}";
    }
}

}

