
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleGroupData : Luban.BeanBase
{
    public CfgBattleGroupData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["campId"].IsNumber) { throw new SerializationException(); }  CampId = _buf["campId"]; }
        { if(!_buf["groupType"].IsNumber) { throw new SerializationException(); }  GroupType = (Battle.GroupType)_buf["groupType"].AsInt; }
        { if(!_buf["battleEnterType"].IsNumber) { throw new SerializationException(); }  BattleEnterType = (Battle.GroupBattleEntryType)_buf["battleEnterType"].AsInt; }
        { if(!_buf["memberMaxCount"].IsNumber) { throw new SerializationException(); }  MemberMaxCount = _buf["memberMaxCount"]; }
        { var __json0 = _buf["initCreateUnitId"]; if(!__json0.IsArray) { throw new SerializationException(); } InitCreateUnitId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  InitCreateUnitId.Add(__v0); }   }
        { if(!_buf["birthPos"].IsObject) { throw new SerializationException(); }  BirthPos = Math.Vec3.DeserializeVec3(_buf["birthPos"]);  }
        { if(!_buf["birthRot"].IsNumber) { throw new SerializationException(); }  BirthRot = _buf["birthRot"]; }
        { var _j = _buf["formationId"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  FormationId = _j; } } else { FormationId = null; } }
        FormationId_Ref = null;
        { if(!_buf["memberBirthPos"].IsObject) { throw new SerializationException(); }  MemberBirthPos = BattleGroup.MemberBirthPos.DeserializeMemberBirthPos(_buf["memberBirthPos"]);  }
        { if(!_buf["memberBirthRot"].IsObject) { throw new SerializationException(); }  MemberBirthRot = BattleGroup.MemberBirthRot.DeserializeMemberBirthRot(_buf["memberBirthRot"]);  }
        { var __json0 = _buf["initBuffs"]; if(!__json0.IsArray) { throw new SerializationException(); } InitBuffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  InitBuffs.Add(__v0); }   }
        { var __json0 = _buf["aiBTrees"]; if(!__json0.IsArray) { throw new SerializationException(); } AiBTrees = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  AiBTrees.Add(__v0); }   }
        { var __json0 = _buf["captainBTrees"]; if(!__json0.IsArray) { throw new SerializationException(); } CaptainBTrees = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  CaptainBTrees.Add(__v0); }   }
        { var __json0 = _buf["memberBTrees"]; if(!__json0.IsArray) { throw new SerializationException(); } MemberBTrees = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  MemberBTrees.Add(__v0); }   }
    }

    public static CfgBattleGroupData DeserializeCfgBattleGroupData(JSONNode _buf)
    {
        return new Battle.CfgBattleGroupData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 所属阵营
    /// </summary>
    public readonly int CampId;
    /// <summary>
    /// 组类型
    /// </summary>
    public readonly Battle.GroupType GroupType;
    /// <summary>
    /// 进入战斗类型
    /// </summary>
    public readonly Battle.GroupBattleEntryType BattleEnterType;
    /// <summary>
    /// 成员上限数量
    /// </summary>
    public readonly int MemberMaxCount;
    /// <summary>
    /// 初始化创建单位
    /// </summary>
    public readonly System.Collections.Generic.List<int> InitCreateUnitId;
    public System.Collections.Generic.List<Battle.CfgBattleUnitData> InitCreateUnitId_Ref;
    /// <summary>
    /// 战斗组出生位置
    /// </summary>
    public readonly Math.Vec3 BirthPos;
    /// <summary>
    /// 战斗组出生角度
    /// </summary>
    public readonly int BirthRot;
    /// <summary>
    /// 阵型ID
    /// </summary>
    public readonly int? FormationId;
    public Battle.CfgBattleFormationData FormationId_Ref;
    /// <summary>
    /// 成员出生位置类型
    /// </summary>
    public readonly BattleGroup.MemberBirthPos MemberBirthPos;
    /// <summary>
    /// 成员出生方向类型
    /// </summary>
    public readonly BattleGroup.MemberBirthRot MemberBirthRot;
    /// <summary>
    /// 初始释放BUFF
    /// </summary>
    public readonly System.Collections.Generic.List<int> InitBuffs;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> InitBuffs_Ref;
    /// <summary>
    /// AI行为树
    /// </summary>
    public readonly System.Collections.Generic.List<string> AiBTrees;
    /// <summary>
    /// 队长行为树
    /// </summary>
    public readonly System.Collections.Generic.List<string> CaptainBTrees;
    /// <summary>
    /// 成员行为树
    /// </summary>
    public readonly System.Collections.Generic.List<string> MemberBTrees;
   
    public const int __ID__ = -1013156637;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitCreateUnitId_Ref = new System.Collections.Generic.List<Battle.CfgBattleUnitData>();
        foreach (var _v in InitCreateUnitId) { InitCreateUnitId_Ref.Add(tables.TbBattleUnitMain.GetOrDefault(_v)); }

        FormationId_Ref = FormationId!= null ? tables.TbBattleFormation.GetOrDefault(FormationId.Value) : null;
        MemberBirthPos?.ResolveRef(tables);
        MemberBirthRot?.ResolveRef(tables);
        InitBuffs_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in InitBuffs) { InitBuffs_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "campId:" + CampId + ","
        + "groupType:" + GroupType + ","
        + "battleEnterType:" + BattleEnterType + ","
        + "memberMaxCount:" + MemberMaxCount + ","
        + "initCreateUnitId:" + Luban.StringUtil.CollectionToString(InitCreateUnitId) + ","
        + "birthPos:" + BirthPos + ","
        + "birthRot:" + BirthRot + ","
        + "formationId:" + FormationId + ","
        + "memberBirthPos:" + MemberBirthPos + ","
        + "memberBirthRot:" + MemberBirthRot + ","
        + "initBuffs:" + Luban.StringUtil.CollectionToString(InitBuffs) + ","
        + "aiBTrees:" + Luban.StringUtil.CollectionToString(AiBTrees) + ","
        + "captainBTrees:" + Luban.StringUtil.CollectionToString(CaptainBTrees) + ","
        + "memberBTrees:" + Luban.StringUtil.CollectionToString(MemberBTrees) + ","
        + "}";
    }
}

}

