
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleSkillTriggerData : Luban.BeanBase
{
    public CfgBattleSkillTriggerData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["triggerType"].IsObject) { throw new SerializationException(); }  TriggerType = Battle.ConditionData.DeserializeConditionData(_buf["triggerType"]);  }
    }

    public static CfgBattleSkillTriggerData DeserializeCfgBattleSkillTriggerData(JSONNode _buf)
    {
        return new Battle.CfgBattleSkillTriggerData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能触发条件
    /// </summary>
    public readonly Battle.ConditionData TriggerType;
   
    public const int __ID__ = 1040837399;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TriggerType?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "triggerType:" + TriggerType + ","
        + "}";
    }
}

}

