
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfgBattleAttribute : Luban.BeanBase
{
    public CfgBattleAttribute(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["propertyType"].IsNumber) { throw new SerializationException(); }  PropertyType = (Battle.PropertyType)_buf["propertyType"].AsInt; }
        { if(!_buf["name_lid"].IsNumber) { throw new SerializationException(); }  NameLid = _buf["name_lid"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["isBase"].IsBoolean) { throw new SerializationException(); }  IsBase = _buf["isBase"]; }
        { if(!_buf["showType"].IsNumber) { throw new SerializationException(); }  ShowType = _buf["showType"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["battleIcon"].IsString) { throw new SerializationException(); }  BattleIcon = _buf["battleIcon"]; }
    }

    public static CfgBattleAttribute DeserializeCfgBattleAttribute(JSONNode _buf)
    {
        return new Battle.CfgBattleAttribute(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Battle.PropertyType PropertyType;
    /// <summary>
    /// 语言包ID
    /// </summary>
    public readonly int NameLid;
    /// <summary>
    /// 属性分类
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 是否基础属性
    /// </summary>
    public readonly bool IsBase;
    /// <summary>
    /// 展示类型
    /// </summary>
    public readonly int ShowType;
    /// <summary>
    /// 属性图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 战斗属性图标
    /// </summary>
    public readonly string BattleIcon;
   
    public const int __ID__ = 483400886;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "propertyType:" + PropertyType + ","
        + "nameLid:" + NameLid + ","
        + "type:" + Type + ","
        + "isBase:" + IsBase + ","
        + "showType:" + ShowType + ","
        + "icon:" + Icon + ","
        + "battleIcon:" + BattleIcon + ","
        + "}";
    }
}

}

