
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    [System.Flags]
    public enum EntityType
    {
        /// <summary>
        /// 单位
        /// </summary>
        Unit = 1,
        /// <summary>
        /// 技能
        /// </summary>
        Skill = 2,
        /// <summary>
        /// BUFF
        /// </summary>
        Buff = 3,
        /// <summary>
        /// 组
        /// </summary>
        Group = 4,
        /// <summary>
        /// 全选
        /// </summary>
        All = Unit|Skill|Buff|Group,
    }

} 

