
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    public enum GroupType
    {
        /// <summary>
        /// 无类型
        /// </summary>
        None = 0,
        /// <summary>
        /// 宗门组
        /// </summary>
        Guild = 1,
        /// <summary>
        /// 入侵组
        /// </summary>
        Invade = 2,
        /// <summary>
        /// 怪物组
        /// </summary>
        Monster = 3,
        /// <summary>
        /// Boss组
        /// </summary>
        Boss = 4,
        /// <summary>
        /// 阵法组
        /// </summary>
        MagicCircle = 5,
        /// <summary>
        /// 红
        /// </summary>
        Red = 6,
        /// <summary>
        /// 蓝
        /// </summary>
        Blue = 7,
    }

} 

