
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    public enum HealType
    {
        /// <summary>
        /// 攻击力治疗
        /// </summary>
        Atk = 0,
        /// <summary>
        /// 最大血量治疗
        /// </summary>
        MaxHp = 1,
    }

} 

