
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    [System.Flags]
    public enum PropertyType
    {
        /// <summary>
        /// $攻击
        /// </summary>
        AtkPhy = 1,
        /// <summary>
        /// $防御
        /// </summary>
        DefPhy = 2,
        /// <summary>
        /// $生命
        /// </summary>
        Hp = 3,
        /// <summary>
        /// $最大生命
        /// </summary>
        MaxHp = 4,
        /// <summary>
        /// $暴击率
        /// </summary>
        Critr = 5,
        /// <summary>
        /// $抗暴率
        /// </summary>
        CritrRes = 6,
        /// <summary>
        /// $暴击伤害
        /// </summary>
        CritHurt = 7,
        /// <summary>
        /// $增伤率
        /// </summary>
        AugInjury = 8,
        /// <summary>
        /// $免伤率
        /// </summary>
        DeInjury = 9,
        /// <summary>
        /// $风属性伤害
        /// </summary>
        WindInjury = 10,
        /// <summary>
        /// $土属性伤害
        /// </summary>
        EarthInjury = 11,
        /// <summary>
        /// $水属性伤害
        /// </summary>
        WaterInjury = 12,
        /// <summary>
        /// $火属性伤害
        /// </summary>
        FireInjury = 13,
        /// <summary>
        /// $风属性伤害减免
        /// </summary>
        DeInjuryWind = 14,
        /// <summary>
        /// $土属性伤害减免
        /// </summary>
        DeInjuryEarth = 15,
        /// <summary>
        /// $水属性伤害减免
        /// </summary>
        DeInjuryWater = 16,
        /// <summary>
        /// $火属性伤害减免
        /// </summary>
        DeInjuryFire = 17,
        /// <summary>
        /// $蓄力伤害加成
        /// </summary>
        StateAccInjury = 18,
        /// <summary>
        /// $虚弱伤害加成
        /// </summary>
        StateWeakInjury = 19,
        /// <summary>
        /// $BUFF伤害加成
        /// </summary>
        BuffInjury = 20,
        /// <summary>
        /// $控制BUFF抵抗
        /// </summary>
        ResistCtrlDebuff = 21,
        /// <summary>
        /// $控制BUFF减免
        /// </summary>
        DeCtrlDebuff = 22,
        /// <summary>
        /// $移速
        /// </summary>
        Speed = 23,
        /// <summary>
        /// $攻速
        /// </summary>
        AtkSpeed = 24,
        /// <summary>
        /// $治疗加成
        /// </summary>
        AugHeal = 25,
        /// <summary>
        /// $被治疗加成
        /// </summary>
        AugBeHeal = 26,
        /// <summary>
        /// $减疗率
        /// </summary>
        DeHealRate = 27,
        /// <summary>
        /// $修炼经验值
        /// </summary>
        Exp = 28,
        /// <summary>
        /// $修炼经验效率
        /// </summary>
        ExpSpeed = 29,
        /// <summary>
        /// $突破成功率，万分值
        /// </summary>
        BreakRate = 30,
        /// <summary>
        /// 洞察力
        /// </summary>
        Insight = 31,
        /// <summary>
        /// 护盾
        /// </summary>
        Shield = 32,
        /// <summary>
        /// 最大护盾
        /// </summary>
        MaxShield = 33,
        /// <summary>
        /// 吸血加成
        /// </summary>
        AugLifeSteal = 34,
        /// <summary>
        /// 吸血减免
        /// </summary>
        DeLifeSteal = 35,
        /// <summary>
        /// 吸血减益
        /// </summary>
        RedLifeSteal = 36,
    }

} 

