
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TbBuffCate
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffCateData> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfgBattleBuffCateData> _dataList;
    
    public TbBuffCate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffCateData>();
        _dataList = new System.Collections.Generic.List<Battle.CfgBattleBuffCateData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.CfgBattleBuffCateData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Battle.CfgBattleBuffCateData.DeserializeCfgBattleBuffCateData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffCateData> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfgBattleBuffCateData> DataList => _dataList;

    public Battle.CfgBattleBuffCateData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfgBattleBuffCateData Get(int key) => _dataMap[key];
    public Battle.CfgBattleBuffCateData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

