
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TbBuffMain
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffData> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfgBattleBuffData> _dataList;
    
    public TbBuffMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffData>();
        _dataList = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.CfgBattleBuffData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Battle.CfgBattleBuffData.DeserializeCfgBattleBuffData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffData> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> DataList => _dataList;

    public Battle.CfgBattleBuffData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfgBattleBuffData Get(int key) => _dataMap[key];
    public Battle.CfgBattleBuffData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

