
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TbBuffAction
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffActionData> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfgBattleBuffActionData> _dataList;
    
    public TbBuffAction(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffActionData>();
        _dataList = new System.Collections.Generic.List<Battle.CfgBattleBuffActionData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.CfgBattleBuffActionData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Battle.CfgBattleBuffActionData.DeserializeCfgBattleBuffActionData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfgBattleBuffActionData> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfgBattleBuffActionData> DataList => _dataList;

    public Battle.CfgBattleBuffActionData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfgBattleBuffActionData Get(int key) => _dataMap[key];
    public Battle.CfgBattleBuffActionData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

