
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Trial
{
public sealed partial class CfgTrialTotal : Luban.BeanBase
{
    public CfgTrialTotal(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["TrialNum"].IsNumber) { throw new SerializationException(); }  TrialNum = _buf["TrialNum"]; }
        { if(!_buf["countdown"].IsNumber) { throw new SerializationException(); }  Countdown = _buf["countdown"]; }
    }

    public static CfgTrialTotal DeserializeCfgTrialTotal(JSONNode _buf)
    {
        return new Trial.CfgTrialTotal(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 关卡数量
    /// </summary>
    public readonly int TrialNum;
    /// <summary>
    /// 倒计时
    /// </summary>
    public readonly int Countdown;
   
    public const int __ID__ = 144387130;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "TrialNum:" + TrialNum + ","
        + "countdown:" + Countdown + ","
        + "}";
    }
}

}

