
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Insight
{
public partial class TbInsightMain
{
    private readonly System.Collections.Generic.Dictionary<int, Insight.CfgInsightMain> _dataMap;
    private readonly System.Collections.Generic.List<Insight.CfgInsightMain> _dataList;
    
    public TbInsightMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Insight.CfgInsightMain>();
        _dataList = new System.Collections.Generic.List<Insight.CfgInsightMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Insight.CfgInsightMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Insight.CfgInsightMain.DeserializeCfgInsightMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Insight.CfgInsightMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Insight.CfgInsightMain> DataList => _dataList;

    public Insight.CfgInsightMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Insight.CfgInsightMain Get(int key) => _dataMap[key];
    public Insight.CfgInsightMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

