
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CfgSkillSuit : Luban.BeanBase
{
    public CfgSkillSuit(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { var __json0 = _buf["specialEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialEffect = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialEffect.Add(__v0); }   }
    }

    public static CfgSkillSuit DeserializeCfgSkillSuit(JSONNode _buf)
    {
        return new Skill.CfgSkillSuit(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 增加属性类型
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialEffect;
   
    public const int __ID__ = -1827142217;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SpecialEffect) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Level + ","
        + "specialEffect:" + Luban.StringUtil.CollectionToString(SpecialEffect) + ","
        + "}";
    }
}

}

