
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CfgSkillMain : Luban.BeanBase
{
    public CfgSkillMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["group"].IsNumber) { throw new SerializationException(); }  Group = _buf["group"]; }
        { var __json0 = _buf["decompose"]; if(!__json0.IsArray) { throw new SerializationException(); } Decompose = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Decompose.Add(__v0); }   }
        { if(!_buf["skillType"].IsNumber) { throw new SerializationException(); }  SkillType = (Skill.SkillDisplayType)_buf["skillType"].AsInt; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Item.Quality)_buf["quality"].AsInt; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { var __json0 = _buf["specialEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialEffect = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialEffect.Add(__v0); }   }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["cd"].IsNumber) { throw new SerializationException(); }  Cd = _buf["cd"]; }
        { var _j = _buf["buff"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  Buff = _j; } } else { Buff = null; } }
        Buff_Ref = null;
        { var __json0 = _buf["battleSkill"]; if(!__json0.IsArray) { throw new SerializationException(); } BattleSkill = new System.Collections.Generic.List<Skill.SkAndSktIdData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Skill.SkAndSktIdData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Skill.SkAndSktIdData.DeserializeSkAndSktIdData(__e0);  }  BattleSkill.Add(__v0); }   }
        { var __json0 = _buf["passivityBattleSkill"]; if(!__json0.IsArray) { throw new SerializationException(); } PassivityBattleSkill = new System.Collections.Generic.List<Skill.SkAndSktIdData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Skill.SkAndSktIdData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Skill.SkAndSktIdData.DeserializeSkAndSktIdData(__e0);  }  PassivityBattleSkill.Add(__v0); }   }
        { if(!_buf["AddFight"].IsNumber) { throw new SerializationException(); }  AddFight = _buf["AddFight"]; }
    }

    public static CfgSkillMain DeserializeCfgSkillMain(JSONNode _buf)
    {
        return new Skill.CfgSkillMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能效果
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 技能组
    /// </summary>
    public readonly int Group;
    /// <summary>
    /// 分解奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Decompose;
    /// <summary>
    /// 技能类别
    /// </summary>
    public readonly Skill.SkillDisplayType SkillType;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Item.Quality Quality;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 增加属性类型
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialEffect;
    /// <summary>
    /// 技能图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 技能CD<br/>(单位ms)
    /// </summary>
    public readonly int Cd;
    /// <summary>
    /// 效果id
    /// </summary>
    public readonly int? Buff;
    public Battle.CfgBattleBuffData Buff_Ref;
    /// <summary>
    /// 主动技能
    /// </summary>
    public readonly System.Collections.Generic.List<Skill.SkAndSktIdData> BattleSkill;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly System.Collections.Generic.List<Skill.SkAndSktIdData> PassivityBattleSkill;
    /// <summary>
    /// 技能升级提升战力
    /// </summary>
    public readonly int AddFight;
   
    public const int __ID__ = -1827340189;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Decompose) { _e?.ResolveRef(tables); }
        foreach (var _e in SpecialEffect) { _e?.ResolveRef(tables); }
        Buff_Ref = Buff!= null ? tables.TbBuffMain.GetOrDefault(Buff.Value) : null;
        foreach (var _e in BattleSkill) { _e?.ResolveRef(tables); }
        foreach (var _e in PassivityBattleSkill) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "group:" + Group + ","
        + "decompose:" + Luban.StringUtil.CollectionToString(Decompose) + ","
        + "skillType:" + SkillType + ","
        + "quality:" + Quality + ","
        + "level:" + Level + ","
        + "specialEffect:" + Luban.StringUtil.CollectionToString(SpecialEffect) + ","
        + "icon:" + Icon + ","
        + "cd:" + Cd + ","
        + "buff:" + Buff + ","
        + "battleSkill:" + Luban.StringUtil.CollectionToString(BattleSkill) + ","
        + "passivityBattleSkill:" + Luban.StringUtil.CollectionToString(PassivityBattleSkill) + ","
        + "AddFight:" + AddFight + ","
        + "}";
    }
}

}

