
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondUnitDeathData : Battle.ConditionData
{
    public CondUnitDeathData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["targetType"].IsNumber) { throw new SerializationException(); }  TargetType = (Target.TargetType)_buf["targetType"].AsInt; }
    }

    public static CondUnitDeathData DeserializeCondUnitDeathData(JSONNode _buf)
    {
        return new Skill.CondUnitDeathData(_buf);
    }

    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly Target.TargetType TargetType;
   
    public const int __ID__ = 2058023035;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetType:" + TargetType + ","
        + "}";
    }
}

}

