
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondUnitNoMainTargetData : Battle.ConditionData
{
    public CondUnitNoMainTargetData(JSONNode _buf)  : base(_buf) 
    {
    }

    public static CondUnitNoMainTargetData DeserializeCondUnitNoMainTargetData(JSONNode _buf)
    {
        return new Skill.CondUnitNoMainTargetData(_buf);
    }

   
    public const int __ID__ = -60193608;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

