
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondUnitGroupTypeData : Battle.ConditionData
{
    public CondUnitGroupTypeData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["unitGroupType"].IsNumber) { throw new SerializationException(); }  UnitGroupType = (Battle.GroupType)_buf["unitGroupType"].AsInt; }
        { if(!_buf["invert"].IsBoolean) { throw new SerializationException(); }  Invert = _buf["invert"]; }
    }

    public static CondUnitGroupTypeData DeserializeCondUnitGroupTypeData(JSONNode _buf)
    {
        return new Skill.CondUnitGroupTypeData(_buf);
    }

    /// <summary>
    /// 单位战斗组类型
    /// </summary>
    public readonly Battle.GroupType UnitGroupType;
    /// <summary>
    /// 取返
    /// </summary>
    public readonly bool Invert;
   
    public const int __ID__ = -1440538784;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "unitGroupType:" + UnitGroupType + ","
        + "invert:" + Invert + ","
        + "}";
    }
}

}

