
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondRandomPerData : Battle.ConditionData
{
    public CondRandomPerData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["percent"].IsNumber) { throw new SerializationException(); }  Percent = _buf["percent"]; }
    }

    public static CondRandomPerData DeserializeCondRandomPerData(JSONNode _buf)
    {
        return new Skill.CondRandomPerData(_buf);
    }

    /// <summary>
    /// 概率万分比
    /// </summary>
    public readonly int Percent;
   
    public const int __ID__ = 2033138053;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "percent:" + Percent + ","
        + "}";
    }
}

}

