
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondSkillCateUseData : Battle.ConditionData
{
    public CondSkillCateUseData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["skillCate"].IsNumber) { throw new SerializationException(); }  SkillCate = (Skill.SkillCate)_buf["skillCate"].AsInt; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static CondSkillCateUseData DeserializeCondSkillCateUseData(JSONNode _buf)
    {
        return new Skill.CondSkillCateUseData(_buf);
    }

    /// <summary>
    /// 技能分类
    /// </summary>
    public readonly Skill.SkillCate SkillCate;
    /// <summary>
    /// 使用次数
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = -1938197648;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "skillCate:" + SkillCate + ","
        + "count:" + Count + ","
        + "}";
    }
}

}

