
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondHasBuffStateData : Battle.ConditionData
{
    public CondHasBuffStateData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["buffStateType"].IsNumber) { throw new SerializationException(); }  BuffStateType = (Unit.BuffStateType)_buf["buffStateType"].AsInt; }
    }

    public static CondHasBuffStateData DeserializeCondHasBuffStateData(JSONNode _buf)
    {
        return new Skill.CondHasBuffStateData(_buf);
    }

    /// <summary>
    /// buff状态类型(多选)
    /// </summary>
    public readonly Unit.BuffStateType BuffStateType;
   
    public const int __ID__ = -442565811;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "buffStateType:" + BuffStateType + ","
        + "}";
    }
}

}

