
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondHasBuffData : Battle.ConditionData
{
    public CondHasBuffData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["buffCfgId"].IsNumber) { throw new SerializationException(); }  BuffCfgId = _buf["buffCfgId"]; }
    }

    public static CondHasBuffData DeserializeCondHasBuffData(JSONNode _buf)
    {
        return new Skill.CondHasBuffData(_buf);
    }

    /// <summary>
    /// buff配置ID
    /// </summary>
    public readonly int BuffCfgId;
   
    public const int __ID__ = 1674087672;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "buffCfgId:" + BuffCfgId + ","
        + "}";
    }
}

}

