
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public abstract partial class RecoveryData : Luban.BeanBase
{
    public RecoveryData(JSONNode _buf) 
    {
    }

    public static RecoveryData DeserializeRecoveryData(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "RecoveryCD": return new Skill.RecoveryCD(_buf);
            case "RecoveryEnergy": return new Skill.RecoveryEnergy(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

