
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Skill
{ 
    public enum SkillCate
    {
        /// <summary>
        /// 普通攻击
        /// </summary>
        Common = 0,
        /// <summary>
        /// 普通技能
        /// </summary>
        Skill = 1,
        /// <summary>
        /// 手动技能
        /// </summary>
        ManualSkill = 2,
    }

} 

