
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Skill
{ 
    public enum SkillType
    {
        /// <summary>
        /// 主动技能
        /// </summary>
        ActiveSkill = 0,
        /// <summary>
        /// 被动技能
        /// </summary>
        PassiveSkill = 1,
    }

} 

