
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public partial class TbSkillUpgrade
{
    private readonly System.Collections.Generic.Dictionary<int, Skill.CfgSkillUpgrade> _dataMap;
    private readonly System.Collections.Generic.List<Skill.CfgSkillUpgrade> _dataList;
    
    public TbSkillUpgrade(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Skill.CfgSkillUpgrade>();
        _dataList = new System.Collections.Generic.List<Skill.CfgSkillUpgrade>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Skill.CfgSkillUpgrade _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Skill.CfgSkillUpgrade.DeserializeCfgSkillUpgrade(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Skill.CfgSkillUpgrade> DataMap => _dataMap;
    public System.Collections.Generic.List<Skill.CfgSkillUpgrade> DataList => _dataList;

    public Skill.CfgSkillUpgrade GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill.CfgSkillUpgrade Get(int key) => _dataMap[key];
    public Skill.CfgSkillUpgrade this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

