
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public partial class TbSkillSuit
{
    private readonly System.Collections.Generic.Dictionary<int, Skill.CfgSkillSuit> _dataMap;
    private readonly System.Collections.Generic.List<Skill.CfgSkillSuit> _dataList;
    
    public TbSkillSuit(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Skill.CfgSkillSuit>();
        _dataList = new System.Collections.Generic.List<Skill.CfgSkillSuit>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Skill.CfgSkillSuit _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Skill.CfgSkillSuit.DeserializeCfgSkillSuit(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Skill.CfgSkillSuit> DataMap => _dataMap;
    public System.Collections.Generic.List<Skill.CfgSkillSuit> DataList => _dataList;

    public Skill.CfgSkillSuit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill.CfgSkillSuit Get(int key) => _dataMap[key];
    public Skill.CfgSkillSuit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

