
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Table.TbLanguage TbLanguage {get; }
    public Table.TbGlobalConfig TbGlobalConfig {get; }
    public Table.TbSceneMain TbSceneMain {get; }
    public Table.TbUnableBossTime TbUnableBossTime {get; }
    public Reward.TbRewardDrop TbRewardDrop {get; }
    public Reward.TbRewardDropGroup TbRewardDropGroup {get; }
    public Reward.TbRewardDropBox TbRewardDropBox {get; }
    public Item.TbItemMain TbItemMain {get; }
    public Item.TbItemRes TbItemRes {get; }
    public Item.TbItemShard TbItemShard {get; }
    public Skill.TbSkillMain TbSkillMain {get; }
    public Skill.TbSkillSuit TbSkillSuit {get; }
    public Skill.TbSkillUpgrade TbSkillUpgrade {get; }
    public Stage.TbStageMain TbStageMain {get; }
    public Stage.TbStageType TbStageType {get; }
    public Battle.TbBattleAttribute TbBattleAttribute {get; }
    public Battle.TbBattleUnitMain TbBattleUnitMain {get; }
    public Battle.TbBattleSkillMain TbBattleSkillMain {get; }
    public Battle.TbBattleSkillBBParams TbBattleSkillBBParams {get; }
    public Battle.TbBattleSkillTrigger TbBattleSkillTrigger {get; }
    public Battle.TbBuffMain TbBuffMain {get; }
    public Battle.TbBuffCate TbBuffCate {get; }
    public Battle.TbBuffAction TbBuffAction {get; }
    public Battle.TbBattleFx TbBattleFx {get; }
    public Battle.TbBattleGroup TbBattleGroup {get; }
    public Battle.TbBattleFormation TbBattleFormation {get; }
    public Hero.TbHeroMain TbHeroMain {get; }
    public Hero.TbHeroLevel TbHeroLevel {get; }
    public Hero.TbHeroAvatar TbHeroAvatar {get; }
    public Hero.TbHeroTitle TbHeroTitle {get; }
    public Hero.TbHeroAvatarGroup TbHeroAvatarGroup {get; }
    public Hero.TbHeroIntimacy TbHeroIntimacy {get; }
    public Equip.TbEquipMain TbEquipMain {get; }
    public Equip.TbEquipLevel TbEquipLevel {get; }
    public Event.TbEventMain TbEventMain {get; }
    public Gift.TbGiftMain TbGiftMain {get; }
    public Monster.TbBossMain TbBossMain {get; }
    public Boss.TbBossRankReward TbBossRankReward {get; }
    public Boss.TbBossCallNumReward TbBossCallNumReward {get; }
    public WorldBoss.TbWorldBossMain TbWorldBossMain {get; }
    public WorldBoss.TbWorldBossRankReward TbWorldBossRankReward {get; }
    public WorldBoss.TbWorldBossDamageReward TbWorldBossDamageReward {get; }
    public Equip.TbMountMain TbMountMain {get; }
    public Equip.TbMountLevel TbMountLevel {get; }
    public Activity.TbActivityMain TbActivityMain {get; }
    public Activity.TbRewardActivityLoginUse TbRewardActivityLoginUse {get; }
    public Zhenfa.TbZhenfaMain TbZhenfaMain {get; }
    public Zhenfa.TbZhenfaLevel TbZhenfaLevel {get; }
    public Zhenfa.TbZhenfaGroup TbZhenfaGroup {get; }
    public Action.TbActionScoreMain TbActionScoreMain {get; }
    public Table.TbUnitMain TbUnitMain {get; }
    public Rank.RankMain RankMain {get; }
    public Rank.RankReward RankReward {get; }
    public CampWar.CampWarGiftMain CampWarGiftMain {get; }
    public CampWar.CampWarUnit CampWarUnit {get; }
    public CampWar.CampWarRankReward CampWarRankReward {get; }
    public Table.TbQualityMain TbQualityMain {get; }
    public Table.TbTaskMain TbTaskMain {get; }
    public Table.TbAddLikesMain TbAddLikesMain {get; }
    public Table.TbInstructMain TbInstructMain {get; }
    public Table.TbArenatMain TbArenatMain {get; }
    public Dungeon.TbDungeonMain TbDungeonMain {get; }
    public Dungeon.TbDungeonTotal TbDungeonTotal {get; }
    public Dungeon.TbDungeonWave TbDungeonWave {get; }
    public Dungeon.TbDungeonRankReward TbDungeonRankReward {get; }
    public Pet.TbPetMain TbPetMain {get; }
    public Pet.TbPetStar TbPetStar {get; }
    public Pet.TbPetDecompose TbPetDecompose {get; }
    public Pet.TbPetEquip TbPetEquip {get; }
    public Pet.TbPetEquipLevel TbPetEquipLevel {get; }
    public Season.TbInsightRetain TbInsightRetain {get; }
    public Season.TbItemRetain TbItemRetain {get; }
    public Version.VersionMain VersionMain {get; }
    public Trial.TbTrialMain TbTrialMain {get; }
    public Trial.TbTrialTotal TbTrialTotal {get; }
    public Trial.TbTrialWave TbTrialWave {get; }
    public Trial.TbTrialRankReward TbTrialRankReward {get; }
    public Treasure.TbTreasureMain TbTreasureMain {get; }
    public GuildCompetition.GuildCompetitionMain GuildCompetitionMain {get; }
    public GuildCompetition.GuildCompetitionRankReward GuildCompetitionRankReward {get; }
    public Insight.TbInsightMain TbInsightMain {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbLanguage = new Table.TbLanguage(loader("table_tblanguage"));
        TbGlobalConfig = new Table.TbGlobalConfig(loader("table_tbglobalconfig"));
        TbSceneMain = new Table.TbSceneMain(loader("table_tbscenemain"));
        TbUnableBossTime = new Table.TbUnableBossTime(loader("table_tbunablebosstime"));
        TbRewardDrop = new Reward.TbRewardDrop(loader("reward_tbrewarddrop"));
        TbRewardDropGroup = new Reward.TbRewardDropGroup(loader("reward_tbrewarddropgroup"));
        TbRewardDropBox = new Reward.TbRewardDropBox(loader("reward_tbrewarddropbox"));
        TbItemMain = new Item.TbItemMain(loader("item_tbitemmain"));
        TbItemRes = new Item.TbItemRes(loader("item_tbitemres"));
        TbItemShard = new Item.TbItemShard(loader("item_tbitemshard"));
        TbSkillMain = new Skill.TbSkillMain(loader("skill_tbskillmain"));
        TbSkillSuit = new Skill.TbSkillSuit(loader("skill_tbskillsuit"));
        TbSkillUpgrade = new Skill.TbSkillUpgrade(loader("skill_tbskillupgrade"));
        TbStageMain = new Stage.TbStageMain(loader("stage_tbstagemain"));
        TbStageType = new Stage.TbStageType(loader("stage_tbstagetype"));
        TbBattleAttribute = new Battle.TbBattleAttribute(loader("battle_tbbattleattribute"));
        TbBattleUnitMain = new Battle.TbBattleUnitMain(loader("battle_tbbattleunitmain"));
        TbBattleSkillMain = new Battle.TbBattleSkillMain(loader("battle_tbbattleskillmain"));
        TbBattleSkillBBParams = new Battle.TbBattleSkillBBParams(loader("battle_tbbattleskillbbparams"));
        TbBattleSkillTrigger = new Battle.TbBattleSkillTrigger(loader("battle_tbbattleskilltrigger"));
        TbBuffMain = new Battle.TbBuffMain(loader("battle_tbbuffmain"));
        TbBuffCate = new Battle.TbBuffCate(loader("battle_tbbuffcate"));
        TbBuffAction = new Battle.TbBuffAction(loader("battle_tbbuffaction"));
        TbBattleFx = new Battle.TbBattleFx(loader("battle_tbbattlefx"));
        TbBattleGroup = new Battle.TbBattleGroup(loader("battle_tbbattlegroup"));
        TbBattleFormation = new Battle.TbBattleFormation(loader("battle_tbbattleformation"));
        TbHeroMain = new Hero.TbHeroMain(loader("hero_tbheromain"));
        TbHeroLevel = new Hero.TbHeroLevel(loader("hero_tbherolevel"));
        TbHeroAvatar = new Hero.TbHeroAvatar(loader("hero_tbheroavatar"));
        TbHeroTitle = new Hero.TbHeroTitle(loader("hero_tbherotitle"));
        TbHeroAvatarGroup = new Hero.TbHeroAvatarGroup(loader("hero_tbheroavatargroup"));
        TbHeroIntimacy = new Hero.TbHeroIntimacy(loader("hero_tbherointimacy"));
        TbEquipMain = new Equip.TbEquipMain(loader("equip_tbequipmain"));
        TbEquipLevel = new Equip.TbEquipLevel(loader("equip_tbequiplevel"));
        TbEventMain = new Event.TbEventMain(loader("event_tbeventmain"));
        TbGiftMain = new Gift.TbGiftMain(loader("gift_tbgiftmain"));
        TbBossMain = new Monster.TbBossMain(loader("monster_tbbossmain"));
        TbBossRankReward = new Boss.TbBossRankReward(loader("boss_tbbossrankreward"));
        TbBossCallNumReward = new Boss.TbBossCallNumReward(loader("boss_tbbosscallnumreward"));
        TbWorldBossMain = new WorldBoss.TbWorldBossMain(loader("worldboss_tbworldbossmain"));
        TbWorldBossRankReward = new WorldBoss.TbWorldBossRankReward(loader("worldboss_tbworldbossrankreward"));
        TbWorldBossDamageReward = new WorldBoss.TbWorldBossDamageReward(loader("worldboss_tbworldbossdamagereward"));
        TbMountMain = new Equip.TbMountMain(loader("equip_tbmountmain"));
        TbMountLevel = new Equip.TbMountLevel(loader("equip_tbmountlevel"));
        TbActivityMain = new Activity.TbActivityMain(loader("activity_tbactivitymain"));
        TbRewardActivityLoginUse = new Activity.TbRewardActivityLoginUse(loader("activity_tbrewardactivityloginuse"));
        TbZhenfaMain = new Zhenfa.TbZhenfaMain(loader("zhenfa_tbzhenfamain"));
        TbZhenfaLevel = new Zhenfa.TbZhenfaLevel(loader("zhenfa_tbzhenfalevel"));
        TbZhenfaGroup = new Zhenfa.TbZhenfaGroup(loader("zhenfa_tbzhenfagroup"));
        TbActionScoreMain = new Action.TbActionScoreMain(loader("action_tbactionscoremain"));
        TbUnitMain = new Table.TbUnitMain(loader("table_tbunitmain"));
        RankMain = new Rank.RankMain(loader("rank_rankmain"));
        RankReward = new Rank.RankReward(loader("rank_rankreward"));
        CampWarGiftMain = new CampWar.CampWarGiftMain(loader("campwar_campwargiftmain"));
        CampWarUnit = new CampWar.CampWarUnit(loader("campwar_campwarunit"));
        CampWarRankReward = new CampWar.CampWarRankReward(loader("campwar_campwarrankreward"));
        TbQualityMain = new Table.TbQualityMain(loader("table_tbqualitymain"));
        TbTaskMain = new Table.TbTaskMain(loader("table_tbtaskmain"));
        TbAddLikesMain = new Table.TbAddLikesMain(loader("table_tbaddlikesmain"));
        TbInstructMain = new Table.TbInstructMain(loader("table_tbinstructmain"));
        TbArenatMain = new Table.TbArenatMain(loader("table_tbarenatmain"));
        TbDungeonMain = new Dungeon.TbDungeonMain(loader("dungeon_tbdungeonmain"));
        TbDungeonTotal = new Dungeon.TbDungeonTotal(loader("dungeon_tbdungeontotal"));
        TbDungeonWave = new Dungeon.TbDungeonWave(loader("dungeon_tbdungeonwave"));
        TbDungeonRankReward = new Dungeon.TbDungeonRankReward(loader("dungeon_tbdungeonrankreward"));
        TbPetMain = new Pet.TbPetMain(loader("pet_tbpetmain"));
        TbPetStar = new Pet.TbPetStar(loader("pet_tbpetstar"));
        TbPetDecompose = new Pet.TbPetDecompose(loader("pet_tbpetdecompose"));
        TbPetEquip = new Pet.TbPetEquip(loader("pet_tbpetequip"));
        TbPetEquipLevel = new Pet.TbPetEquipLevel(loader("pet_tbpetequiplevel"));
        TbInsightRetain = new Season.TbInsightRetain(loader("season_tbinsightretain"));
        TbItemRetain = new Season.TbItemRetain(loader("season_tbitemretain"));
        VersionMain = new Version.VersionMain(loader("version_versionmain"));
        TbTrialMain = new Trial.TbTrialMain(loader("trial_tbtrialmain"));
        TbTrialTotal = new Trial.TbTrialTotal(loader("trial_tbtrialtotal"));
        TbTrialWave = new Trial.TbTrialWave(loader("trial_tbtrialwave"));
        TbTrialRankReward = new Trial.TbTrialRankReward(loader("trial_tbtrialrankreward"));
        TbTreasureMain = new Treasure.TbTreasureMain(loader("treasure_tbtreasuremain"));
        GuildCompetitionMain = new GuildCompetition.GuildCompetitionMain(loader("guildcompetition_guildcompetitionmain"));
        GuildCompetitionRankReward = new GuildCompetition.GuildCompetitionRankReward(loader("guildcompetition_guildcompetitionrankreward"));
        TbInsightMain = new Insight.TbInsightMain(loader("insight_tbinsightmain"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbLanguage.ResolveRef(this);
        TbGlobalConfig.ResolveRef(this);
        TbSceneMain.ResolveRef(this);
        TbUnableBossTime.ResolveRef(this);
        TbRewardDrop.ResolveRef(this);
        TbRewardDropGroup.ResolveRef(this);
        TbRewardDropBox.ResolveRef(this);
        TbItemMain.ResolveRef(this);
        TbItemRes.ResolveRef(this);
        TbItemShard.ResolveRef(this);
        TbSkillMain.ResolveRef(this);
        TbSkillSuit.ResolveRef(this);
        TbSkillUpgrade.ResolveRef(this);
        TbStageMain.ResolveRef(this);
        TbStageType.ResolveRef(this);
        TbBattleAttribute.ResolveRef(this);
        TbBattleUnitMain.ResolveRef(this);
        TbBattleSkillMain.ResolveRef(this);
        TbBattleSkillBBParams.ResolveRef(this);
        TbBattleSkillTrigger.ResolveRef(this);
        TbBuffMain.ResolveRef(this);
        TbBuffCate.ResolveRef(this);
        TbBuffAction.ResolveRef(this);
        TbBattleFx.ResolveRef(this);
        TbBattleGroup.ResolveRef(this);
        TbBattleFormation.ResolveRef(this);
        TbHeroMain.ResolveRef(this);
        TbHeroLevel.ResolveRef(this);
        TbHeroAvatar.ResolveRef(this);
        TbHeroTitle.ResolveRef(this);
        TbHeroAvatarGroup.ResolveRef(this);
        TbHeroIntimacy.ResolveRef(this);
        TbEquipMain.ResolveRef(this);
        TbEquipLevel.ResolveRef(this);
        TbEventMain.ResolveRef(this);
        TbGiftMain.ResolveRef(this);
        TbBossMain.ResolveRef(this);
        TbBossRankReward.ResolveRef(this);
        TbBossCallNumReward.ResolveRef(this);
        TbWorldBossMain.ResolveRef(this);
        TbWorldBossRankReward.ResolveRef(this);
        TbWorldBossDamageReward.ResolveRef(this);
        TbMountMain.ResolveRef(this);
        TbMountLevel.ResolveRef(this);
        TbActivityMain.ResolveRef(this);
        TbRewardActivityLoginUse.ResolveRef(this);
        TbZhenfaMain.ResolveRef(this);
        TbZhenfaLevel.ResolveRef(this);
        TbZhenfaGroup.ResolveRef(this);
        TbActionScoreMain.ResolveRef(this);
        TbUnitMain.ResolveRef(this);
        RankMain.ResolveRef(this);
        RankReward.ResolveRef(this);
        CampWarGiftMain.ResolveRef(this);
        CampWarUnit.ResolveRef(this);
        CampWarRankReward.ResolveRef(this);
        TbQualityMain.ResolveRef(this);
        TbTaskMain.ResolveRef(this);
        TbAddLikesMain.ResolveRef(this);
        TbInstructMain.ResolveRef(this);
        TbArenatMain.ResolveRef(this);
        TbDungeonMain.ResolveRef(this);
        TbDungeonTotal.ResolveRef(this);
        TbDungeonWave.ResolveRef(this);
        TbDungeonRankReward.ResolveRef(this);
        TbPetMain.ResolveRef(this);
        TbPetStar.ResolveRef(this);
        TbPetDecompose.ResolveRef(this);
        TbPetEquip.ResolveRef(this);
        TbPetEquipLevel.ResolveRef(this);
        TbInsightRetain.ResolveRef(this);
        TbItemRetain.ResolveRef(this);
        VersionMain.ResolveRef(this);
        TbTrialMain.ResolveRef(this);
        TbTrialTotal.ResolveRef(this);
        TbTrialWave.ResolveRef(this);
        TbTrialRankReward.ResolveRef(this);
        TbTreasureMain.ResolveRef(this);
        GuildCompetitionMain.ResolveRef(this);
        GuildCompetitionRankReward.ResolveRef(this);
        TbInsightMain.ResolveRef(this);
    }
}

}
