
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Pet
{
public sealed partial class CfgPetStar : Luban.BeanBase
{
    public CfgPetStar(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { var __json0 = _buf["specialEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialEffect = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialEffect.Add(__v0); }   }
        { if(!_buf["convertCoefficient"].IsNumber) { throw new SerializationException(); }  ConvertCoefficient = _buf["convertCoefficient"]; }
        { var __json0 = _buf["starCost"]; if(!__json0.IsArray) { throw new SerializationException(); } StarCost = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  StarCost.Add(__v0); }   }
        { var __json0 = _buf["buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } Buffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buffs.Add(__v0); }   }
        { if(!_buf["animation"].IsString) { throw new SerializationException(); }  Animation = _buf["animation"]; }
    }

    public static CfgPetStar DeserializeCfgPetStar(JSONNode _buf)
    {
        return new Pet.CfgPetStar(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 星级
    /// </summary>
    public readonly int Star;
    /// <summary>
    /// 在宠物基础上附加属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialEffect;
    /// <summary>
    /// 共鸣系数
    /// </summary>
    public readonly float ConvertCoefficient;
    /// <summary>
    /// 升星消耗
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> StarCost;
    /// <summary>
    /// 效果id
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buffs;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> Buffs_Ref;
    /// <summary>
    /// 动画
    /// </summary>
    public readonly string Animation;
   
    public const int __ID__ = -175923332;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SpecialEffect) { _e?.ResolveRef(tables); }
        foreach (var _e in StarCost) { _e?.ResolveRef(tables); }
        Buffs_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in Buffs) { Buffs_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "star:" + Star + ","
        + "specialEffect:" + Luban.StringUtil.CollectionToString(SpecialEffect) + ","
        + "convertCoefficient:" + ConvertCoefficient + ","
        + "starCost:" + Luban.StringUtil.CollectionToString(StarCost) + ","
        + "buffs:" + Luban.StringUtil.CollectionToString(Buffs) + ","
        + "animation:" + Animation + ","
        + "}";
    }
}

}

