
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Pet
{
public partial class TbPetEquipLevel
{
    private readonly System.Collections.Generic.Dictionary<int, Pet.CfgPetEquipLevel> _dataMap;
    private readonly System.Collections.Generic.List<Pet.CfgPetEquipLevel> _dataList;
    
    public TbPetEquipLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Pet.CfgPetEquipLevel>();
        _dataList = new System.Collections.Generic.List<Pet.CfgPetEquipLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Pet.CfgPetEquipLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Pet.CfgPetEquipLevel.DeserializeCfgPetEquipLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Pet.CfgPetEquipLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<Pet.CfgPetEquipLevel> DataList => _dataList;

    public Pet.CfgPetEquipLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Pet.CfgPetEquipLevel Get(int key) => _dataMap[key];
    public Pet.CfgPetEquipLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

