
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Stage
{
public sealed partial class CfgStageMain : Luban.BeanBase
{
    public CfgStageMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["stageType"].IsNumber) { throw new SerializationException(); }  StageType = (Stage.Type)_buf["stageType"].AsInt; }
        { var __json0 = _buf["groupList"]; if(!__json0.IsArray) { throw new SerializationException(); } GroupList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  GroupList.Add(__v0); }   }
        { if(!_buf["isAllowInvade"].IsBoolean) { throw new SerializationException(); }  IsAllowInvade = _buf["isAllowInvade"]; }
        { if(!_buf["isAllowJoin"].IsBoolean) { throw new SerializationException(); }  IsAllowJoin = _buf["isAllowJoin"]; }
        { if(!_buf["isAllowDefense"].IsBoolean) { throw new SerializationException(); }  IsAllowDefense = _buf["isAllowDefense"]; }
        { if(!_buf["isAllowSummonBoss"].IsBoolean) { throw new SerializationException(); }  IsAllowSummonBoss = _buf["isAllowSummonBoss"]; }
        { if(!_buf["isBattleQuit"].IsBoolean) { throw new SerializationException(); }  IsBattleQuit = _buf["isBattleQuit"]; }
        { var __json0 = _buf["sceneGroup"]; if(!__json0.IsArray) { throw new SerializationException(); } SceneGroup = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SceneGroup.Add(__v0); }   }
        { var __json0 = _buf["mapBTrees"]; if(!__json0.IsArray) { throw new SerializationException(); } MapBTrees = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  MapBTrees.Add(__v0); }   }
        { var __json0 = _buf["buff"]; if(!__json0.IsArray) { throw new SerializationException(); } Buff = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buff.Add(__v0); }   }
        { if(!_buf["groupType"].IsNumber) { throw new SerializationException(); }  GroupType = (Battle.GroupType)_buf["groupType"].AsInt; }
    }

    public static CfgStageMain DeserializeCfgStageMain(JSONNode _buf)
    {
        return new Stage.CfgStageMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 关卡类型
    /// </summary>
    public readonly Stage.Type StageType;
    /// <summary>
    /// 战斗组
    /// </summary>
    public readonly System.Collections.Generic.List<int> GroupList;
    public System.Collections.Generic.List<Battle.CfgBattleGroupData> GroupList_Ref;
    /// <summary>
    /// 是否能入侵
    /// </summary>
    public readonly bool IsAllowInvade;
    /// <summary>
    /// 是否能加入
    /// </summary>
    public readonly bool IsAllowJoin;
    /// <summary>
    /// 是否能协防
    /// </summary>
    public readonly bool IsAllowDefense;
    /// <summary>
    /// 是否能召唤BOSS
    /// </summary>
    public readonly bool IsAllowSummonBoss;
    /// <summary>
    /// 是否战斗中可以退出
    /// </summary>
    public readonly bool IsBattleQuit;
    /// <summary>
    /// 场景数组
    /// </summary>
    public readonly System.Collections.Generic.List<int> SceneGroup;
    public System.Collections.Generic.List<Table.CfgSceneMain> SceneGroup_Ref;
    /// <summary>
    /// 关卡行为树
    /// </summary>
    public readonly System.Collections.Generic.List<string> MapBTrees;
    /// <summary>
    /// buff效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buff;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> Buff_Ref;
    /// <summary>
    /// buff生效对象
    /// </summary>
    public readonly Battle.GroupType GroupType;
   
    public const int __ID__ = 1693655811;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        GroupList_Ref = new System.Collections.Generic.List<Battle.CfgBattleGroupData>();
        foreach (var _v in GroupList) { GroupList_Ref.Add(tables.TbBattleGroup.GetOrDefault(_v)); }

        SceneGroup_Ref = new System.Collections.Generic.List<Table.CfgSceneMain>();
        foreach (var _v in SceneGroup) { SceneGroup_Ref.Add(tables.TbSceneMain.GetOrDefault(_v)); }

        Buff_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in Buff) { Buff_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "stageType:" + StageType + ","
        + "groupList:" + Luban.StringUtil.CollectionToString(GroupList) + ","
        + "isAllowInvade:" + IsAllowInvade + ","
        + "isAllowJoin:" + IsAllowJoin + ","
        + "isAllowDefense:" + IsAllowDefense + ","
        + "isAllowSummonBoss:" + IsAllowSummonBoss + ","
        + "isBattleQuit:" + IsBattleQuit + ","
        + "sceneGroup:" + Luban.StringUtil.CollectionToString(SceneGroup) + ","
        + "mapBTrees:" + Luban.StringUtil.CollectionToString(MapBTrees) + ","
        + "buff:" + Luban.StringUtil.CollectionToString(Buff) + ","
        + "groupType:" + GroupType + ","
        + "}";
    }
}

}

