
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Stage
{ 
    public enum NormalStageType
    {
        /// <summary>
        /// 普通关卡
        /// </summary>
        Common = 1,
        /// <summary>
        /// 金币关卡
        /// </summary>
        Gold = 2,
        /// <summary>
        /// 经验关卡
        /// </summary>
        Exp = 3,
    }

} 

