
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Item
{ 
    public enum Quality
    {
        /// <summary>
        /// 白
        /// </summary>
        White = 0,
        /// <summary>
        /// 绿
        /// </summary>
        Green = 1,
        /// <summary>
        /// 蓝
        /// </summary>
        Blue = 2,
        /// <summary>
        /// 紫
        /// </summary>
        Purple = 3,
        /// <summary>
        /// 金
        /// </summary>
        Gold = 4,
        /// <summary>
        /// 红
        /// </summary>
        Red = 5,
        /// <summary>
        /// 粉
        /// </summary>
        Powder = 6,
        /// <summary>
        /// 彩
        /// </summary>
        Colour = 7,
    }

} 

