
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public sealed partial class CfgHeroAvatarGroup : Luban.BeanBase
{
    public CfgHeroAvatarGroup(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["maleAvatar"].IsNumber) { throw new SerializationException(); }  MaleAvatar = _buf["maleAvatar"]; }
        { if(!_buf["femaleAvatar"].IsNumber) { throw new SerializationException(); }  FemaleAvatar = _buf["femaleAvatar"]; }
        { if(!_buf["specialAvatar"].IsNumber) { throw new SerializationException(); }  SpecialAvatar = _buf["specialAvatar"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["specialAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialAttrValue = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialAttrValue.Add(__v0); }   }
        { if(!_buf["unlock"].IsString) { throw new SerializationException(); }  Unlock = _buf["unlock"]; }
    }

    public static CfgHeroAvatarGroup DeserializeCfgHeroAvatarGroup(JSONNode _buf)
    {
        return new Hero.CfgHeroAvatarGroup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 男avatar
    /// </summary>
    public readonly int MaleAvatar;
    /// <summary>
    /// 女avatar
    /// </summary>
    public readonly int FemaleAvatar;
    /// <summary>
    /// 是否特殊皮肤
    /// </summary>
    public readonly int SpecialAvatar;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 附加属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialAttrValue;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly string Unlock;
   
    public const int __ID__ = -1333502532;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SpecialAttrValue) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maleAvatar:" + MaleAvatar + ","
        + "femaleAvatar:" + FemaleAvatar + ","
        + "specialAvatar:" + SpecialAvatar + ","
        + "name:" + Name + ","
        + "specialAttrValue:" + Luban.StringUtil.CollectionToString(SpecialAttrValue) + ","
        + "unlock:" + Unlock + ","
        + "}";
    }
}

}

