
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public sealed partial class CfgHeroMain : Luban.BeanBase
{
    public CfgHeroMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["unitID"].IsNumber) { throw new SerializationException(); }  UnitID = _buf["unitID"]; }
        { if(!_buf["avatar"].IsNumber) { throw new SerializationException(); }  Avatar = _buf["avatar"]; }
        { var __json0 = _buf["equip"]; if(!__json0.IsArray) { throw new SerializationException(); } Equip = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Equip.Add(__v0); }   }
        { if(!_buf["mount"].IsNumber) { throw new SerializationException(); }  Mount = _buf["mount"]; }
        Mount_Ref = null;
        { if(!_buf["state"].IsNumber) { throw new SerializationException(); }  State = _buf["state"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
    }

    public static CfgHeroMain DeserializeCfgHeroMain(JSONNode _buf)
    {
        return new Hero.CfgHeroMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 单位id
    /// </summary>
    public readonly int UnitID;
    /// <summary>
    /// 模型id
    /// </summary>
    public readonly int Avatar;
    /// <summary>
    /// 法宝id
    /// </summary>
    public readonly System.Collections.Generic.List<int> Equip;
    public System.Collections.Generic.List<Equip.CfgEquipMain> Equip_Ref;
    /// <summary>
    /// 坐骑id
    /// </summary>
    public readonly int Mount;
    public Equip.CfgMountMain Mount_Ref;
    /// <summary>
    /// 境界
    /// </summary>
    public readonly int State;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
   
    public const int __ID__ = 430983523;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Equip_Ref = new System.Collections.Generic.List<Equip.CfgEquipMain>();
        foreach (var _v in Equip) { Equip_Ref.Add(tables.TbEquipMain.GetOrDefault(_v)); }

        Mount_Ref = tables.TbMountMain.GetOrDefault(Mount);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "unitID:" + UnitID + ","
        + "avatar:" + Avatar + ","
        + "equip:" + Luban.StringUtil.CollectionToString(Equip) + ","
        + "mount:" + Mount + ","
        + "state:" + State + ","
        + "level:" + Level + ","
        + "}";
    }
}

}

