
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public sealed partial class CfgHeroIntimacy : Luban.BeanBase
{
    public CfgHeroIntimacy(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["intimacy"].IsNumber) { throw new SerializationException(); }  Intimacy = _buf["intimacy"]; }
        { var __json0 = _buf["specialAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialAttrValue = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialAttrValue.Add(__v0); }   }
        { if(!_buf["animation"].IsString) { throw new SerializationException(); }  Animation = _buf["animation"]; }
    }

    public static CfgHeroIntimacy DeserializeCfgHeroIntimacy(JSONNode _buf)
    {
        return new Hero.CfgHeroIntimacy(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 亲密度
    /// </summary>
    public readonly int Intimacy;
    /// <summary>
    /// 双方附加属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialAttrValue;
    /// <summary>
    /// 动画
    /// </summary>
    public readonly string Animation;
   
    public const int __ID__ = -290124530;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SpecialAttrValue) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "intimacy:" + Intimacy + ","
        + "specialAttrValue:" + Luban.StringUtil.CollectionToString(SpecialAttrValue) + ","
        + "animation:" + Animation + ","
        + "}";
    }
}

}

