
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public partial class TbHeroAvatarGroup
{
    private readonly System.Collections.Generic.Dictionary<int, Hero.CfgHeroAvatarGroup> _dataMap;
    private readonly System.Collections.Generic.List<Hero.CfgHeroAvatarGroup> _dataList;
    
    public TbHeroAvatarGroup(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Hero.CfgHeroAvatarGroup>();
        _dataList = new System.Collections.Generic.List<Hero.CfgHeroAvatarGroup>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Hero.CfgHeroAvatarGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Hero.CfgHeroAvatarGroup.DeserializeCfgHeroAvatarGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Hero.CfgHeroAvatarGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<Hero.CfgHeroAvatarGroup> DataList => _dataList;

    public Hero.CfgHeroAvatarGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Hero.CfgHeroAvatarGroup Get(int key) => _dataMap[key];
    public Hero.CfgHeroAvatarGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

