
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public partial class TbHeroTitle
{
    private readonly System.Collections.Generic.Dictionary<int, Hero.CfgHeroTitle> _dataMap;
    private readonly System.Collections.Generic.List<Hero.CfgHeroTitle> _dataList;
    
    public TbHeroTitle(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Hero.CfgHeroTitle>();
        _dataList = new System.Collections.Generic.List<Hero.CfgHeroTitle>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Hero.CfgHeroTitle _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Hero.CfgHeroTitle.DeserializeCfgHeroTitle(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Hero.CfgHeroTitle> DataMap => _dataMap;
    public System.Collections.Generic.List<Hero.CfgHeroTitle> DataList => _dataList;

    public Hero.CfgHeroTitle GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Hero.CfgHeroTitle Get(int key) => _dataMap[key];
    public Hero.CfgHeroTitle this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

