
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public partial class TbHeroLevel
{
    private readonly System.Collections.Generic.Dictionary<int, Hero.CfgHeroLevel> _dataMap;
    private readonly System.Collections.Generic.List<Hero.CfgHeroLevel> _dataList;
    
    public TbHeroLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Hero.CfgHeroLevel>();
        _dataList = new System.Collections.Generic.List<Hero.CfgHeroLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Hero.CfgHeroLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Hero.CfgHeroLevel.DeserializeCfgHeroLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Hero.CfgHeroLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<Hero.CfgHeroLevel> DataList => _dataList;

    public Hero.CfgHeroLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Hero.CfgHeroLevel Get(int key) => _dataMap[key];
    public Hero.CfgHeroLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

