
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public sealed partial class CfgHeroAvatar : Luban.BeanBase
{
    public CfgHeroAvatar(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["sort"]; }
        { if(!_buf["gender"].IsNumber) { throw new SerializationException(); }  Gender = _buf["gender"]; }
        { if(!_buf["battleUnitID"].IsNumber) { throw new SerializationException(); }  BattleUnitID = _buf["battleUnitID"]; }
        BattleUnitID_Ref = null;
        { if(!_buf["spineID"].IsNumber) { throw new SerializationException(); }  SpineID = _buf["spineID"]; }
        { if(!_buf["time"].IsNumber) { throw new SerializationException(); }  Time = _buf["time"]; }
        { var __json0 = _buf["specialAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialAttrValue = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialAttrValue.Add(__v0); }   }
        { if(!_buf["icon_big"].IsString) { throw new SerializationException(); }  IconBig = _buf["icon_big"]; }
        { if(!_buf["icon_medium"].IsString) { throw new SerializationException(); }  IconMedium = _buf["icon_medium"]; }
        { if(!_buf["durationTimeUI"].IsString) { throw new SerializationException(); }  DurationTimeUI = _buf["durationTimeUI"]; }
    }

    public static CfgHeroAvatar DeserializeCfgHeroAvatar(JSONNode _buf)
    {
        return new Hero.CfgHeroAvatar(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 境界
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Sort;
    /// <summary>
    /// 性别
    /// </summary>
    public readonly int Gender;
    /// <summary>
    /// 单位id
    /// </summary>
    public readonly int BattleUnitID;
    public Battle.CfgBattleUnitData BattleUnitID_Ref;
    /// <summary>
    /// spineid
    /// </summary>
    public readonly int SpineID;
    /// <summary>
    /// 时效，秒
    /// </summary>
    public readonly int Time;
    /// <summary>
    /// 附加属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialAttrValue;
    /// <summary>
    /// 大号ICON
    /// </summary>
    public readonly string IconBig;
    /// <summary>
    /// 中号ICON
    /// </summary>
    public readonly string IconMedium;
    /// <summary>
    /// 持续时间UI皮肤
    /// </summary>
    public readonly string DurationTimeUI;
   
    public const int __ID__ = 1533919875;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BattleUnitID_Ref = tables.TbBattleUnitMain.GetOrDefault(BattleUnitID);
        foreach (var _e in SpecialAttrValue) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "sort:" + Sort + ","
        + "gender:" + Gender + ","
        + "battleUnitID:" + BattleUnitID + ","
        + "spineID:" + SpineID + ","
        + "time:" + Time + ","
        + "specialAttrValue:" + Luban.StringUtil.CollectionToString(SpecialAttrValue) + ","
        + "iconBig:" + IconBig + ","
        + "iconMedium:" + IconMedium + ","
        + "durationTimeUI:" + DurationTimeUI + ","
        + "}";
    }
}

}

