
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public sealed partial class CfgHeroLevel : Luban.BeanBase
{
    public CfgHeroLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["rate"].IsNumber) { throw new SerializationException(); }  Rate = _buf["rate"]; }
        { var __json0 = _buf["baseAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } BaseAttrValue = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  BaseAttrValue.Add(__v0); }   }
        { var __json0 = _buf["addAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } AddAttrValue = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  AddAttrValue.Add(__v0); }   }
        { if(!_buf["lvExp"].IsNumber) { throw new SerializationException(); }  LvExp = _buf["lvExp"]; }
        { if(!_buf["saveExp"].IsNumber) { throw new SerializationException(); }  SaveExp = _buf["saveExp"]; }
        { if(!_buf["maxLevel"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["maxLevel"]; }
        { if(!_buf["practiceExp"].IsNumber) { throw new SerializationException(); }  PracticeExp = _buf["practiceExp"]; }
        { var __json0 = _buf["reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Reward.Add(__v0); }   }
        { if(!_buf["meritScore"].IsNumber) { throw new SerializationException(); }  MeritScore = _buf["meritScore"]; }
        { if(!_buf["zhenfaExp"].IsNumber) { throw new SerializationException(); }  ZhenfaExp = _buf["zhenfaExp"]; }
        { if(!_buf["MainSorce"].IsNumber) { throw new SerializationException(); }  MainSorce = _buf["MainSorce"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["specialDisplay"].IsNumber) { throw new SerializationException(); }  SpecialDisplay = _buf["specialDisplay"]; }
    }

    public static CfgHeroLevel DeserializeCfgHeroLevel(JSONNode _buf)
    {
        return new Hero.CfgHeroLevel(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 境界
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 突破成功率
    /// </summary>
    public readonly int Rate;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> BaseAttrValue;
    /// <summary>
    /// 升级属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> AddAttrValue;
    /// <summary>
    /// 升级经验
    /// </summary>
    public readonly long LvExp;
    /// <summary>
    /// 保存经验上限
    /// </summary>
    public readonly long SaveExp;
    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 修炼值
    /// </summary>
    public readonly int PracticeExp;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Reward;
    /// <summary>
    /// 击杀该境界获得功勋值
    /// </summary>
    public readonly int MeritScore;
    /// <summary>
    /// 击杀该境界获得阵法经验
    /// </summary>
    public readonly int ZhenfaExp;
    /// <summary>
    /// 击杀改境界获得积分值
    /// </summary>
    public readonly int MainSorce;
    /// <summary>
    /// 境界图片
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 突破到该境界专属展示
    /// </summary>
    public readonly int SpecialDisplay;
   
    public const int __ID__ = 474795290;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BaseAttrValue) { _e?.ResolveRef(tables); }
        foreach (var _e in AddAttrValue) { _e?.ResolveRef(tables); }
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "rate:" + Rate + ","
        + "baseAttrValue:" + Luban.StringUtil.CollectionToString(BaseAttrValue) + ","
        + "addAttrValue:" + Luban.StringUtil.CollectionToString(AddAttrValue) + ","
        + "lvExp:" + LvExp + ","
        + "saveExp:" + SaveExp + ","
        + "maxLevel:" + MaxLevel + ","
        + "practiceExp:" + PracticeExp + ","
        + "reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "meritScore:" + MeritScore + ","
        + "zhenfaExp:" + ZhenfaExp + ","
        + "MainSorce:" + MainSorce + ","
        + "icon:" + Icon + ","
        + "specialDisplay:" + SpecialDisplay + ","
        + "}";
    }
}

}

