
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Hero
{
public partial class TbHeroIntimacy
{
    private readonly System.Collections.Generic.Dictionary<int, Hero.CfgHeroIntimacy> _dataMap;
    private readonly System.Collections.Generic.List<Hero.CfgHeroIntimacy> _dataList;
    
    public TbHeroIntimacy(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Hero.CfgHeroIntimacy>();
        _dataList = new System.Collections.Generic.List<Hero.CfgHeroIntimacy>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Hero.CfgHeroIntimacy _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Hero.CfgHeroIntimacy.DeserializeCfgHeroIntimacy(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Hero.CfgHeroIntimacy> DataMap => _dataMap;
    public System.Collections.Generic.List<Hero.CfgHeroIntimacy> DataList => _dataList;

    public Hero.CfgHeroIntimacy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Hero.CfgHeroIntimacy Get(int key) => _dataMap[key];
    public Hero.CfgHeroIntimacy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

