
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CfgSkillUpgrade : Luban.BeanBase
{
    public CfgSkillUpgrade(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["cost"]; if(!__json0.IsArray) { throw new SerializationException(); } Cost = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Cost.Add(__v0); }   }
        { if(!_buf["upgradeID"].IsNumber) { throw new SerializationException(); }  UpgradeID = _buf["upgradeID"]; }
    }

    public static CfgSkillUpgrade DeserializeCfgSkillUpgrade(JSONNode _buf)
    {
        return new Skill.CfgSkillUpgrade(_buf);
    }

    /// <summary>
    /// 进阶功法id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级消耗
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Cost;
    /// <summary>
    /// 升级后功法id
    /// </summary>
    public readonly int UpgradeID;
   
    public const int __ID__ = -643193038;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Cost) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "cost:" + Luban.StringUtil.CollectionToString(Cost) + ","
        + "upgradeID:" + UpgradeID + ","
        + "}";
    }
}

}

