
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondTargetBodyTypeData : Battle.ConditionData
{
    public CondTargetBodyTypeData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["bodyType"].IsNumber) { throw new SerializationException(); }  BodyType = (Unit.BodyType)_buf["bodyType"].AsInt; }
    }

    public static CondTargetBodyTypeData DeserializeCondTargetBodyTypeData(JSONNode _buf)
    {
        return new Skill.CondTargetBodyTypeData(_buf);
    }

    /// <summary>
    /// 目标体型(多选)
    /// </summary>
    public readonly Unit.BodyType BodyType;
   
    public const int __ID__ = -2147438282;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "bodyType:" + BodyType + ","
        + "}";
    }
}

}

