
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondUnitRandomAtivateSkillData : Battle.ConditionData
{
    public CondUnitRandomAtivateSkillData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["invert"].IsBoolean) { throw new SerializationException(); }  Invert = _buf["invert"]; }
    }

    public static CondUnitRandomAtivateSkillData DeserializeCondUnitRandomAtivateSkillData(JSONNode _buf)
    {
        return new Skill.CondUnitRandomAtivateSkillData(_buf);
    }

    /// <summary>
    /// 取返
    /// </summary>
    public readonly bool Invert;
   
    public const int __ID__ = -151623281;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "invert:" + Invert + ","
        + "}";
    }
}

}

