
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CondCompareHpData : Battle.ConditionData
{
    public CondCompareHpData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["compareMode"].IsNumber) { throw new SerializationException(); }  CompareMode = (Condition.CompareMode)_buf["compareMode"].AsInt; }
        { if(!_buf["compareValue"].IsNumber) { throw new SerializationException(); }  CompareValue = _buf["compareValue"]; }
    }

    public static CondCompareHpData DeserializeCondCompareHpData(JSONNode _buf)
    {
        return new Skill.CondCompareHpData(_buf);
    }

    /// <summary>
    /// 比较方式
    /// </summary>
    public readonly Condition.CompareMode CompareMode;
    /// <summary>
    /// 比较值万分比
    /// </summary>
    public readonly int CompareValue;
   
    public const int __ID__ = -625512584;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "compareMode:" + CompareMode + ","
        + "compareValue:" + CompareValue + ","
        + "}";
    }
}

}

