
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class SkAndSktIdData : Luban.BeanBase
{
    public SkAndSktIdData(JSONNode _buf) 
    {
        { if(!_buf["skId"].IsNumber) { throw new SerializationException(); }  SkId = _buf["skId"]; }
        { if(!_buf["sktId"].IsNumber) { throw new SerializationException(); }  SktId = _buf["sktId"]; }
    }

    public static SkAndSktIdData DeserializeSkAndSktIdData(JSONNode _buf)
    {
        return new Skill.SkAndSktIdData(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int SkId;
    /// <summary>
    /// 技能树ID
    /// </summary>
    public readonly int SktId;
   
    public const int __ID__ = 1152743295;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "skId:" + SkId + ","
        + "sktId:" + SktId + ","
        + "}";
    }
}

}

