
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Zhenfa
{
public sealed partial class CfgZhenfaGroup : Luban.BeanBase
{
    public CfgZhenfaGroup(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["unlockLevel"].IsNumber) { throw new SerializationException(); }  UnlockLevel = _buf["unlockLevel"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static CfgZhenfaGroup DeserializeCfgZhenfaGroup(JSONNode _buf)
    {
        return new Zhenfa.CfgZhenfaGroup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// icon
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = -1763362459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}

