
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Zhenfa
{
public sealed partial class CfgZhenfaLevel : Luban.BeanBase
{
    public CfgZhenfaLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["lvExp"].IsNumber) { throw new SerializationException(); }  LvExp = _buf["lvExp"]; }
        { if(!_buf["ZhanfaBaseExp"].IsNumber) { throw new SerializationException(); }  ZhanfaBaseExp = _buf["ZhanfaBaseExp"]; }
        { var __json0 = _buf["baseAttrValue"]; if(!__json0.IsArray) { throw new SerializationException(); } BaseAttrValue = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  BaseAttrValue.Add(__v0); }   }
        { if(!_buf["reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["reward"]; }
        { if(!_buf["ZhenfaRecoverTime"].IsNumber) { throw new SerializationException(); }  ZhenfaRecoverTime = _buf["ZhenfaRecoverTime"]; }
        { if(!_buf["killZhenfaExp"].IsNumber) { throw new SerializationException(); }  KillZhenfaExp = _buf["killZhenfaExp"]; }
    }

    public static CfgZhenfaLevel DeserializeCfgZhenfaLevel(JSONNode _buf)
    {
        return new Zhenfa.CfgZhenfaLevel(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级经验
    /// </summary>
    public readonly int LvExp;
    /// <summary>
    /// 自身修炼值/秒
    /// </summary>
    public readonly int ZhanfaBaseExp;
    /// <summary>
    /// 增益-基础属性
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> BaseAttrValue;
    /// <summary>
    /// 解锁阵法组
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 虚弱时间，秒
    /// </summary>
    public readonly int ZhenfaRecoverTime;
    /// <summary>
    /// 被击杀对方阵法增加经验
    /// </summary>
    public readonly int KillZhenfaExp;
   
    public const int __ID__ = -1759125910;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BaseAttrValue) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "lvExp:" + LvExp + ","
        + "ZhanfaBaseExp:" + ZhanfaBaseExp + ","
        + "baseAttrValue:" + Luban.StringUtil.CollectionToString(BaseAttrValue) + ","
        + "reward:" + Reward + ","
        + "ZhenfaRecoverTime:" + ZhenfaRecoverTime + ","
        + "killZhenfaExp:" + KillZhenfaExp + ","
        + "}";
    }
}

}

