
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Zhenfa
{
public partial class TbZhenfaGroup
{
    private readonly System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaGroup> _dataMap;
    private readonly System.Collections.Generic.List<Zhenfa.CfgZhenfaGroup> _dataList;
    
    public TbZhenfaGroup(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaGroup>();
        _dataList = new System.Collections.Generic.List<Zhenfa.CfgZhenfaGroup>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Zhenfa.CfgZhenfaGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Zhenfa.CfgZhenfaGroup.DeserializeCfgZhenfaGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<Zhenfa.CfgZhenfaGroup> DataList => _dataList;

    public Zhenfa.CfgZhenfaGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Zhenfa.CfgZhenfaGroup Get(int key) => _dataMap[key];
    public Zhenfa.CfgZhenfaGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

