
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Zhenfa
{
public partial class TbZhenfaMain
{
    private readonly System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaMain> _dataMap;
    private readonly System.Collections.Generic.List<Zhenfa.CfgZhenfaMain> _dataList;
    
    public TbZhenfaMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaMain>();
        _dataList = new System.Collections.Generic.List<Zhenfa.CfgZhenfaMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Zhenfa.CfgZhenfaMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Zhenfa.CfgZhenfaMain.DeserializeCfgZhenfaMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.UnitID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Zhenfa.CfgZhenfaMain> DataList => _dataList;

    public Zhenfa.CfgZhenfaMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Zhenfa.CfgZhenfaMain Get(int key) => _dataMap[key];
    public Zhenfa.CfgZhenfaMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

