
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Pet
{
public sealed partial class CfgPetDecompose : Luban.BeanBase
{
    public CfgPetDecompose(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["decompose"]; if(!__json0.IsArray) { throw new SerializationException(); } Decompose = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Decompose.Add(__v0); }   }
    }

    public static CfgPetDecompose DeserializeCfgPetDecompose(JSONNode _buf)
    {
        return new Pet.CfgPetDecompose(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 分解奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Decompose;
   
    public const int __ID__ = -818998521;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Decompose) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "decompose:" + Luban.StringUtil.CollectionToString(Decompose) + ","
        + "}";
    }
}

}

