
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Pet
{
public sealed partial class CfgPetMain : Luban.BeanBase
{
    public CfgPetMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["sort"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { var __json0 = _buf["compose"]; if(!__json0.IsArray) { throw new SerializationException(); } Compose = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Compose.Add(__v0); }   }
        { var __json0 = _buf["specialEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SpecialEffect = new System.Collections.Generic.List<Property.PropertyData>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Property.PropertyData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Property.PropertyData.DeserializePropertyData(__e0);  }  SpecialEffect.Add(__v0); }   }
        { if(!_buf["convertCoefficient"].IsNumber) { throw new SerializationException(); }  ConvertCoefficient = _buf["convertCoefficient"]; }
        { var __json0 = _buf["advanceCost"]; if(!__json0.IsArray) { throw new SerializationException(); } AdvanceCost = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  AdvanceCost.Add(__v0); }   }
        { if(!_buf["advancePet"].IsNumber) { throw new SerializationException(); }  AdvancePet = _buf["advancePet"]; }
        { var __json0 = _buf["buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } Buffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buffs.Add(__v0); }   }
        { if(!_buf["animation"].IsString) { throw new SerializationException(); }  Animation = _buf["animation"]; }
        { if(!_buf["fx"].IsString) { throw new SerializationException(); }  Fx = _buf["fx"]; }
        { if(!_buf["nameRich"].IsString) { throw new SerializationException(); }  NameRich = _buf["nameRich"]; }
    }

    public static CfgPetMain DeserializeCfgPetMain(JSONNode _buf)
    {
        return new Pet.CfgPetMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 宠物编号
    /// </summary>
    public readonly int Sort;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 合成消耗
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Compose;
    /// <summary>
    /// 增加属性类型
    /// </summary>
    public readonly System.Collections.Generic.List<Property.PropertyData> SpecialEffect;
    /// <summary>
    /// 共鸣系数
    /// </summary>
    public readonly float ConvertCoefficient;
    /// <summary>
    /// 进阶消耗
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> AdvanceCost;
    /// <summary>
    /// 进阶后解锁
    /// </summary>
    public readonly int AdvancePet;
    /// <summary>
    /// 效果id
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buffs;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> Buffs_Ref;
    /// <summary>
    /// 动画
    /// </summary>
    public readonly string Animation;
    /// <summary>
    /// 特效
    /// </summary>
    public readonly string Fx;
    /// <summary>
    /// 富文本
    /// </summary>
    public readonly string NameRich;
   
    public const int __ID__ = -176120093;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Compose) { _e?.ResolveRef(tables); }
        foreach (var _e in SpecialEffect) { _e?.ResolveRef(tables); }
        foreach (var _e in AdvanceCost) { _e?.ResolveRef(tables); }
        Buffs_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in Buffs) { Buffs_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "sort:" + Sort + ","
        + "quality:" + Quality + ","
        + "compose:" + Luban.StringUtil.CollectionToString(Compose) + ","
        + "specialEffect:" + Luban.StringUtil.CollectionToString(SpecialEffect) + ","
        + "convertCoefficient:" + ConvertCoefficient + ","
        + "advanceCost:" + Luban.StringUtil.CollectionToString(AdvanceCost) + ","
        + "advancePet:" + AdvancePet + ","
        + "buffs:" + Luban.StringUtil.CollectionToString(Buffs) + ","
        + "animation:" + Animation + ","
        + "fx:" + Fx + ","
        + "nameRich:" + NameRich + ","
        + "}";
    }
}

}

