
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Pet
{
public partial class TbPetMain
{
    private readonly System.Collections.Generic.Dictionary<int, Pet.CfgPetMain> _dataMap;
    private readonly System.Collections.Generic.List<Pet.CfgPetMain> _dataList;
    
    public TbPetMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Pet.CfgPetMain>();
        _dataList = new System.Collections.Generic.List<Pet.CfgPetMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Pet.CfgPetMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Pet.CfgPetMain.DeserializeCfgPetMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Pet.CfgPetMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Pet.CfgPetMain> DataList => _dataList;

    public Pet.CfgPetMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Pet.CfgPetMain Get(int key) => _dataMap[key];
    public Pet.CfgPetMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

