
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum ArmorType
    {
        /// <summary>
        /// 均衡
        /// </summary>
        Balanced = 1,
        /// <summary>
        /// 裸形
        /// </summary>
        Naked_Form = 2,
        /// <summary>
        /// 畸刺
        /// </summary>
        Abnormal_Spur = 3,
        /// <summary>
        /// 邪诡
        /// </summary>
        Evil = 4,
    }

} 

