
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum ArmType
    {
        /// <summary>
        /// 坦克
        /// </summary>
        Tank = 1,
        /// <summary>
        /// 战士
        /// </summary>
        Soldier = 2,
        /// <summary>
        /// 射手
        /// </summary>
        Shooter = 3,
        /// <summary>
        /// 辅助
        /// </summary>
        Assist = 4,
    }

} 

