
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum FormationPosType
    {
        /// <summary>
        /// 前排
        /// </summary>
        Front = 0,
        /// <summary>
        /// 后排
        /// </summary>
        Back = 1,
    }

} 

