
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum Quality
    {
        /// <summary>
        /// N卡
        /// </summary>
        N = 1,
        /// <summary>
        /// R卡
        /// </summary>
        R = 2,
        /// <summary>
        /// SR卡
        /// </summary>
        SR = 3,
        /// <summary>
        /// SSR卡
        /// </summary>
        SSR = 4,
    }

} 

