
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    [System.Flags]
    public enum UnitActionType
    {
        /// <summary>
        /// none
        /// </summary>
        None = 0,
        /// <summary>
        /// 防守
        /// </summary>
        Defend = 1,
        /// <summary>
        /// 入侵
        /// </summary>
        Invade = 2,
        /// <summary>
        /// 协防
        /// </summary>
        Assist = 3,
        /// <summary>
        /// 红
        /// </summary>
        Red = 4,
        /// <summary>
        /// 蓝
        /// </summary>
        Blue = 5,
        /// <summary>
        /// 挑战
        /// </summary>
        Challenge = 6,
        /// <summary>
        /// 访客
        /// </summary>
        Visit = 7,
    }

} 

