
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.CampWar
{
public partial class CampWarRankReward
{
    private readonly System.Collections.Generic.Dictionary<int, CampWar.CfgCampWarRankReward> _dataMap;
    private readonly System.Collections.Generic.List<CampWar.CfgCampWarRankReward> _dataList;
    
    public CampWarRankReward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CampWar.CfgCampWarRankReward>();
        _dataList = new System.Collections.Generic.List<CampWar.CfgCampWarRankReward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CampWar.CfgCampWarRankReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CampWar.CfgCampWarRankReward.DeserializeCfgCampWarRankReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CampWar.CfgCampWarRankReward> DataMap => _dataMap;
    public System.Collections.Generic.List<CampWar.CfgCampWarRankReward> DataList => _dataList;

    public CampWar.CfgCampWarRankReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CampWar.CfgCampWarRankReward Get(int key) => _dataMap[key];
    public CampWar.CfgCampWarRankReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

