
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.CampWar
{
public partial class CampWarUnit
{
    private readonly System.Collections.Generic.Dictionary<int, CampWar.CfgRankCampWarUnit> _dataMap;
    private readonly System.Collections.Generic.List<CampWar.CfgRankCampWarUnit> _dataList;
    
    public CampWarUnit(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CampWar.CfgRankCampWarUnit>();
        _dataList = new System.Collections.Generic.List<CampWar.CfgRankCampWarUnit>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CampWar.CfgRankCampWarUnit _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CampWar.CfgRankCampWarUnit.DeserializeCfgRankCampWarUnit(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CampWar.CfgRankCampWarUnit> DataMap => _dataMap;
    public System.Collections.Generic.List<CampWar.CfgRankCampWarUnit> DataList => _dataList;

    public CampWar.CfgRankCampWarUnit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CampWar.CfgRankCampWarUnit Get(int key) => _dataMap[key];
    public CampWar.CfgRankCampWarUnit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

