
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.CampWar
{
public sealed partial class CfgCampWarGift : Luban.BeanBase
{
    public CfgCampWarGift(JSONNode _buf) 
    {
        { if(!_buf["giftID"].IsNumber) { throw new SerializationException(); }  GiftID = _buf["giftID"]; }
        { if(!_buf["campWarScore"].IsNumber) { throw new SerializationException(); }  CampWarScore = _buf["campWarScore"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["callUnitID"].IsNumber) { throw new SerializationException(); }  CallUnitID = _buf["callUnitID"]; }
        { if(!_buf["callUnitTime"].IsNumber) { throw new SerializationException(); }  CallUnitTime = _buf["callUnitTime"]; }
        { if(!_buf["noticeID"].IsNumber) { throw new SerializationException(); }  NoticeID = _buf["noticeID"]; }
    }

    public static CfgCampWarGift DeserializeCfgCampWarGift(JSONNode _buf)
    {
        return new CampWar.CfgCampWarGift(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int GiftID;
    /// <summary>
    /// 论道积分
    /// </summary>
    public readonly int CampWarScore;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 召唤单位ID
    /// </summary>
    public readonly int CallUnitID;
    /// <summary>
    /// 召唤单位存在时间，秒
    /// </summary>
    public readonly int CallUnitTime;
    /// <summary>
    /// 弹幕id
    /// </summary>
    public readonly int NoticeID;
   
    public const int __ID__ = -1963540518;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "giftID:" + GiftID + ","
        + "campWarScore:" + CampWarScore + ","
        + "damage:" + Damage + ","
        + "callUnitID:" + CallUnitID + ","
        + "callUnitTime:" + CallUnitTime + ","
        + "noticeID:" + NoticeID + ","
        + "}";
    }
}

}

