
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.CampWar
{
public sealed partial class CfgRankCampWarUnit : Luban.BeanBase
{
    public CfgRankCampWarUnit(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Shield"].IsNumber) { throw new SerializationException(); }  Shield = _buf["Shield"]; }
        { if(!_buf["skill"].IsNumber) { throw new SerializationException(); }  Skill = _buf["skill"]; }
    }

    public static CfgRankCampWarUnit DeserializeCfgRankCampWarUnit(JSONNode _buf)
    {
        return new CampWar.CfgRankCampWarUnit(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 护盾值
    /// </summary>
    public readonly int Shield;
    /// <summary>
    /// 播放技能
    /// </summary>
    public readonly int Skill;
   
    public const int __ID__ = 378867426;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Shield:" + Shield + ","
        + "skill:" + Skill + ","
        + "}";
    }
}

}

