
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Dungeon
{
public sealed partial class CfgDungeonTotal : Luban.BeanBase
{
    public CfgDungeonTotal(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["dungeonNum"].IsNumber) { throw new SerializationException(); }  DungeonNum = _buf["dungeonNum"]; }
        { if(!_buf["countdown"].IsNumber) { throw new SerializationException(); }  Countdown = _buf["countdown"]; }
    }

    public static CfgDungeonTotal DeserializeCfgDungeonTotal(JSONNode _buf)
    {
        return new Dungeon.CfgDungeonTotal(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 关卡数量
    /// </summary>
    public readonly int DungeonNum;
    /// <summary>
    /// 倒计时
    /// </summary>
    public readonly int Countdown;
   
    public const int __ID__ = 961652666;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "dungeonNum:" + DungeonNum + ","
        + "countdown:" + Countdown + ","
        + "}";
    }
}

}

