
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Dungeon
{
public partial class TbDungeonMain
{
    private readonly System.Collections.Generic.Dictionary<int, Dungeon.CfgDungeonMain> _dataMap;
    private readonly System.Collections.Generic.List<Dungeon.CfgDungeonMain> _dataList;
    
    public TbDungeonMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Dungeon.CfgDungeonMain>();
        _dataList = new System.Collections.Generic.List<Dungeon.CfgDungeonMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Dungeon.CfgDungeonMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Dungeon.CfgDungeonMain.DeserializeCfgDungeonMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Dungeon.CfgDungeonMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Dungeon.CfgDungeonMain> DataList => _dataList;

    public Dungeon.CfgDungeonMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dungeon.CfgDungeonMain Get(int key) => _dataMap[key];
    public Dungeon.CfgDungeonMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

