
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.WorldBoss
{
public sealed partial class CfgWorldBossRankReward : Luban.BeanBase
{
    public CfgWorldBossRankReward(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["group"].IsNumber) { throw new SerializationException(); }  Group = _buf["group"]; }
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["rank"]; }
        { var __json0 = _buf["rewardProp"]; if(!__json0.IsArray) { throw new SerializationException(); } RewardProp = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  RewardProp.Add(__v0); }   }
        { if(!_buf["drop"].IsString) { throw new SerializationException(); }  Drop = _buf["drop"]; }
    }

    public static CfgWorldBossRankReward DeserializeCfgWorldBossRankReward(JSONNode _buf)
    {
        return new WorldBoss.CfgWorldBossRankReward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 境界分组
    /// </summary>
    public readonly int Group;
    /// <summary>
    /// 伤害排名
    /// </summary>
    public readonly int Rank;
    /// <summary>
    /// 奖励物品
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> RewardProp;
    /// <summary>
    /// 掉落
    /// </summary>
    public readonly string Drop;
   
    public const int __ID__ = 466355173;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in RewardProp) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "group:" + Group + ","
        + "rank:" + Rank + ","
        + "rewardProp:" + Luban.StringUtil.CollectionToString(RewardProp) + ","
        + "drop:" + Drop + ","
        + "}";
    }
}

}

