
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.WorldBoss
{
public sealed partial class CfgWorldBossMain : Luban.BeanBase
{
    public CfgWorldBossMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["MonsterType"].IsNumber) { throw new SerializationException(); }  MonsterType = (Monster.Type)_buf["MonsterType"].AsInt; }
        { if(!_buf["unitID"].IsNumber) { throw new SerializationException(); }  UnitID = _buf["unitID"]; }
        { if(!_buf["bossLevel"].IsNumber) { throw new SerializationException(); }  BossLevel = _buf["bossLevel"]; }
        { if(!_buf["stageID"].IsNumber) { throw new SerializationException(); }  StageID = _buf["stageID"]; }
        { if(!_buf["avatar"].IsNumber) { throw new SerializationException(); }  Avatar = _buf["avatar"]; }
    }

    public static CfgWorldBossMain DeserializeCfgWorldBossMain(JSONNode _buf)
    {
        return new WorldBoss.CfgWorldBossMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 怪物类型
    /// </summary>
    public readonly Monster.Type MonsterType;
    /// <summary>
    /// 单位id
    /// </summary>
    public readonly int UnitID;
    /// <summary>
    /// BOSS等级
    /// </summary>
    public readonly int BossLevel;
    /// <summary>
    /// 出现的关卡ID
    /// </summary>
    public readonly int StageID;
    /// <summary>
    /// 模型id
    /// </summary>
    public readonly int Avatar;
   
    public const int __ID__ = -949671261;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "MonsterType:" + MonsterType + ","
        + "unitID:" + UnitID + ","
        + "bossLevel:" + BossLevel + ","
        + "stageID:" + StageID + ","
        + "avatar:" + Avatar + ","
        + "}";
    }
}

}

