
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.WorldBoss
{
public partial class TbWorldBossMain
{
    private readonly System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossMain> _dataMap;
    private readonly System.Collections.Generic.List<WorldBoss.CfgWorldBossMain> _dataList;
    
    public TbWorldBossMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossMain>();
        _dataList = new System.Collections.Generic.List<WorldBoss.CfgWorldBossMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WorldBoss.CfgWorldBossMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = WorldBoss.CfgWorldBossMain.DeserializeCfgWorldBossMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossMain> DataMap => _dataMap;
    public System.Collections.Generic.List<WorldBoss.CfgWorldBossMain> DataList => _dataList;

    public WorldBoss.CfgWorldBossMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WorldBoss.CfgWorldBossMain Get(int key) => _dataMap[key];
    public WorldBoss.CfgWorldBossMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

