
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Item
{
public sealed partial class CfgItemShard : Luban.BeanBase
{
    public CfgItemShard(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["composeMax"].IsNumber) { throw new SerializationException(); }  ComposeMax = _buf["composeMax"]; }
        { if(!_buf["shardNum"].IsNumber) { throw new SerializationException(); }  ShardNum = _buf["shardNum"]; }
        { var __json0 = _buf["reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Reward.Add(__v0); }   }
        { if(!_buf["drop"].IsNumber) { throw new SerializationException(); }  Drop = _buf["drop"]; }
    }

    public static CfgItemShard DeserializeCfgItemShard(JSONNode _buf)
    {
        return new Item.CfgItemShard(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最多合成数量
    /// </summary>
    public readonly int ComposeMax;
    /// <summary>
    /// 需要数量
    /// </summary>
    public readonly int ShardNum;
    /// <summary>
    /// 获得奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Reward;
    /// <summary>
    /// 随机奖励
    /// </summary>
    public readonly int Drop;
   
    public const int __ID__ = 1214366594;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "composeMax:" + ComposeMax + ","
        + "shardNum:" + ShardNum + ","
        + "reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "drop:" + Drop + ","
        + "}";
    }
}

}

