
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Item
{
public sealed partial class CfgItemRes : Luban.BeanBase
{
    public CfgItemRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["bigIcon"].IsString) { throw new SerializationException(); }  BigIcon = _buf["bigIcon"]; }
    }

    public static CfgItemRes DeserializeCfgItemRes(JSONNode _buf)
    {
        return new Item.CfgItemRes(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具图标128*128
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 道具图标512*512
    /// </summary>
    public readonly string BigIcon;
   
    public const int __ID__ = -923876028;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "icon:" + Icon + ","
        + "bigIcon:" + BigIcon + ","
        + "}";
    }
}

}

