
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Item
{
public partial class TbItemRes
{
    private readonly System.Collections.Generic.Dictionary<int, Item.CfgItemRes> _dataMap;
    private readonly System.Collections.Generic.List<Item.CfgItemRes> _dataList;
    
    public TbItemRes(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.CfgItemRes>();
        _dataList = new System.Collections.Generic.List<Item.CfgItemRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Item.CfgItemRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Item.CfgItemRes.DeserializeCfgItemRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Item.CfgItemRes> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.CfgItemRes> DataList => _dataList;

    public Item.CfgItemRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.CfgItemRes Get(int key) => _dataMap[key];
    public Item.CfgItemRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

