
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Item
{
public partial class TbItemMain
{
    private readonly System.Collections.Generic.Dictionary<int, Item.CfgItemMain> _dataMap;
    private readonly System.Collections.Generic.List<Item.CfgItemMain> _dataList;
    
    public TbItemMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.CfgItemMain>();
        _dataList = new System.Collections.Generic.List<Item.CfgItemMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Item.CfgItemMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Item.CfgItemMain.DeserializeCfgItemMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Item.CfgItemMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.CfgItemMain> DataList => _dataList;

    public Item.CfgItemMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.CfgItemMain Get(int key) => _dataMap[key];
    public Item.CfgItemMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

