
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Item
{ 
    public enum Type
    {
        /// <summary>
        /// 货币
        /// </summary>
        Currency = 1,
        /// <summary>
        /// 增加属性道具
        /// </summary>
        Attribute = 2,
        /// <summary>
        /// 增加突破概率道具
        /// </summary>
        Break = 3,
        /// <summary>
        /// 增加修炼经验道具
        /// </summary>
        Exp = 4,
        /// <summary>
        /// 宝箱类
        /// </summary>
        Box = 5,
        /// <summary>
        /// 常规道具
        /// </summary>
        common = 6,
        /// <summary>
        /// 功法书
        /// </summary>
        Skill = 7,
        /// <summary>
        /// 皮肤
        /// </summary>
        Avatar = 8,
        /// <summary>
        /// 法宝
        /// </summary>
        Equip = 9,
        /// <summary>
        /// 坐骑
        /// </summary>
        Mount = 10,
        /// <summary>
        /// 宠物
        /// </summary>
        Pet = 11,
        /// <summary>
        /// 计数类礼盒
        /// </summary>
        CountBox = 12,
        /// <summary>
        /// 礼物了道具
        /// </summary>
        Gift = 13,
        /// <summary>
        /// 复活道具
        /// </summary>
        Revive = 14,
        /// <summary>
        /// 宠物属性道具
        /// </summary>
        PetAttribute = 15,
        /// <summary>
        /// 宠物装备
        /// </summary>
        PetEquip = 16,
        /// <summary>
        /// 称号
        /// </summary>
        Title = 17,
        /// <summary>
        /// 碎片道具
        /// </summary>
        Shard = 18,
        /// <summary>
        /// 灵宝
        /// </summary>
        Treasure = 19,
    }

} 

