
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.PetEquip
{ 
    public enum Type
    {
        /// <summary>
        /// 进攻宠物装备
        /// </summary>
        AttackPetEquip = 1,
        /// <summary>
        /// 防御宠物装备
        /// </summary>
        DefensePetEquip = 2,
    }

} 

