
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Boss
{
public sealed partial class CfgBossRankReward : Luban.BeanBase
{
    public CfgBossRankReward(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["stage"].IsNumber) { throw new SerializationException(); }  Stage = _buf["stage"]; }
        Stage_Ref = null;
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["rank"]; }
        { var __json0 = _buf["dropReward"]; if(!__json0.IsArray) { throw new SerializationException(); } DropReward = new System.Collections.Generic.List<Reward.DamageRank>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Reward.DamageRank __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Reward.DamageRank.DeserializeDamageRank(__e0);  }  DropReward.Add(__v0); }   }
    }

    public static CfgBossRankReward DeserializeCfgBossRankReward(JSONNode _buf)
    {
        return new Boss.CfgBossRankReward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// BOSSID
    /// </summary>
    public readonly int Stage;
    public Monster.CfgBossMain Stage_Ref;
    /// <summary>
    /// 伤害排名
    /// </summary>
    public readonly int Rank;
    /// <summary>
    /// 掉落id
    /// </summary>
    public readonly System.Collections.Generic.List<Reward.DamageRank> DropReward;
   
    public const int __ID__ = -943218933;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Stage_Ref = tables.TbBossMain.GetOrDefault(Stage);
        foreach (var _e in DropReward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "stage:" + Stage + ","
        + "rank:" + Rank + ","
        + "dropReward:" + Luban.StringUtil.CollectionToString(DropReward) + ","
        + "}";
    }
}

}

