
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Boss
{
public partial class TbBossCallNumReward
{
    private readonly System.Collections.Generic.Dictionary<int, Boss.CfgBossCallNumReward> _dataMap;
    private readonly System.Collections.Generic.List<Boss.CfgBossCallNumReward> _dataList;
    
    public TbBossCallNumReward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Boss.CfgBossCallNumReward>();
        _dataList = new System.Collections.Generic.List<Boss.CfgBossCallNumReward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Boss.CfgBossCallNumReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Boss.CfgBossCallNumReward.DeserializeCfgBossCallNumReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Boss.CfgBossCallNumReward> DataMap => _dataMap;
    public System.Collections.Generic.List<Boss.CfgBossCallNumReward> DataList => _dataList;

    public Boss.CfgBossCallNumReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Boss.CfgBossCallNumReward Get(int key) => _dataMap[key];
    public Boss.CfgBossCallNumReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

