
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Action
{
public partial class TbActionScoreMain
{
    private readonly System.Collections.Generic.Dictionary<int, Action.CfgActionScoreMain> _dataMap;
    private readonly System.Collections.Generic.List<Action.CfgActionScoreMain> _dataList;
    
    public TbActionScoreMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Action.CfgActionScoreMain>();
        _dataList = new System.Collections.Generic.List<Action.CfgActionScoreMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Action.CfgActionScoreMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Action.CfgActionScoreMain.DeserializeCfgActionScoreMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Action.CfgActionScoreMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Action.CfgActionScoreMain> DataList => _dataList;

    public Action.CfgActionScoreMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Action.CfgActionScoreMain Get(int key) => _dataMap[key];
    public Action.CfgActionScoreMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

