
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public sealed partial class CfgRewardDropGroup : Luban.BeanBase
{
    public CfgRewardDropGroup(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["dropGroupItem"]; if(!__json0.IsArray) { throw new SerializationException(); } DropGroupItem = new System.Collections.Generic.List<Reward.DropGroup>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Reward.DropGroup __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Reward.DropGroup.DeserializeDropGroup(__e0);  }  DropGroupItem.Add(__v0); }   }
    }

    public static CfgRewardDropGroup DeserializeCfgRewardDropGroup(JSONNode _buf)
    {
        return new Reward.CfgRewardDropGroup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 掉落项
    /// </summary>
    public readonly System.Collections.Generic.List<Reward.DropGroup> DropGroupItem;
   
    public const int __ID__ = 1566279292;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DropGroupItem) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dropGroupItem:" + Luban.StringUtil.CollectionToString(DropGroupItem) + ","
        + "}";
    }
}

}

