
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public sealed partial class CfgRewardDropBox : Luban.BeanBase
{
    public CfgRewardDropBox(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["itemID"].IsNumber) { throw new SerializationException(); }  ItemID = _buf["itemID"]; }
        { if(!_buf["openNum"].IsNumber) { throw new SerializationException(); }  OpenNum = _buf["openNum"]; }
        { var __json0 = _buf["Drop"]; if(!__json0.IsArray) { throw new SerializationException(); } Drop = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Drop.Add(__v0); }   }
    }

    public static CfgRewardDropBox DeserializeCfgRewardDropBox(JSONNode _buf)
    {
        return new Reward.CfgRewardDropBox(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int ItemID;
    /// <summary>
    /// 开启次数
    /// </summary>
    public readonly int OpenNum;
    /// <summary>
    /// 奖励掉落id
    /// </summary>
    public readonly System.Collections.Generic.List<int> Drop;
    public System.Collections.Generic.List<Reward.CfgRewardDrop> Drop_Ref;
   
    public const int __ID__ = -1343624952;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Drop_Ref = new System.Collections.Generic.List<Reward.CfgRewardDrop>();
        foreach (var _v in Drop) { Drop_Ref.Add(tables.TbRewardDrop.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemID:" + ItemID + ","
        + "openNum:" + OpenNum + ","
        + "Drop:" + Luban.StringUtil.CollectionToString(Drop) + ","
        + "}";
    }
}

}

