
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public sealed partial class DamageRank : Luban.BeanBase
{
    public DamageRank(JSONNode _buf) 
    {
        { if(!_buf["insightMin"].IsNumber) { throw new SerializationException(); }  InsightMin = _buf["insightMin"]; }
        { if(!_buf["insightMax"].IsNumber) { throw new SerializationException(); }  InsightMax = _buf["insightMax"]; }
        { if(!_buf["dropId"].IsNumber) { throw new SerializationException(); }  DropId = _buf["dropId"]; }
    }

    public static DamageRank DeserializeDamageRank(JSONNode _buf)
    {
        return new Reward.DamageRank(_buf);
    }

    /// <summary>
    /// 悟性最小值
    /// </summary>
    public readonly int InsightMin;
    /// <summary>
    /// 悟性最大值
    /// </summary>
    public readonly int InsightMax;
    /// <summary>
    /// 掉落id
    /// </summary>
    public readonly int DropId;
   
    public const int __ID__ = 886629466;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "insightMin:" + InsightMin + ","
        + "insightMax:" + InsightMax + ","
        + "dropId:" + DropId + ","
        + "}";
    }
}

}

