
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public sealed partial class DropGroup : Luban.BeanBase
{
    public DropGroup(JSONNode _buf) 
    {
        { if(!_buf["rate"].IsNumber) { throw new SerializationException(); }  Rate = _buf["rate"]; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["numMin"].IsNumber) { throw new SerializationException(); }  NumMin = _buf["numMin"]; }
        { if(!_buf["numMax"].IsNumber) { throw new SerializationException(); }  NumMax = _buf["numMax"]; }
    }

    public static DropGroup DeserializeDropGroup(JSONNode _buf)
    {
        return new Reward.DropGroup(_buf);
    }

    /// <summary>
    /// 概率，万分比
    /// </summary>
    public readonly int Rate;
    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最小数量
    /// </summary>
    public readonly int NumMin;
    /// <summary>
    /// 最大数量
    /// </summary>
    public readonly int NumMax;
   
    public const int __ID__ = -449844015;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "rate:" + Rate + ","
        + "id:" + Id + ","
        + "numMin:" + NumMin + ","
        + "numMax:" + NumMax + ","
        + "}";
    }
}

}

