
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Reward
{ 
    public enum Tag
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 必掉
        /// </summary>
        Default = 1,
        /// <summary>
        /// 首通
        /// </summary>
        First = 2,
        /// <summary>
        /// 星级
        /// </summary>
        Star = 3,
        /// <summary>
        /// 高概率
        /// </summary>
        High = 4,
        /// <summary>
        /// 低概率
        /// </summary>
        Middle = 5,
        /// <summary>
        /// 中概率
        /// </summary>
        Low = 6,
        /// <summary>
        /// 罕见
        /// </summary>
        Rare = 7,
    }

} 

