
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public partial class TbRewardDropGroup
{
    private readonly System.Collections.Generic.Dictionary<int, Reward.CfgRewardDropGroup> _dataMap;
    private readonly System.Collections.Generic.List<Reward.CfgRewardDropGroup> _dataList;
    
    public TbRewardDropGroup(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Reward.CfgRewardDropGroup>();
        _dataList = new System.Collections.Generic.List<Reward.CfgRewardDropGroup>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Reward.CfgRewardDropGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Reward.CfgRewardDropGroup.DeserializeCfgRewardDropGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Reward.CfgRewardDropGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<Reward.CfgRewardDropGroup> DataList => _dataList;

    public Reward.CfgRewardDropGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Reward.CfgRewardDropGroup Get(int key) => _dataMap[key];
    public Reward.CfgRewardDropGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

