
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.WorldBoss
{
public sealed partial class CfgWorldBossDamageReward : Luban.BeanBase
{
    public CfgWorldBossDamageReward(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["group"].IsNumber) { throw new SerializationException(); }  Group = _buf["group"]; }
        { if(!_buf["dropReward"].IsNumber) { throw new SerializationException(); }  DropReward = _buf["dropReward"]; }
        { if(!_buf["notice"].IsNumber) { throw new SerializationException(); }  Notice = _buf["notice"]; }
    }

    public static CfgWorldBossDamageReward DeserializeCfgWorldBossDamageReward(JSONNode _buf)
    {
        return new WorldBoss.CfgWorldBossDamageReward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 伤害值
    /// </summary>
    public readonly double Group;
    /// <summary>
    /// 掉落id
    /// </summary>
    public readonly int DropReward;
    /// <summary>
    /// 公告id
    /// </summary>
    public readonly int Notice;
   
    public const int __ID__ = 1958597224;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "group:" + Group + ","
        + "dropReward:" + DropReward + ","
        + "notice:" + Notice + ","
        + "}";
    }
}

}

