
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.WorldBoss
{
public partial class TbWorldBossDamageReward
{
    private readonly System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossDamageReward> _dataMap;
    private readonly System.Collections.Generic.List<WorldBoss.CfgWorldBossDamageReward> _dataList;
    
    public TbWorldBossDamageReward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossDamageReward>();
        _dataList = new System.Collections.Generic.List<WorldBoss.CfgWorldBossDamageReward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WorldBoss.CfgWorldBossDamageReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = WorldBoss.CfgWorldBossDamageReward.DeserializeCfgWorldBossDamageReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossDamageReward> DataMap => _dataMap;
    public System.Collections.Generic.List<WorldBoss.CfgWorldBossDamageReward> DataList => _dataList;

    public WorldBoss.CfgWorldBossDamageReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WorldBoss.CfgWorldBossDamageReward Get(int key) => _dataMap[key];
    public WorldBoss.CfgWorldBossDamageReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

