
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.WorldBoss
{
public partial class TbWorldBossRankReward
{
    private readonly System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossRankReward> _dataMap;
    private readonly System.Collections.Generic.List<WorldBoss.CfgWorldBossRankReward> _dataList;
    
    public TbWorldBossRankReward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossRankReward>();
        _dataList = new System.Collections.Generic.List<WorldBoss.CfgWorldBossRankReward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WorldBoss.CfgWorldBossRankReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = WorldBoss.CfgWorldBossRankReward.DeserializeCfgWorldBossRankReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WorldBoss.CfgWorldBossRankReward> DataMap => _dataMap;
    public System.Collections.Generic.List<WorldBoss.CfgWorldBossRankReward> DataList => _dataList;

    public WorldBoss.CfgWorldBossRankReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WorldBoss.CfgWorldBossRankReward Get(int key) => _dataMap[key];
    public WorldBoss.CfgWorldBossRankReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

