
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionChangeHpData : Buff.ActionData
{
    public ActionChangeHpData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
        { if(!_buf["minPctValue"].IsNumber) { throw new SerializationException(); }  MinPctValue = _buf["minPctValue"]; }
        { if(!_buf["maxPctValue"].IsNumber) { throw new SerializationException(); }  MaxPctValue = _buf["maxPctValue"]; }
    }

    public static ActionChangeHpData DeserializeActionChangeHpData(JSONNode _buf)
    {
        return new Buff.ActionChangeHpData(_buf);
    }

    /// <summary>
    /// 恢复值(万分比)
    /// </summary>
    public readonly long PctValue;
    /// <summary>
    /// 固定值
    /// </summary>
    public readonly long FixedValue;
    /// <summary>
    /// 下限值(万分比)
    /// </summary>
    public readonly long MinPctValue;
    /// <summary>
    /// 上限值(万分比)
    /// </summary>
    public readonly long MaxPctValue;
   
    public const int __ID__ = 1752477555;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "pctValue:" + PctValue + ","
        + "fixedValue:" + FixedValue + ","
        + "minPctValue:" + MinPctValue + ","
        + "maxPctValue:" + MaxPctValue + ","
        + "}";
    }
}

}

