
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionUnitLifeHealData : Buff.ActionData
{
    public ActionUnitLifeHealData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["healType"].IsNumber) { throw new SerializationException(); }  HealType = (Battle.HealType)_buf["healType"].AsInt; }
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
    }

    public static ActionUnitLifeHealData DeserializeActionUnitLifeHealData(JSONNode _buf)
    {
        return new Buff.ActionUnitLifeHealData(_buf);
    }

    /// <summary>
    /// 治疗类型
    /// </summary>
    public readonly Battle.HealType HealType;
    /// <summary>
    /// 恢复值(万分比)
    /// </summary>
    public readonly long PctValue;
    /// <summary>
    /// 固定值
    /// </summary>
    public readonly long FixedValue;
   
    public const int __ID__ = 1831736003;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "healType:" + HealType + ","
        + "pctValue:" + PctValue + ","
        + "fixedValue:" + FixedValue + ","
        + "}";
    }
}

}

