
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionDamageConversionAttrData : Buff.ActionData
{
    public ActionDamageConversionAttrData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["targetDamageType"].IsNumber) { throw new SerializationException(); }  TargetDamageType = (Unit.UnitDamageType)_buf["targetDamageType"].AsInt; }
        { if(!_buf["targetPropertyType"].IsNumber) { throw new SerializationException(); }  TargetPropertyType = (Battle.PropertyType)_buf["targetPropertyType"].AsInt; }
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
    }

    public static ActionDamageConversionAttrData DeserializeActionDamageConversionAttrData(JSONNode _buf)
    {
        return new Buff.ActionDamageConversionAttrData(_buf);
    }

    /// <summary>
    /// 产生或受到伤害类型
    /// </summary>
    public readonly Unit.UnitDamageType TargetDamageType;
    /// <summary>
    /// 转换目标属性类型
    /// </summary>
    public readonly Battle.PropertyType TargetPropertyType;
    /// <summary>
    /// 万分比
    /// </summary>
    public readonly long PctValue;
    /// <summary>
    /// 固定值
    /// </summary>
    public readonly long FixedValue;
   
    public const int __ID__ = -793063535;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "targetDamageType:" + TargetDamageType + ","
        + "targetPropertyType:" + TargetPropertyType + ","
        + "pctValue:" + PctValue + ","
        + "fixedValue:" + FixedValue + ","
        + "}";
    }
}

}

