
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionChangeShieldData : Buff.ActionData
{
    public ActionChangeShieldData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["propertySource"].IsNumber) { throw new SerializationException(); }  PropertySource = (Battle.PropertyType)_buf["propertySource"].AsInt; }
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
        { if(!_buf["fixedValue"].IsNumber) { throw new SerializationException(); }  FixedValue = _buf["fixedValue"]; }
    }

    public static ActionChangeShieldData DeserializeActionChangeShieldData(JSONNode _buf)
    {
        return new Buff.ActionChangeShieldData(_buf);
    }

    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly Battle.PropertyType PropertySource;
    /// <summary>
    /// 恢复值(万分比)
    /// </summary>
    public readonly long PctValue;
    /// <summary>
    /// 固定值
    /// </summary>
    public readonly long FixedValue;
   
    public const int __ID__ = 1571188948;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "propertySource:" + PropertySource + ","
        + "pctValue:" + PctValue + ","
        + "fixedValue:" + FixedValue + ","
        + "}";
    }
}

}

