
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class ActionUnitRespawnData : Buff.ActionData
{
    public ActionUnitRespawnData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["pctValue"].IsNumber) { throw new SerializationException(); }  PctValue = _buf["pctValue"]; }
    }

    public static ActionUnitRespawnData DeserializeActionUnitRespawnData(JSONNode _buf)
    {
        return new Buff.ActionUnitRespawnData(_buf);
    }

    /// <summary>
    /// 重生概率
    /// </summary>
    public readonly long PctValue;
   
    public const int __ID__ = -1247114147;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetSource:" + TargetSource + ","
        + "pctValue:" + PctValue + ","
        + "}";
    }
}

}

