
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Buff
{
public sealed partial class CondPeriodicActivateData : Battle.ConditionData
{
    public CondPeriodicActivateData(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["intervalTime"].IsNumber) { throw new SerializationException(); }  IntervalTime = _buf["intervalTime"]; }
    }

    public static CondPeriodicActivateData DeserializeCondPeriodicActivateData(JSONNode _buf)
    {
        return new Buff.CondPeriodicActivateData(_buf);
    }

    /// <summary>
    /// 间隔时间(ms)
    /// </summary>
    public readonly int IntervalTime;
   
    public const int __ID__ = -1821971211;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "intervalTime:" + IntervalTime + ","
        + "}";
    }
}

}

