
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public sealed partial class CfgLanguage : Luban.BeanBase
{
    public CfgLanguage(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["giftType"].IsNumber) { throw new SerializationException(); }  GiftType = _buf["giftType"]; }
        { if(!_buf["showActivityPos"].IsBoolean) { throw new SerializationException(); }  ShowActivityPos = _buf["showActivityPos"]; }
        { if(!_buf["showMainPos"].IsBoolean) { throw new SerializationException(); }  ShowMainPos = _buf["showMainPos"]; }
        { if(!_buf["showSceneMiddlePos"].IsBoolean) { throw new SerializationException(); }  ShowSceneMiddlePos = _buf["showSceneMiddlePos"]; }
        { if(!_buf["showDanmaku"].IsObject) { throw new SerializationException(); }  ShowDanmaku = Message.DanmakuData.DeserializeDanmakuData(_buf["showDanmaku"]);  }
        { if(!_buf["content"].IsString) { throw new SerializationException(); }  Content = _buf["content"]; }
        { if(!_buf["paramType"].IsNumber) { throw new SerializationException(); }  ParamType = _buf["paramType"]; }
        { var __json0 = _buf["param"]; if(!__json0.IsArray) { throw new SerializationException(); } Param = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Param.Add(__v0); }   }
    }

    public static CfgLanguage DeserializeCfgLanguage(JSONNode _buf)
    {
        return new Table.CfgLanguage(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 弹幕类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 礼物公告
    /// </summary>
    public readonly int GiftType;
    /// <summary>
    /// 显示在活动倒计时位置
    /// </summary>
    public readonly bool ShowActivityPos;
    /// <summary>
    /// 显示在挂机信息栏
    /// </summary>
    public readonly bool ShowMainPos;
    /// <summary>
    /// 显示在场景中间
    /// </summary>
    public readonly bool ShowSceneMiddlePos;
    public readonly Message.DanmakuData ShowDanmaku;
    /// <summary>
    /// 文本内容
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 参数类型
    /// </summary>
    public readonly int ParamType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> Param;
   
    public const int __ID__ = -1283298948;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ShowDanmaku?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "giftType:" + GiftType + ","
        + "showActivityPos:" + ShowActivityPos + ","
        + "showMainPos:" + ShowMainPos + ","
        + "showSceneMiddlePos:" + ShowSceneMiddlePos + ","
        + "showDanmaku:" + ShowDanmaku + ","
        + "content:" + Content + ","
        + "paramType:" + ParamType + ","
        + "param:" + Luban.StringUtil.CollectionToString(Param) + ","
        + "}";
    }
}

}

