
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public partial class TbAddLikesMain
{
    private readonly System.Collections.Generic.Dictionary<int, Table.CfgAddLikesMain> _dataMap;
    private readonly System.Collections.Generic.List<Table.CfgAddLikesMain> _dataList;
    
    public TbAddLikesMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Table.CfgAddLikesMain>();
        _dataList = new System.Collections.Generic.List<Table.CfgAddLikesMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Table.CfgAddLikesMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Table.CfgAddLikesMain.DeserializeCfgAddLikesMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Table.CfgAddLikesMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Table.CfgAddLikesMain> DataList => _dataList;

    public Table.CfgAddLikesMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Table.CfgAddLikesMain Get(int key) => _dataMap[key];
    public Table.CfgAddLikesMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

