
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Table
{
public partial class TbTaskMain
{
    private readonly System.Collections.Generic.Dictionary<int, Table.CfgTaskMain> _dataMap;
    private readonly System.Collections.Generic.List<Table.CfgTaskMain> _dataList;
    
    public TbTaskMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Table.CfgTaskMain>();
        _dataList = new System.Collections.Generic.List<Table.CfgTaskMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Table.CfgTaskMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Table.CfgTaskMain.DeserializeCfgTaskMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Table.CfgTaskMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Table.CfgTaskMain> DataList => _dataList;

    public Table.CfgTaskMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Table.CfgTaskMain Get(int key) => _dataMap[key];
    public Table.CfgTaskMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

