
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Condition
{ 
    public enum CompareMode
    {
        /// <summary>
        /// &gt;
        /// </summary>
        Value1 = 0,
        /// <summary>
        /// =
        /// </summary>
        Value2 = 1,
        /// <summary>
        /// &lt;
        /// </summary>
        Value3 = 2,
        /// <summary>
        /// &gt;=
        /// </summary>
        Value4 = 3,
        /// <summary>
        /// &lt;=
        /// </summary>
        Value5 = 4,
    }

} 

