
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Zhenfa
{
public sealed partial class CfgZhenfaMain : Luban.BeanBase
{
    public CfgZhenfaMain(JSONNode _buf) 
    {
        { if(!_buf["unitID"].IsNumber) { throw new SerializationException(); }  UnitID = _buf["unitID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["group"].IsNumber) { throw new SerializationException(); }  Group = _buf["group"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { var __json0 = _buf["buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } Buffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buffs.Add(__v0); }   }
        { if(!_buf["buffDesc"].IsString) { throw new SerializationException(); }  BuffDesc = _buf["buffDesc"]; }
    }

    public static CfgZhenfaMain DeserializeCfgZhenfaMain(JSONNode _buf)
    {
        return new Zhenfa.CfgZhenfaMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int UnitID;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 阵法组
    /// </summary>
    public readonly int Group;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 阵法给宗门成员附加的buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buffs;
    public System.Collections.Generic.List<Battle.CfgBattleBuffData> Buffs_Ref;
    /// <summary>
    /// buff描述
    /// </summary>
    public readonly string BuffDesc;
   
    public const int __ID__ = -1580741101;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Buffs_Ref = new System.Collections.Generic.List<Battle.CfgBattleBuffData>();
        foreach (var _v in Buffs) { Buffs_Ref.Add(tables.TbBuffMain.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "unitID:" + UnitID + ","
        + "name:" + Name + ","
        + "group:" + Group + ","
        + "level:" + Level + ","
        + "buffs:" + Luban.StringUtil.CollectionToString(Buffs) + ","
        + "buffDesc:" + BuffDesc + ","
        + "}";
    }
}

}

