
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Zhenfa
{
public partial class TbZhenfaLevel
{
    private readonly System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaLevel> _dataMap;
    private readonly System.Collections.Generic.List<Zhenfa.CfgZhenfaLevel> _dataList;
    
    public TbZhenfaLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaLevel>();
        _dataList = new System.Collections.Generic.List<Zhenfa.CfgZhenfaLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Zhenfa.CfgZhenfaLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Zhenfa.CfgZhenfaLevel.DeserializeCfgZhenfaLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Zhenfa.CfgZhenfaLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<Zhenfa.CfgZhenfaLevel> DataList => _dataList;

    public Zhenfa.CfgZhenfaLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Zhenfa.CfgZhenfaLevel Get(int key) => _dataMap[key];
    public Zhenfa.CfgZhenfaLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

