
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public sealed partial class CfgRewardDrop : Luban.BeanBase
{
    public CfgRewardDrop(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["rate"].IsNumber) { throw new SerializationException(); }  Rate = _buf["rate"]; }
        { if(!_buf["dropType"].IsNumber) { throw new SerializationException(); }  DropType = (DropEnum.Type)_buf["dropType"].AsInt; }
        { var __json0 = _buf["dropReward"]; if(!__json0.IsArray) { throw new SerializationException(); } DropReward = new System.Collections.Generic.List<Reward.Drop>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Reward.Drop __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Reward.Drop.DeserializeDrop(__e0);  }  DropReward.Add(__v0); }   }
    }

    public static CfgRewardDrop DeserializeCfgRewardDrop(JSONNode _buf)
    {
        return new Reward.CfgRewardDrop(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Rate;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly DropEnum.Type DropType;
    /// <summary>
    /// 掉落项
    /// </summary>
    public readonly System.Collections.Generic.List<Reward.Drop> DropReward;
   
    public const int __ID__ = -1452269117;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DropReward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "rate:" + Rate + ","
        + "dropType:" + DropType + ","
        + "dropReward:" + Luban.StringUtil.CollectionToString(DropReward) + ","
        + "}";
    }
}

}

