
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public sealed partial class Drop : Luban.BeanBase
{
    public Drop(JSONNode _buf) 
    {
        { if(!_buf["rewardType"].IsNumber) { throw new SerializationException(); }  RewardType = (DropEnum.RewardType)_buf["rewardType"].AsInt; }
        { if(!_buf["rate"].IsNumber) { throw new SerializationException(); }  Rate = _buf["rate"]; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["num"].IsNumber) { throw new SerializationException(); }  Num = _buf["num"]; }
    }

    public static Drop DeserializeDrop(JSONNode _buf)
    {
        return new Reward.Drop(_buf);
    }

    /// <summary>
    /// 掉落类型
    /// </summary>
    public readonly DropEnum.RewardType RewardType;
    /// <summary>
    /// 概率，万分比
    /// </summary>
    public readonly int Rate;
    /// <summary>
    /// 物品ID或掉落组ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Num;
   
    public const int __ID__ = -1775216050;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "rewardType:" + RewardType + ","
        + "rate:" + Rate + ","
        + "id:" + Id + ","
        + "num:" + Num + ","
        + "}";
    }
}

}

