
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Reward
{
public partial class TbRewardDropBox
{
    private readonly System.Collections.Generic.Dictionary<int, Reward.CfgRewardDropBox> _dataMap;
    private readonly System.Collections.Generic.List<Reward.CfgRewardDropBox> _dataList;
    
    public TbRewardDropBox(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Reward.CfgRewardDropBox>();
        _dataList = new System.Collections.Generic.List<Reward.CfgRewardDropBox>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Reward.CfgRewardDropBox _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Reward.CfgRewardDropBox.DeserializeCfgRewardDropBox(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Reward.CfgRewardDropBox> DataMap => _dataMap;
    public System.Collections.Generic.List<Reward.CfgRewardDropBox> DataList => _dataList;

    public Reward.CfgRewardDropBox GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Reward.CfgRewardDropBox Get(int key) => _dataMap[key];
    public Reward.CfgRewardDropBox this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

