
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Math
{
public partial struct IntVec3
{
    public IntVec3(JSONNode _buf) 
    {
        { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
        { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
        { if(!_buf["z"].IsNumber) { throw new SerializationException(); }  Z = _buf["z"]; }
    }

    public static IntVec3 DeserializeIntVec3(JSONNode _buf)
    {
        return new Math.IntVec3(_buf);
    }

    /// <summary>
    /// x
    /// </summary>
    public readonly int X;
    /// <summary>
    /// y
    /// </summary>
    public readonly int Y;
    /// <summary>
    /// z
    /// </summary>
    public readonly int Z;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "}";
    }
}

}

