
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Math
{
public partial struct Rect
{
    public Rect(JSONNode _buf) 
    {
        { if(!_buf["width"].IsNumber) { throw new SerializationException(); }  Width = _buf["width"]; }
        { if(!_buf["height"].IsNumber) { throw new SerializationException(); }  Height = _buf["height"]; }
    }

    public static Rect DeserializeRect(JSONNode _buf)
    {
        return new Math.Rect(_buf);
    }

    /// <summary>
    /// width(厘米)
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// height(厘米)
    /// </summary>
    public readonly int Height;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "}";
    }
}

}

