
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Activity
{
public sealed partial class CfgRewardActivityLoginUse : Luban.BeanBase
{
    public CfgRewardActivityLoginUse(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["useNum"].IsNumber) { throw new SerializationException(); }  UseNum = _buf["useNum"]; }
        { var __json0 = _buf["reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<Prop.PropObj>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Prop.PropObj __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Prop.PropObj.DeserializePropObj(__e0);  }  Reward.Add(__v0); }   }
    }

    public static CfgRewardActivityLoginUse DeserializeCfgRewardActivityLoginUse(JSONNode _buf)
    {
        return new Activity.CfgRewardActivityLoginUse(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 消耗数量
    /// </summary>
    public readonly int UseNum;
    /// <summary>
    /// 奖励道具
    /// </summary>
    public readonly System.Collections.Generic.List<Prop.PropObj> Reward;
   
    public const int __ID__ = -425530815;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "useNum:" + UseNum + ","
        + "reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "}";
    }
}

}

