
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Activity
{
public partial class TbRewardActivityLoginUse
{
    private readonly System.Collections.Generic.Dictionary<int, Activity.CfgRewardActivityLoginUse> _dataMap;
    private readonly System.Collections.Generic.List<Activity.CfgRewardActivityLoginUse> _dataList;
    
    public TbRewardActivityLoginUse(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Activity.CfgRewardActivityLoginUse>();
        _dataList = new System.Collections.Generic.List<Activity.CfgRewardActivityLoginUse>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Activity.CfgRewardActivityLoginUse _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Activity.CfgRewardActivityLoginUse.DeserializeCfgRewardActivityLoginUse(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Activity.CfgRewardActivityLoginUse> DataMap => _dataMap;
    public System.Collections.Generic.List<Activity.CfgRewardActivityLoginUse> DataList => _dataList;

    public Activity.CfgRewardActivityLoginUse GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Activity.CfgRewardActivityLoginUse Get(int key) => _dataMap[key];
    public Activity.CfgRewardActivityLoginUse this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

