
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Message
{
public sealed partial class DanmakuData : Luban.BeanBase
{
    public DanmakuData(JSONNode _buf) 
    {
        { if(!_buf["danmakuType"].IsNumber) { throw new SerializationException(); }  DanmakuType = _buf["danmakuType"]; }
        { if(!_buf["danmakuSkin"].IsString) { throw new SerializationException(); }  DanmakuSkin = _buf["danmakuSkin"]; }
        { if(!_buf["danmakuIcon"].IsString) { throw new SerializationException(); }  DanmakuIcon = _buf["danmakuIcon"]; }
    }

    public static DanmakuData DeserializeDanmakuData(JSONNode _buf)
    {
        return new Message.DanmakuData(_buf);
    }

    /// <summary>
    /// 弹幕类型
    /// </summary>
    public readonly int DanmakuType;
    /// <summary>
    /// 弹幕皮肤路径
    /// </summary>
    public readonly string DanmakuSkin;
    /// <summary>
    /// 弹幕图标路径
    /// </summary>
    public readonly string DanmakuIcon;
   
    public const int __ID__ = 937357746;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "danmakuType:" + DanmakuType + ","
        + "danmakuSkin:" + DanmakuSkin + ","
        + "danmakuIcon:" + DanmakuIcon + ","
        + "}";
    }
}

}

