
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum HurtType
    {
        /// <summary>
        /// 均衡
        /// </summary>
        Balanced = 1,
        /// <summary>
        /// 劲力
        /// </summary>
        Strength = 2,
        /// <summary>
        /// 自然
        /// </summary>
        Nature = 3,
        /// <summary>
        /// 秘术
        /// </summary>
        Occult = 4,
    }

} 

