
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Unit
{
public sealed partial class TargetFilterData : Luban.BeanBase
{
    public TargetFilterData(JSONNode _buf) 
    {
        { if(!_buf["targetIsInBattle"].IsBoolean) { throw new SerializationException(); }  TargetIsInBattle = _buf["targetIsInBattle"]; }
        { if(!_buf["targetBodyType"].IsNumber) { throw new SerializationException(); }  TargetBodyType = (Unit.BodyType)_buf["targetBodyType"].AsInt; }
        { if(!_buf["targetBuffStateType"].IsNumber) { throw new SerializationException(); }  TargetBuffStateType = (Unit.BuffStateType)_buf["targetBuffStateType"].AsInt; }
        { if(!_buf["targetFiltrType"].IsNumber) { throw new SerializationException(); }  TargetFiltrType = (Target.TargetFiltrType)_buf["targetFiltrType"].AsInt; }
        { if(!_buf["targetNum"].IsNumber) { throw new SerializationException(); }  TargetNum = _buf["targetNum"]; }
        { if(!_buf["isExcludeSelf"].IsBoolean) { throw new SerializationException(); }  IsExcludeSelf = _buf["isExcludeSelf"]; }
    }

    public static TargetFilterData DeserializeTargetFilterData(JSONNode _buf)
    {
        return new Unit.TargetFilterData(_buf);
    }

    /// <summary>
    /// 目标是否必须在战斗中
    /// </summary>
    public readonly bool TargetIsInBattle;
    /// <summary>
    /// 目标体型(多选)
    /// </summary>
    public readonly Unit.BodyType TargetBodyType;
    /// <summary>
    /// 目标BUFF(多选)
    /// </summary>
    public readonly Unit.BuffStateType TargetBuffStateType;
    /// <summary>
    /// 目标过滤条件
    /// </summary>
    public readonly Target.TargetFiltrType TargetFiltrType;
    /// <summary>
    /// 目标数量上限
    /// </summary>
    public readonly int TargetNum;
    /// <summary>
    /// 是否排除自己
    /// </summary>
    public readonly bool IsExcludeSelf;
   
    public const int __ID__ = -666806563;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "targetIsInBattle:" + TargetIsInBattle + ","
        + "targetBodyType:" + TargetBodyType + ","
        + "targetBuffStateType:" + TargetBuffStateType + ","
        + "targetFiltrType:" + TargetFiltrType + ","
        + "targetNum:" + TargetNum + ","
        + "isExcludeSelf:" + IsExcludeSelf + ","
        + "}";
    }
}

}

