
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum UnitCategory
    {
        /// <summary>
        /// 角色
        /// </summary>
        Actor = 0,
        /// <summary>
        /// 子弹
        /// </summary>
        Bullet = 1,
        /// <summary>
        /// 道具
        /// </summary>
        Prop = 2,
        /// <summary>
        /// 其它
        /// </summary>
        Other = 3,
    }

} 

