
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum UnitEventType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 当出生时
        /// </summary>
        OnBorn = 1,
        /// <summary>
        /// 当血量增加时
        /// </summary>
        OnIncreaseHp = 2,
        /// <summary>
        /// 当血量减少时
        /// </summary>
        OnReduceHp = 3,
        /// <summary>
        /// 当血量变化时
        /// </summary>
        OnHpChange = 4,
        /// <summary>
        /// 当闪避普攻伤害时
        /// </summary>
        OnDodgeCommonAtk = 5,
        /// <summary>
        /// 当受到普攻伤害时
        /// </summary>
        OnRecvCommonAtk = 6,
        /// <summary>
        /// 当闪避技能伤害时
        /// </summary>
        OnDodgeSkill = 7,
        /// <summary>
        /// 当受到技能伤害时
        /// </summary>
        OnRecvSkill = 8,
        /// <summary>
        /// 当闪避伤害时
        /// </summary>
        OnDodgeDamage = 9,
        /// <summary>
        /// 当产生伤害
        /// </summary>
        OnDealtDamage = 10,
        /// <summary>
        /// 当受到伤害
        /// </summary>
        OnRecvDamage = 11,
        /// <summary>
        /// 当收到攻击时(无论命中与否)
        /// </summary>
        OnRecvAtk = 12,
        /// <summary>
        /// 当击杀单位时
        /// </summary>
        OnKill = 13,
        /// <summary>
        /// 当死亡时
        /// </summary>
        OnDeath = 14,
        /// <summary>
        /// 当死亡结束时(动画结束)
        /// </summary>
        OnDeathEnd = 15,
        /// <summary>
        /// 当主动技能开始时
        /// </summary>
        OnActiveSkillStart = 16,
        /// <summary>
        /// 当技能结束时
        /// </summary>
        OnSkillFinish = 17,
        /// <summary>
        /// 当普攻开始时
        /// </summary>
        OnCommonSkillStart = 18,
        /// <summary>
        /// 当普攻结束时
        /// </summary>
        OnCommonSkillFinish = 19,
        /// <summary>
        /// 当进入近战时
        /// </summary>
        OnEnterClosebat = 20,
        /// <summary>
        /// 当脱离近战时
        /// </summary>
        OnExitClosebat = 21,
        /// <summary>
        /// 当添加护盾
        /// </summary>
        OnShieldAdd = 22,
        /// <summary>
        /// 当移除护盾
        /// </summary>
        OnShieldRemove = 23,
        /// <summary>
        /// 当添加buff
        /// </summary>
        OnBuffAdd = 24,
        /// <summary>
        /// 当移除buff
        /// </summary>
        OnBuffRemove = 25,
        /// <summary>
        /// 当进入战斗
        /// </summary>
        OnBattleEnter = 26,
        /// <summary>
        /// 当退出战斗
        /// </summary>
        OnBattleExit = 27,
        /// <summary>
        /// 当进入重生状态
        /// </summary>
        OnRebornEnter = 28,
        /// <summary>
        /// 当退出重生状态
        /// </summary>
        OnRebornExit = 29,
        /// <summary>
        /// 当触发免疫死亡
        /// </summary>
        OnUndead = 30,
        /// <summary>
        /// 当死亡完成
        /// </summary>
        OnDeadFinish = 31,
        /// <summary>
        /// 当单位产生所有技能伤害
        /// </summary>
        OnDealtAllSkillDamage = 32,
    }

} 

