
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum UnitType
    {
        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 1,
        /// <summary>
        /// BOSS
        /// </summary>
        Boss = 2,
        /// <summary>
        /// 阵法
        /// </summary>
        MagicCircle = 3,
        /// <summary>
        /// 世界BOSS
        /// </summary>
        WorldBoss = 4,
        /// <summary>
        /// 怪物
        /// </summary>
        Monster = 10,
        /// <summary>
        /// 道具
        /// </summary>
        Prop = 11,
        /// <summary>
        /// 子弹
        /// </summary>
        Bullet = 100,
        /// <summary>
        /// 空体
        /// </summary>
        Empty = 101,
    }

} 

