
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Unit
{ 
    public enum UnitDamageType
    {
        /// <summary>
        /// 受到伤害
        /// </summary>
        ReceivedDamage = 0,
        /// <summary>
        /// 产生伤害
        /// </summary>
        DealtDamage = 1,
    }

} 

