
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Season
{
public sealed partial class CfgSeasonInsightRetain : Luban.BeanBase
{
    public CfgSeasonInsightRetain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["insightNum"].IsNumber) { throw new SerializationException(); }  InsightNum = _buf["insightNum"]; }
        { if(!_buf["insightRetain"].IsNumber) { throw new SerializationException(); }  InsightRetain = _buf["insightRetain"]; }
    }

    public static CfgSeasonInsightRetain DeserializeCfgSeasonInsightRetain(JSONNode _buf)
    {
        return new Season.CfgSeasonInsightRetain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 悟性丹数量
    /// </summary>
    public readonly int InsightNum;
    /// <summary>
    /// 悟性丹保留比例(万分比）
    /// </summary>
    public readonly int InsightRetain;
   
    public const int __ID__ = 1040286977;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "insightNum:" + InsightNum + ","
        + "insightRetain:" + InsightRetain + ","
        + "}";
    }
}

}

