
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Season
{
public sealed partial class CfgSeasonItemRetain : Luban.BeanBase
{
    public CfgSeasonItemRetain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["itemID"].IsNumber) { throw new SerializationException(); }  ItemID = _buf["itemID"]; }
        { if(!_buf["retain"].IsNumber) { throw new SerializationException(); }  Retain = _buf["retain"]; }
    }

    public static CfgSeasonItemRetain DeserializeCfgSeasonItemRetain(JSONNode _buf)
    {
        return new Season.CfgSeasonItemRetain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int ItemID;
    /// <summary>
    /// 保留比例(万分比）
    /// </summary>
    public readonly int Retain;
   
    public const int __ID__ = 332285492;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "itemID:" + ItemID + ","
        + "retain:" + Retain + ","
        + "}";
    }
}

}

