
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Season
{
public partial class TbInsightRetain
{
    private readonly System.Collections.Generic.Dictionary<int, Season.CfgSeasonInsightRetain> _dataMap;
    private readonly System.Collections.Generic.List<Season.CfgSeasonInsightRetain> _dataList;
    
    public TbInsightRetain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Season.CfgSeasonInsightRetain>();
        _dataList = new System.Collections.Generic.List<Season.CfgSeasonInsightRetain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Season.CfgSeasonInsightRetain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Season.CfgSeasonInsightRetain.DeserializeCfgSeasonInsightRetain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Season.CfgSeasonInsightRetain> DataMap => _dataMap;
    public System.Collections.Generic.List<Season.CfgSeasonInsightRetain> DataList => _dataList;

    public Season.CfgSeasonInsightRetain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Season.CfgSeasonInsightRetain Get(int key) => _dataMap[key];
    public Season.CfgSeasonInsightRetain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

