
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Season
{
public partial class TbItemRetain
{
    private readonly System.Collections.Generic.Dictionary<int, Season.CfgSeasonItemRetain> _dataMap;
    private readonly System.Collections.Generic.List<Season.CfgSeasonItemRetain> _dataList;
    
    public TbItemRetain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Season.CfgSeasonItemRetain>();
        _dataList = new System.Collections.Generic.List<Season.CfgSeasonItemRetain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Season.CfgSeasonItemRetain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Season.CfgSeasonItemRetain.DeserializeCfgSeasonItemRetain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Season.CfgSeasonItemRetain> DataMap => _dataMap;
    public System.Collections.Generic.List<Season.CfgSeasonItemRetain> DataList => _dataList;

    public Season.CfgSeasonItemRetain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Season.CfgSeasonItemRetain Get(int key) => _dataMap[key];
    public Season.CfgSeasonItemRetain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

