
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.DropEnum
{ 
    public enum RewardType
    {
        /// <summary>
        /// 道具
        /// </summary>
        Item = 1,
        /// <summary>
        /// 掉落组
        /// </summary>
        DropGroup = 2,
    }

} 

