
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.DropEnum
{ 
    public enum Type
    {
        /// <summary>
        /// 互斥
        /// </summary>
        Exclusion = 0,
        /// <summary>
        /// 独立
        /// </summary>
        Independence = 1,
    }

} 

