
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Gift
{
public sealed partial class SpecialReward : Luban.BeanBase
{
    public SpecialReward(JSONNode _buf) 
    {
        { if(!_buf["rewardType"].IsNumber) { throw new SerializationException(); }  RewardType = (Gift.specialRewardType)_buf["rewardType"].AsInt; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
    }

    public static SpecialReward DeserializeSpecialReward(JSONNode _buf)
    {
        return new Gift.SpecialReward(_buf);
    }

    /// <summary>
    /// 礼物特殊奖励类型
    /// </summary>
    public readonly Gift.specialRewardType RewardType;
    /// <summary>
    /// buff或技能id
    /// </summary>
    public readonly int Id;
   
    public const int __ID__ = -1080817398;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "rewardType:" + RewardType + ","
        + "id:" + Id + ","
        + "}";
    }
}

}

