
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gift
{ 
    public enum Type
    {
        /// <summary>
        /// 常规挂机场景
        /// </summary>
        Noraml = 1,
        /// <summary>
        /// 系统BOSS
        /// </summary>
        SystemBoss = 2,
        /// <summary>
        /// 论道活动时
        /// </summary>
        CampWar = 3,
        /// <summary>
        /// 世界BOSS
        /// </summary>
        WorldBoss = 4,
        /// <summary>
        /// 幻境副本
        /// </summary>
        Dungeon = 5,
        /// <summary>
        /// 宗门试炼
        /// </summary>
        Trial = 6,
        /// <summary>
        /// 宗门对决
        /// </summary>
        GuildCompetition = 7,
    }

} 

