
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Treasure
{
public sealed partial class CfgTreasureMain : Luban.BeanBase
{
    public CfgTreasureMain(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["itemid"].IsNumber) { throw new SerializationException(); }  Itemid = _buf["itemid"]; }
        { if(!_buf["num"].IsNumber) { throw new SerializationException(); }  Num = _buf["num"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Item.Quality)_buf["quality"].AsInt; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static CfgTreasureMain DeserializeCfgTreasureMain(JSONNode _buf)
    {
        return new Treasure.CfgTreasureMain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Itemid;
    /// <summary>
    /// 道具数量
    /// </summary>
    public readonly int Num;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Item.Quality Quality;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 效果
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 3975757;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "itemid:" + Itemid + ","
        + "num:" + Num + ","
        + "quality:" + Quality + ","
        + "level:" + Level + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

