
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Treasure
{
public partial class TbTreasureMain
{
    private readonly System.Collections.Generic.Dictionary<int, Treasure.CfgTreasureMain> _dataMap;
    private readonly System.Collections.Generic.List<Treasure.CfgTreasureMain> _dataList;
    
    public TbTreasureMain(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Treasure.CfgTreasureMain>();
        _dataList = new System.Collections.Generic.List<Treasure.CfgTreasureMain>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Treasure.CfgTreasureMain _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Treasure.CfgTreasureMain.DeserializeCfgTreasureMain(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Treasure.CfgTreasureMain> DataMap => _dataMap;
    public System.Collections.Generic.List<Treasure.CfgTreasureMain> DataList => _dataList;

    public Treasure.CfgTreasureMain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Treasure.CfgTreasureMain Get(int key) => _dataMap[key];
    public Treasure.CfgTreasureMain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

