
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Prop
{ 
    public enum Categories
    {
        /// <summary>
        /// 道具
        /// </summary>
        Item = 1,
        /// <summary>
        /// 皮肤
        /// </summary>
        Avatar = 2,
        /// <summary>
        /// 功法
        /// </summary>
        Skill = 3,
        /// <summary>
        /// 法宝
        /// </summary>
        Euip = 4,
        /// <summary>
        /// 坐骑
        /// </summary>
        Mount = 5,
        /// <summary>
        /// 称号
        /// </summary>
        Title = 6,
    }

} 

