
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Prop
{
public sealed partial class PropObj : Luban.BeanBase
{
    public PropObj(JSONNode _buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Prop.Categories)_buf["type"].AsInt; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static PropObj DeserializePropObj(JSONNode _buf)
    {
        return new Prop.PropObj(_buf);
    }

    /// <summary>
    /// 物品分类
    /// </summary>
    public readonly Prop.Categories Type;
    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品数量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = 2053455625;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "id:" + Id + ","
        + "count:" + Count + ","
        + "}";
    }
}

}

