
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Rank
{
public partial class RankReward
{
    private readonly System.Collections.Generic.Dictionary<int, Rank.CfgRankReward> _dataMap;
    private readonly System.Collections.Generic.List<Rank.CfgRankReward> _dataList;
    
    public RankReward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Rank.CfgRankReward>();
        _dataList = new System.Collections.Generic.List<Rank.CfgRankReward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Rank.CfgRankReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Rank.CfgRankReward.DeserializeCfgRankReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Rank.CfgRankReward> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank.CfgRankReward> DataList => _dataList;

    public Rank.CfgRankReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Rank.CfgRankReward Get(int key) => _dataMap[key];
    public Rank.CfgRankReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

